// Port of gas/test/ledgerFlow.test.ts, reshaped for the three-scope code register, plus the
// scope behaviour gas/ has no golden for.
//
// Two populations of test live here and it matters which is which:
//
//   FIXTURE PARITY — test/fixtures/ledger_flow.json and severities_scope.json are BYTE COPIES
//   from gas/, generated by the Python domain layer. They are never edited or regenerated
//   here. ledger_flow.json is fed through a RENAME SHIM (below) that maps gas/'s column names
//   onto sheetsDb.ts's and nothing else: the records, the scan ids and every expected value go
//   in verbatim. The shim follows test/reconcile.test.ts's, which maps the same 18 ledger
//   columns; the scans table needs one entry of its own (`shape`).
//
//   HAND-WRITTEN — the scope behaviour: which scan is "the previous scan" when three
//   registers interleave in one scan log, idempotency across scopes, the baseRows filter, and
//   the two episode-collision branches. Every number in these is either read off a fixture or
//   derived with the arithmetic written out in the test.
//
// WHAT IS NOT PORTED, and why. gas/'s ledgerFlow.test.ts continues into deleteScansCore and
// compactLedgerCore (gas/src/domain/maintenance.ts). Neither is in this package: compaction.ts
// ports only the pure retention predicates and its own header draws the line at the checkpoint
// replay. So ledger_flow.json's `delete_result` and `after_delete_scan2` steps, and the whole
// of ledger_compaction.json, are UNUSED here — deliberately, and named so that a later package
// adding maintenance.ts knows the goldens are already sitting in the fixtures directory.

import { describe, expect, it } from "vitest";
import {
  COMPACTED_ASSET,
  baseRows,
  emptyState,
  existingScanDeltas,
  latestScan,
  persistFlatScan,
  prevScanIdBySeverity,
  scansAsc,
  severityCountsFromObservations,
} from "../src/domain/ledgerCore";
import { SEVERITY_ORDER } from "../src/domain/config";
import { parseSeverities } from "../src/domain/compaction";
import type {
  EpisodeRow,
  LedgerRow,
  LedgerState,
  Observation,
  ScanRow,
} from "../src/domain/ledgerTypes";
import { cmp } from "../src/domain/util";
import { expectParity, fixture } from "./helpers";

// --------------------------------------------------------------------------- #
//  The rename shim
// --------------------------------------------------------------------------- #

/**
 * gas/ column -> gas_devsecops column, for the LEDGER rows. Identical to the table in
 * test/reconcile.test.ts, because it is the same 18-column fixture shape. Source of truth for
 * the right-hand side is TAB_HEADERS[TABS.ledger] in src/server/sheetsDb.ts, mirrored as
 * LEDGER_COLUMNS in src/domain/ledgerTypes.ts.
 */
const RENAMED: Record<string, string> = {
  vuln_key: "finding_key",
  cve: "identifier",
  asset_id: "repo_id",
  asset_name: "repo_name",
  cloud: "platform",
};

/** Ledger fields with no counterpart, listed rather than silently dropped. */
const UNMAPPED: Record<string, string> = {
  asset_type: "the asset is always a repository; REPOSITORY vs REPOSITORY_BRANCH is `branch`",
  subscription_name: "no cloud subscription on a repo; ownership is owner_project from projects[]",
  subscription_ext_id: "same — see owner_project / owner_path",
};

/** Ledger fields that pass through under their own name. */
const PASSTHROUGH = [
  "severity", "first_seen", "last_seen", "status", "resolved_at", "resolution_src",
  "reopened_count", "first_scan_id", "last_scan_id", "tags_json",
];

/**
 * SCAN fields with no counterpart. Exactly one, and it is the divergence persistFlatScan
 * documents: this register's ScanRow has no `shape` column at all, because there is no
 * grouped-by-asset variant — every scope's fetch is a flat per-finding scan.
 */
const UNMAPPED_SCAN: Record<string, string> = {
  shape: "no grouped shape here; ScanRow has no `shape` column and every scan is flat",
};

/** Scan fields that pass through under their own name. */
const PASSTHROUGH_SCAN = [
  "scan_id", "ts", "mode", "total", "new_count", "resolved_count", "reopened_count",
  "severities", "sealed",
];

/**
 * The one column this register ADDS to the scan row. Not a rename of anything in the fixture —
 * gas/ had one register and never needed it.
 */
const ADDED_SCAN = ["scope"];

const fx = fixture("ledger_flow");
const SCAN_IDS = ["s1", "s2", "s3", "s4"] as const;

/** gas/'s `id:A` key becomes this register's scope-prefixed `sca:id:A` (lifecycle.findingKey). */
const renameKey = (k: string): string => `sca:${k}`;

function shimRow(row: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = { scope: "sca" };
  for (const [k, v] of Object.entries(row)) {
    if (k in UNMAPPED) continue;
    out[RENAMED[k] ?? k] = k === "vuln_key" ? renameKey(String(v)) : v;
  }
  return out;
}

function shimLedger(ledger: Record<string, any>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, row] of Object.entries(ledger)) out[renameKey(k)] = shimRow(row);
  return out;
}

function shimScans(scans: Record<string, unknown>[]): Record<string, unknown>[] {
  return scans.map((r) => {
    const out: Record<string, unknown> = { scope: "sca" };
    for (const [k, v] of Object.entries(r)) {
      if (k in UNMAPPED_SCAN) continue;
      out[k] = v;
    }
    return out;
  });
}

function shimObservations(obs: any[]): unknown[] {
  return obs.map((o) => ({
    scan_id: o.scan_id,
    finding_key: renameKey(o.vuln_key),
    present: o.present,
    severity: o.severity,
    status: o.status,
  }));
}

function obsTable(observationsByScan: Record<string, Observation[]>): Observation[] {
  const all = Object.values(observationsByScan).flat();
  return [...all].sort(
    (a, b) => cmp(a.scan_id, b.scan_id) || cmp(a.finding_key, b.finding_key),
  );
}

describe("ledger_flow.json rename shim — the mapping itself", () => {
  const ledgerFields = new Set<string>();
  const scanFields = new Set<string>();
  const obsFields = new Set<string>();
  for (const step of Object.values<any>(fx.steps)) {
    if (!step || typeof step !== "object" || !step.ledger) continue; // delete_result
    for (const row of Object.values<any>(step.ledger)) {
      for (const k of Object.keys(row)) ledgerFields.add(k);
    }
    for (const row of step.scans) for (const k of Object.keys(row)) scanFields.add(k);
    for (const row of step.observations) for (const k of Object.keys(row)) obsFields.add(k);
  }

  it("every LEDGER field the fixture carries is renamed, passed through, or listed unmapped", () => {
    const accounted = new Set([
      ...Object.keys(RENAMED),
      ...Object.keys(UNMAPPED),
      ...PASSTHROUGH,
    ]);
    expect([...ledgerFields].filter((f) => !accounted.has(f)).sort()).toEqual([]);
    // 18 fields: 5 renamed + 3 unmapped + 10 passed through — the same 18 reconcile.test.ts
    // accounts for, since both fixtures were exported from the same Python row shape.
    expect(ledgerFields.size).toBe(18);
    expect(Object.keys(RENAMED).length + Object.keys(UNMAPPED).length + PASSTHROUGH.length)
      .toBe(18);
  });

  it("every SCAN field is passed through or listed unmapped, and `scope` is the one addition", () => {
    const accounted = new Set([...Object.keys(UNMAPPED_SCAN), ...PASSTHROUGH_SCAN]);
    expect([...scanFields].filter((f) => !accounted.has(f)).sort()).toEqual([]);
    expect(scanFields.size).toBe(10); // 1 unmapped (`shape`) + 9 passed through
    expect(Object.keys(UNMAPPED_SCAN).length + PASSTHROUGH_SCAN.length).toBe(10);
    // The fixture cannot carry `scope`; gas/ had one register.
    expect(ADDED_SCAN.every((c) => !scanFields.has(c))).toBe(true);
  });

  it("observations rename only the key column", () => {
    expect([...obsFields].sort()).toEqual(
      ["present", "scan_id", "severity", "status", "vuln_key"],
    );
  });
});

// --------------------------------------------------------------------------- #
//  ledger_flow.json parity, scope sca
// --------------------------------------------------------------------------- #

describe("ledger flow (SQLite fixture parity, scope sca)", () => {
  it("persist x4 reproduces every table state", () => {
    const state = emptyState();
    const obsByScan: Record<string, Observation[]> = {};
    const stepNames = ["after_scan1", "after_scan2", "after_scan3", "after_scan4"];

    SCAN_IDS.forEach((key, i) => {
      const scan = fx.scans[key];
      const { observations } = persistFlatScan(state, scan.records, {
        scope: "sca",
        mode: "live",
        scanId: scan.id,
      });
      obsByScan[scan.id] = observations;
      const expected = fx.steps[stepNames[i]!];
      expectParity(scansAsc(state.scans), shimScans(expected.scans));
      expectParity(state.ledger, shimLedger(expected.ledger));
      expectParity(obsTable(obsByScan), shimObservations(expected.observations));
      expectParity(state.episodes, expected.episodes);
    });
  });

  it("every persisted scan row carries scope and the two Drive refs", () => {
    const state = emptyState();
    const { scanRow } = persistFlatScan(state, fx.scans.s1.records, {
      scope: "sca",
      mode: "live",
      scanId: fx.scans.s1.id,
      rawRef: "drive-raw-1",
      obsRef: "drive-obs-1",
    });
    expect(scanRow!.scope).toBe("sca");
    expect(scanRow!.raw_ref).toBe("drive-raw-1");
    expect(scanRow!.obs_ref).toBe("drive-obs-1");
    expect(scanRow!.sealed).toBe(0);
    // sca and sast fold no twins, so the stats are zeroed rather than absent.
    expect(persistFlatScan(emptyState(), fx.scans.s1.records, {
      scope: "sca", mode: "live", scanId: fx.scans.s1.id,
    }).twinStats).toEqual({ keys: 0, folded: 0, medianGapDays: null });
  });

  it("re-persisting an existing (scan_id, scope) is a no-op returning stored deltas", () => {
    const state = emptyState();
    const first = persistFlatScan(state, fx.scans.s1.records, {
      scope: "sca", mode: "live", scanId: fx.scans.s1.id,
    });
    const again = persistFlatScan(state, [], {
      scope: "sca", mode: "live", scanId: fx.scans.s1.id,
    });
    expect(again.deltas).toEqual(first.deltas);
    expect(again.scanRow).toBeNull();
    expect(again.observations).toEqual([]);
    expect(state.scans.length).toBe(1);
  });

  /**
   * THE DIVERGENCE FROM gas/, pinned. One sync job carries one scan_id and steps through the
   * scopes (jobsStore.ts: "sync_id -> scan_id ... step_index -> scope"), so the same scan_id
   * legitimately appears once per scope. Keyed on scan_id alone — gas/'s rule, which was
   * correct for a one-register product — the sca step's row would answer for the sast and
   * secrets steps: both would return sca's deltas, write no scan row, and reconcile nothing,
   * with every caller seeing a successful idempotent replay.
   */
  it("the SAME scan_id under a DIFFERENT scope is not a no-op", () => {
    const state = emptyState();
    const id = fx.scans.s1.id;
    persistFlatScan(state, fx.scans.s1.records, { scope: "sca", mode: "live", scanId: id });
    const sast = persistFlatScan(state, [], { scope: "sast", mode: "live", scanId: id });
    expect(sast.scanRow).not.toBeNull();
    expect(sast.scanRow!.scope).toBe("sast");
    expect(state.scans.length).toBe(2);
    expect(state.scans.map((r) => r.scope)).toEqual(["sca", "sast"]);
    // And the whole-register question still has an answer.
    expect(existingScanDeltas(state.scans, id)).not.toBeNull();
    expect(existingScanDeltas(state.scans, id, "secrets")).toBeNull();
  });
});

// --------------------------------------------------------------------------- #
//  severities_scope.json — the severity scope a scan row carries
// --------------------------------------------------------------------------- #

/**
 * Look a serialize case up by its input, so every severities text below is a FIXTURE VALUE
 * rather than a literal retyped from memory. Throws rather than asserting: it is called at
 * module scope, where `expect` is not available.
 */
const sevFx = fixture("severities_scope");
function serializedFor(input: string[] | null): string | null {
  const hit = sevFx.serialize.find(
    (c: any) => JSON.stringify(c.input) === JSON.stringify(input),
  );
  if (!hit) {
    throw new Error(`severities_scope.json has no serialize case for ${JSON.stringify(input)}`);
  }
  return hit.expected;
}

describe("scan severity scope (severities_scope.json)", () => {
  it("the scan row stores exactly what serializeSeverities produced", () => {
    for (const c of sevFx.serialize) {
      const state = emptyState();
      const { scanRow } = persistFlatScan(state, [], {
        scope: "sca",
        mode: "live",
        scanId: "2026-02-01T00:00:00Z",
        scannedSeverities: c.input,
      });
      expect(scanRow!.severities, JSON.stringify(c.input)).toBe(c.expected);
    }
  });

  /**
   * On secrets the gate is OFF (CLAUDE.md; config.DEFAULT_FETCH_SEVERITIES.secrets is []), so
   * the register is the whole CODE population. Both spellings of "no gate" — the empty list
   * and the full selectable set — have to land on the same stored null, because a scan row
   * that claimed a scope would make reconcile refuse to resolve anything outside it.
   */
  it("a secrets scan stores severities = null whether the gate is [] or the full set", () => {
    expect(serializedFor([])).toBeNull();
    expect(serializedFor(["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"])).toBeNull();
    for (const gate of [[], ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]]) {
      const state = emptyState();
      const { scanRow } = persistFlatScan(state, [], {
        scope: "secrets",
        mode: "live",
        scanId: "2026-02-01T00:00:00Z",
        scannedSeverities: gate,
      });
      expect(scanRow!.severities).toBeNull();
      // Unscoped, so the guard map covers every severity.
      expect(Object.keys(prevScanIdBySeverity(state.scans, "secrets")!).sort())
        .toEqual([...SEVERITY_ORDER].sort());
    }
  });

  it("a single scan's guard map covers exactly the severities it scanned", () => {
    for (const c of sevFx.serialize) {
      const row = scanRow({ scan_id: "s", ts: "2026-02-01T00:00:00Z", scope: "sca" });
      row.severities = c.expected;
      const map = prevScanIdBySeverity([row], "sca")!;
      const covered = parseSeverities(c.expected) ?? [...SEVERITY_ORDER];
      expect(Object.keys(map).sort(), JSON.stringify(c.input)).toEqual([...covered].sort());
      expect(new Set(Object.values(map))).toEqual(new Set(["s"]));
    }
  });
});

// --------------------------------------------------------------------------- #
//  The scope generalisation: which scan is "the previous scan"
// --------------------------------------------------------------------------- #

function scanRow(over: Partial<ScanRow> & Pick<ScanRow, "scan_id" | "ts" | "scope">): ScanRow {
  return {
    mode: "live", severities: null, total: 0, new_count: 0, resolved_count: 0,
    reopened_count: 0, raw_ref: null, obs_ref: null, sealed: 0,
    ...over,
  };
}

/**
 * Three scans interleaving two registers, with the LATER sca scan severity-scoped so an
 * unfiltered walk cannot accidentally agree with a filtered one:
 *
 *   S1  2026-01-01  sca      ["CRITICAL", "HIGH"]
 *   S2  2026-01-02  secrets  null (unscoped — the gate is off on secrets)
 *   S3  2026-01-03  sca      ["HIGH"]
 */
const S1 = scanRow({
  scan_id: "2026-01-01T00:00:00Z", ts: "2026-01-01T00:00:00Z", scope: "sca",
  severities: serializedFor(["CRITICAL", "HIGH"]),
});
const S2 = scanRow({
  scan_id: "2026-01-02T00:00:00Z", ts: "2026-01-02T00:00:00Z", scope: "secrets",
  severities: serializedFor([]),
});
// The fixture has no bare ["HIGH"] serialize case; ["bogus", "HIGH"] is its case that yields
// exactly '["HIGH"]' (the unknown severity is dropped), and its `parse` half round-trips it.
const S3 = scanRow({
  scan_id: "2026-01-03T00:00:00Z", ts: "2026-01-03T00:00:00Z", scope: "sca",
  severities: serializedFor(["bogus", "HIGH"]),
});
const INTERLEAVED = [S3, S1, S2]; // deliberately out of order — the readers sort

describe("scan-log readers are scope-aware", () => {
  it("scansAsc sorts by ts and narrows to a scope when asked", () => {
    expect(scansAsc(INTERLEAVED).map((r) => r.scan_id))
      .toEqual([S1.scan_id, S2.scan_id, S3.scan_id]);
    expect(scansAsc(INTERLEAVED, "sca").map((r) => r.scan_id)).toEqual([S1.scan_id, S3.scan_id]);
    expect(scansAsc(INTERLEAVED, "secrets").map((r) => r.scan_id)).toEqual([S2.scan_id]);
    expect(scansAsc(INTERLEAVED, "sast")).toEqual([]);
  });

  it("latestScan answers with the scope's own newest scan, not the log's", () => {
    expect(latestScan(INTERLEAVED, "sca")!.scan_id).toBe(S3.scan_id);
    // S3 is newer than S2 in the log; it is not a secrets scan, so it is not the answer.
    expect(latestScan(INTERLEAVED, "secrets")!.scan_id).toBe(S2.scan_id);
    expect(latestScan(INTERLEAVED, "sast")).toBeNull();
  });

  /**
   * The guard feeds resolve-by-disappearance, so this is the assertion that matters most:
   * "the previous scan that covered this severity" has to mean the previous scan OF THIS
   * REGISTER. Drop the filter and the secrets map below reads {HIGH: S3, ...rest: S2} — S3 is
   * a sca scan — and every secrets row whose last_scan_id is not S3 stops being adjudicated
   * while every HIGH secrets row is compared against a scan that never looked for it.
   */
  it("prevScanIdBySeverity reads the previous scan OF THE SAME SCOPE", () => {
    // sca: S3 covers HIGH; CRITICAL falls back to S1, which is the older sca scan. The other
    // four severities were never in a sca scan's scope, so they are absent.
    expect(prevScanIdBySeverity(INTERLEAVED, "sca")).toEqual({
      HIGH: S3.scan_id,
      CRITICAL: S1.scan_id,
    });
    // secrets: one unscoped scan covers all six, and S3 (newer, but sca) is invisible here.
    const secrets = prevScanIdBySeverity(INTERLEAVED, "secrets")!;
    expect(Object.keys(secrets).sort()).toEqual([...SEVERITY_ORDER].sort());
    expect(new Set(Object.values(secrets))).toEqual(new Set([S2.scan_id]));
    expect(prevScanIdBySeverity(INTERLEAVED, "sast")).toBeNull();
  });

  it("persistFlatScan reconciles against its own scope's previous scan", () => {
    // Two registers, alternating, each seeing one finding that then disappears from its own
    // next scan. Neither disappearance may be attributed to the other register's scan.
    const state = emptyState();
    const scaRec = { id: "A", name: "CVE-A", severity: "HIGH", status: "OPEN" };
    const secRec = {
      secretDataId: "sd-1", path: "app/.env", lineNumber: 3, severity: "LOW", status: "OPEN",
      resource: { id: "r1", name: "org/repo", type: "REPOSITORY" },
    };
    persistFlatScan(state, [scaRec], {
      scope: "sca", mode: "live", scanId: "2026-03-01T00:00:00Z",
    });
    persistFlatScan(state, [secRec], {
      scope: "secrets", mode: "live", scanId: "2026-03-02T00:00:00Z",
    });
    // A sca scan with the finding gone: the sca row resolves, the secrets row does not.
    const d3 = persistFlatScan(state, [], {
      scope: "sca", mode: "live", scanId: "2026-03-03T00:00:00Z",
    });
    expect(d3.deltas).toEqual({ new_count: 0, resolved_count: 1, reopened_count: 0 });
    expect(state.ledger["sca:id:A"]!.status).toBe("RESOLVED");
    expect(state.ledger["sca:id:A"]!.resolved_at).toBe("2026-03-03T00:00:00Z");
    const secretKey = Object.keys(state.ledger).find((k) => k.startsWith("secrets:"))!;
    expect(state.ledger[secretKey]!.status).toBe("OPEN");
    expect(state.ledger[secretKey]!.removed_at).toBeNull();
    // Now the secrets scan that actually stops listing it.
    const d4 = persistFlatScan(state, [], {
      scope: "secrets", mode: "live", scanId: "2026-03-04T00:00:00Z",
    });
    expect(d4.deltas).toEqual({ new_count: 0, resolved_count: 1, reopened_count: 0 });
    expect(state.ledger[secretKey]!.status).toBe("RESOLVED");
    expect(state.ledger[secretKey]!.removed_at).toBe("2026-03-04T00:00:00Z");
    // Removed is not rotated.
    expect(state.ledger[secretKey]!.rotated_at).toBeNull();
  });

  /**
   * THE SAME SYNC ID ACROSS SCOPES, which is how a real sync arrives: jobsStore.ts's JobRow
   * carries ONE scan_id and ONE scope-at-a-time, so all three steps of a sync share a scan_id.
   * Two syncs, three scopes, and the sca step of the second sync must not resolve anything
   * that belongs to the other two registers.
   *
   * MEASURED, not assumed: with the whole ledger handed to reconcile, its disappearance loop
   * walks every row regardless of scope, and the only thing standing between it and another
   * register's rows is `row.last_scan_id !== expectedPrev` — which is FALSE precisely when the
   * scan ids coincide, i.e. on every real sync. Before persistFlatScan partitioned the ledger,
   * this test resolved the sast and secrets rows on the sca step of sync 2. See the partition
   * note in persistFlatScan.
   */
  it("a shared sync id does not let one scope's scan resolve another scope's rows", () => {
    const state = emptyState();
    const SYNC1 = "2026-04-01T00:00:00Z";
    const SYNC2 = "2026-04-08T00:00:00Z";
    const scaRec = { id: "A", name: "CVE-A", severity: "HIGH", status: "OPEN" };
    const sastRec = { id: "S", name: "SQL Injection", severity: "HIGH", status: "OPEN" };
    const secRec = {
      secretDataId: "sd-1", path: "app/.env", lineNumber: 3, severity: "LOW", status: "OPEN",
      resource: { id: "r1", name: "org/repo", type: "REPOSITORY" },
    };

    // Sync 1: all three steps, one scan id.
    persistFlatScan(state, [scaRec], { scope: "sca", mode: "live", scanId: SYNC1 });
    persistFlatScan(state, [sastRec], { scope: "sast", mode: "live", scanId: SYNC1 });
    persistFlatScan(state, [secRec], { scope: "secrets", mode: "live", scanId: SYNC1 });
    expect(state.scans.map((r) => r.scan_id)).toEqual([SYNC1, SYNC1, SYNC1]);
    const secretKey = Object.keys(state.ledger).find((k) => k.startsWith("secrets:"))!;
    for (const k of ["sca:id:A", "sast:id:S", secretKey]) {
      expect(state.ledger[k]!.last_scan_id, k).toBe(SYNC1);
    }

    // Sync 2, step 1 of 3: sca only, and its finding is gone.
    const d = persistFlatScan(state, [], { scope: "sca", mode: "live", scanId: SYNC2 });
    expect(d.deltas).toEqual({ new_count: 0, resolved_count: 1, reopened_count: 0 });
    expect(state.ledger["sca:id:A"]!.status).toBe("RESOLVED");
    // The other two registers have not been scanned yet in sync 2 and must be untouched.
    expect(state.ledger["sast:id:S"]!.status).toBe("OPEN");
    expect(state.ledger["sast:id:S"]!.resolved_at).toBeNull();
    expect(state.ledger[secretKey]!.status).toBe("OPEN");
    expect(state.ledger[secretKey]!.removed_at).toBeNull();
    // And the observation set names only this register's findings.
    expect(d.observations.map((o) => o.finding_key)).toEqual(["sca:id:A"]);
  });
});

// --------------------------------------------------------------------------- #
//  Episode collisions
// --------------------------------------------------------------------------- #

function episode(over: Partial<EpisodeRow> & Pick<EpisodeRow, "finding_key" | "scope">): EpisodeRow {
  return {
    identifier: null, component: null, severity: "HIGH", first_seen: "2026-01-01T00:00:00Z",
    resolved_at: "2026-02-01T00:00:00Z", resolution_src: "api", reopened_count: 0,
    compaction_id: "cmp-1", superseded_by_scan: null, fix_date: null, fix_observed_at: null,
    has_kev: null, has_exploit: null, epss: null, cwe: null, language: null,
    owner_project: null,
    ...over,
  };
}

describe("reconcileEpisodeCollisions", () => {
  it("a re-listed OPEN finding reopens its sealed episode: new -> reopened", () => {
    const state = emptyState();
    state.episodes.push(episode({ finding_key: "sca:id:A", scope: "sca", reopened_count: 2 }));
    const { deltas } = persistFlatScan(
      state,
      [{ id: "A", name: "CVE-A", severity: "HIGH", status: "OPEN" }],
      { scope: "sca", mode: "live", scanId: "2026-03-01T00:00:00Z" },
    );
    // reconcile counted it new; the collision reclassifies it.
    expect(deltas).toEqual({ new_count: 0, resolved_count: 0, reopened_count: 1 });
    expect(state.ledger["sca:id:A"]!.reopened_count).toBe(3); // episode's 2 + this reopen
    expect(state.episodes[0]!.superseded_by_scan).toBe("2026-03-01T00:00:00Z");
  });

  it("a re-listed already-RESOLVED finding is dropped, and hands its owner to the episode", () => {
    const state = emptyState();
    state.episodes.push(episode({ finding_key: "sca:id:B", scope: "sca", owner_project: null }));
    const { deltas } = persistFlatScan(
      state,
      [{
        id: "B", name: "CVE-B", severity: "HIGH", status: "RESOLVED",
        resolvedAt: "2026-02-01T00:00:00Z",
        projects: [{ slug: "team-x", name: "Team X", isFolder: false }],
      }],
      { scope: "sca", mode: "live", scanId: "2026-03-01T00:00:00Z" },
    );
    expect(deltas).toEqual({ new_count: 0, resolved_count: 0, reopened_count: 0 });
    expect(state.ledger["sca:id:B"]).toBeUndefined();
    expect(state.episodes[0]!.superseded_by_scan).toBeNull();
    // DIVERGENCE from gas/, which transfers tags_json: this register's EpisodeRow has no
    // tags_json column and is attributed by owner_project instead.
    expect(state.episodes[0]!.owner_project).toBe("Team X");
  });

  it("the owner transfer is fill-only — an episode that has one keeps it", () => {
    const state = emptyState();
    state.episodes.push(
      episode({ finding_key: "sca:id:B", scope: "sca", owner_project: "Team Original" }),
    );
    persistFlatScan(
      state,
      [{
        id: "B", name: "CVE-B", severity: "HIGH", status: "RESOLVED",
        resolvedAt: "2026-02-01T00:00:00Z",
        projects: [{ slug: "team-x", name: "Team X", isFolder: false }],
      }],
      { scope: "sca", mode: "live", scanId: "2026-03-01T00:00:00Z" },
    );
    expect(state.episodes[0]!.owner_project).toBe("Team Original");
  });
});

// --------------------------------------------------------------------------- #
//  baseRows: the union, the placeholder, and the scope filter
// --------------------------------------------------------------------------- #

const NOW = Date.parse("2026-07-25T00:00:00Z");

function ledgerRow(over: Partial<LedgerRow> & Pick<LedgerRow, "finding_key" | "scope">): LedgerRow {
  return {
    identifier: null, component: null, severity: "HIGH",
    repo_id: null, repo_name: null, branch: null, platform: null,
    first_seen: "2026-07-05T00:00:00Z", last_seen: "2026-07-20T00:00:00Z", status: "OPEN",
    resolved_at: null, resolution_src: null, reopened_count: 0,
    first_scan_id: null, last_scan_id: null,
    fix_date: null, fix_observed_at: null, fixed_version: null,
    has_kev: null, has_exploit: null, epss: null, risk_observed_at: null,
    cwe: null, ai_verdict: null, language: null, file_path: null, start_line: null,
    origin: null, secret_kind: null, rotated_at: null, removed_at: null,
    validation_state: null, validated_at: null, confidence: null,
    owner_project: null, owner_path: null, tags_json: null,
    ...over,
  };
}

describe("baseRows", () => {
  function threeScopeState(): LedgerState {
    const state = emptyState();
    for (const scope of ["sca", "sast", "secrets"] as const) {
      state.ledger[`${scope}:id:1`] = ledgerRow({ finding_key: `${scope}:id:1`, scope });
    }
    state.episodes.push(
      episode({ finding_key: "sast:id:ep", scope: "sast" }),
      episode({ finding_key: "secrets:h:dead", scope: "secrets" }),
    );
    return state;
  }

  it("unions live rows with non-superseded episodes, spanning all three scopes", () => {
    const rows = baseRows(threeScopeState(), { now: NOW });
    expect(rows.map((r) => r.finding_key).sort()).toEqual([
      "sast:id:1", "sast:id:ep", "sca:id:1", "secrets:h:dead", "secrets:id:1",
    ]);
  });

  it("scope narrows both halves of the union", () => {
    const state = threeScopeState();
    expect(baseRows(state, { now: NOW, scope: "sca" }).map((r) => r.finding_key))
      .toEqual(["sca:id:1"]);
    expect(baseRows(state, { now: NOW, scope: "sast" }).map((r) => r.finding_key).sort())
      .toEqual(["sast:id:1", "sast:id:ep"]);
    expect(baseRows(state, { now: NOW, scope: "secrets" }).map((r) => r.finding_key).sort())
      .toEqual(["secrets:h:dead", "secrets:id:1"]);
  });

  it("episodes surface with the (compacted) placeholder and a measurable MTTR", () => {
    const rows = baseRows(threeScopeState(), { now: NOW });
    const compacted = rows.filter((r) => r.repo_name === COMPACTED_ASSET);
    expect(compacted.map((r) => r.finding_key).sort())
      .toEqual(["sast:id:ep", "secrets:h:dead"]);
    for (const r of compacted) {
      expect(r.status).toBe("RESOLVED");
      // episode(): 2026-01-01 -> 2026-02-01 is 31 days.
      expect(r.mttr_days).toBeCloseTo(31, 6);
      expect(r.age_days).toBeNull();
    }
  });

  it("a live row is authoritative over an episode with the same key", () => {
    const state = emptyState();
    state.ledger["sca:id:1"] = ledgerRow({ finding_key: "sca:id:1", scope: "sca" });
    state.episodes.push(episode({ finding_key: "sca:id:1", scope: "sca" }));
    const rows = baseRows(state, { now: NOW });
    expect(rows.length).toBe(1);
    expect(rows[0]!.repo_name).not.toBe(COMPACTED_ASSET);
  });

  it("a superseded episode is not surfaced", () => {
    const state = emptyState();
    state.episodes.push(
      episode({ finding_key: "sca:id:9", scope: "sca", superseded_by_scan: "s7" }),
    );
    expect(baseRows(state, { now: NOW })).toEqual([]);
  });
});

// --------------------------------------------------------------------------- #
//  severityCountsFromObservations
// --------------------------------------------------------------------------- #

describe("severityCountsFromObservations", () => {
  it("counts present observations only, through normalizeSeverity", () => {
    const obs: Pick<Observation, "present" | "severity">[] = [
      { present: 1, severity: "CRITICAL" },
      { present: 1, severity: "critical" },
      { present: 1, severity: "INFORMATIONAL" },
      { present: 1, severity: "nonsense" },
      { present: 1, severity: null },
      { present: 0, severity: "CRITICAL" }, // resolved-by-disappearance: not in this scan
    ];
    expect(severityCountsFromObservations(obs))
      .toEqual({ CRITICAL: 2, INFO: 1, UNKNOWN: 2 });
    expect(severityCountsFromObservations([])).toEqual({});
  });

  it("matches the fixture's own first scan", () => {
    const state = emptyState();
    const { observations } = persistFlatScan(state, fx.scans.s1.records, {
      scope: "sca", mode: "live", scanId: fx.scans.s1.id,
    });
    // s1 lists one CRITICAL (A) and one HIGH (B); both are present.
    expect(severityCountsFromObservations(observations)).toEqual({ CRITICAL: 1, HIGH: 1 });
  });
});
