// Port of the delete/compaction half of gas/test/ledgerFlow.test.ts, reshaped for the
// three-scope code register, plus the scope behaviour gas/ has no golden for.
//
// Two populations of test live here and it matters which is which:
//
//   FIXTURE PARITY — test/fixtures/ledger_flow.json's `delete_result` / `after_delete_scan2`
//   steps and the whole of test/fixtures/ledger_compaction.json are BYTE COPIES from gas/,
//   generated by the Python domain layer. They are never edited or regenerated here. D3's
//   ledgerCore.test.ts consumed `after_scan1..4` and named these two goldens as "sitting in
//   the fixtures directory" for the package that added maintenance.ts; this is that package.
//   Both fixtures are fed through the SAME RENAME SHIM D3 wrote (copied below rather than
//   imported, so neither test file can quietly change the other's oracle) — it maps gas/'s
//   column names onto sheetsDb.ts's and nothing else. The records, the scan ids and every
//   expected value go in verbatim.
//
//   HAND-WRITTEN — the scope behaviour: a delete that spans registers, the cross-scope
//   compaction floor, the sealed-scan refusal, the two column contracts (`toEpisodeRow` and
//   `compactionRow` against TAB_HEADERS), and the cutoffMs/isAfter boundary.
//
// THE FIXTURES ARE SINGLE-SCOPE (gas/ had one register), so every fixture row is shimmed to
// `sca`. The three-register behaviour has no golden and cannot have one — it is pinned by the
// hand-written cases, whose numbers are derived with the arithmetic written out in the test.

import { describe, expect, it } from "vitest";
import {
  baseRows,
  emptyState,
  persistFlatScan,
  scansAsc,
} from "../src/domain/ledgerCore";
import { selectSealCandidates } from "../src/domain/compaction";
import {
  CHECKPOINT_VERSION,
  LedgerRebuildError,
  RETENTION_MIN_DAYS,
  SealedScanError,
  compactLedgerCore,
  compactionRow,
  cutoffMs,
  deleteScansCore,
  isAfter,
  loadReplayPayloads,
  recordsFromPayload,
  settledEpisodeRows,
  toEpisodeRow,
  type Checkpoint,
} from "../src/domain/maintenance";
import { MIN_UNSEALED_FLAT_SCANS } from "../src/domain/config";
import type {
  LedgerRow,
  LedgerState,
  Observation,
  ScanRow,
} from "../src/domain/ledgerTypes";
import { TABS, TAB_HEADERS } from "../src/server/sheetsDb";
import { cmp, type Rec } from "../src/domain/util";
import { expectParity, fixture } from "./helpers";

// --------------------------------------------------------------------------- #
//  The rename shim — D3's, copied from test/ledgerCore.test.ts
// --------------------------------------------------------------------------- #

/** gas/ column -> gas_devsecops column, for LEDGER rows (= TAB_HEADERS[TABS.ledger]). */
const RENAMED: Record<string, string> = {
  vuln_key: "finding_key",
  cve: "identifier",
  asset_id: "repo_id",
  asset_name: "repo_name",
  cloud: "platform",
};

/** Ledger fields with no counterpart, listed rather than silently dropped. */
const UNMAPPED: Record<string, string> = {
  asset_type: "the asset is always a repository; REPOSITORY vs REPOSITORY_BRANCH is `branch`",
  subscription_name: "no cloud subscription on a repo; ownership is owner_project from projects[]",
  subscription_ext_id: "same — see owner_project / owner_path",
};

/** Ledger fields that pass through under their own name. */
const PASSTHROUGH = [
  "severity", "first_seen", "last_seen", "status", "resolved_at", "resolution_src",
  "reopened_count", "first_scan_id", "last_scan_id", "tags_json",
];

/** SCAN fields with no counterpart. Exactly one, and it is ledgerCore's own divergence. */
const UNMAPPED_SCAN: Record<string, string> = {
  shape: "no grouped shape here; ScanRow has no `shape` column and every scan is flat",
};

const PASSTHROUGH_SCAN = [
  "scan_id", "ts", "mode", "total", "new_count", "resolved_count", "reopened_count",
  "severities", "sealed",
];

/** The one column this register ADDS to the scan row. gas/ had one register. */
const ADDED_SCAN = ["scope"];

/**
 * EPISODE fields. `compaction_id` is not in either fixture — gas/'s own test strips it before
 * comparing, because it is storage-specific — so it is listed here as ADDED rather than as a
 * passthrough, alongside the two columns this register's EpisodeRow adds.
 */
const RENAMED_EPISODE: Record<string, string> = {
  vuln_key: "finding_key",
  cve: "identifier",
};

const PASSTHROUGH_EPISODE = [
  "severity", "first_seen", "resolved_at", "resolution_src", "reopened_count",
  "superseded_by_scan",
];

/** Result-shape fields, which carry no renames at all: CompactionResult / DeleteResult. */
const PASSTHROUGH_RESULT = [
  "no_op", "dry_run", "scans_sealed", "episodes_created", "observations_pruned",
  "archive_bytes_freed", "db_bytes_freed", "floor_scan_id", "floor_ts",
];
const PASSTHROUGH_DELETE_RESULT = ["deleted", "scans", "tracked"];
const PASSTHROUGH_CHECKPOINT = ["version", "floor_scan_id", "floor_ts", "ledger"];

/** gas/'s `id:A` key becomes this register's scope-prefixed `sca:id:A` (lifecycle.findingKey). */
const renameKey = (k: string): string => `sca:${k}`;

function shimRow(row: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = { scope: "sca" };
  for (const [k, v] of Object.entries(row)) {
    if (k in UNMAPPED) continue;
    out[RENAMED[k] ?? k] = k === "vuln_key" ? renameKey(String(v)) : v;
  }
  return out;
}

function shimLedger(ledger: Record<string, any>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, row] of Object.entries(ledger)) out[renameKey(k)] = shimRow(row);
  return out;
}

function shimScans(scans: Record<string, unknown>[]): Record<string, unknown>[] {
  return scans.map((r) => {
    const out: Record<string, unknown> = { scope: "sca" };
    for (const [k, v] of Object.entries(r)) {
      if (k in UNMAPPED_SCAN) continue;
      out[k] = v;
    }
    return out;
  });
}

function shimObservations(obs: any[]): unknown[] {
  return obs.map((o) => ({
    scan_id: o.scan_id,
    finding_key: renameKey(o.vuln_key),
    present: o.present,
    severity: o.severity,
    status: o.status,
  }));
}

function shimEpisodes(eps: any[]): unknown[] {
  return eps.map((e) => {
    const out: Record<string, unknown> = { scope: "sca" };
    for (const [k, v] of Object.entries(e)) {
      out[RENAMED_EPISODE[k] ?? k] = k === "vuln_key" ? renameKey(String(v)) : v;
    }
    return out;
  });
}

function obsTable(observationsByScan: Record<string, Observation[]>): Observation[] {
  const all = Object.values(observationsByScan).flat();
  return [...all].sort(
    (a, b) => cmp(a.scan_id, b.scan_id) || cmp(a.finding_key, b.finding_key),
  );
}

/**
 * The archive envelope a PayloadReader hands back. Deliberately NOT gas/'s
 * `vulnerabilityFindings` key — that connection does not exist in this register, and
 * `recordsFromPayload` drops gas/'s special case for it in favour of the generic "first key
 * under `data` carrying `nodes`" walk. Naming a real code connection here is what exercises
 * that.
 */
function envelope(records: unknown[]) {
  return { data: { libraryVulnerabilities: { nodes: records } } };
}

/** Episodes as they compare: without the storage-specific compaction_id. */
function episodesWithoutId(episodes: Record<string, unknown>[]): Record<string, unknown>[] {
  return episodes.map(({ compaction_id, ...rest }) => rest);
}

// --------------------------------------------------------------------------- #
//  Fixture field accounting — every field renamed, passed through, or listed unmapped
// --------------------------------------------------------------------------- #

describe("fixture field accounting — nothing is silently dropped", () => {
  const flow = fixture("ledger_flow");
  const comp = fixture("ledger_compaction");

  function fieldsOf(rows: Iterable<Record<string, unknown>>): Set<string> {
    const out = new Set<string>();
    for (const r of rows) for (const k of Object.keys(r)) out.add(k);
    return out;
  }

  it("ledger_flow's delete steps carry only fields this file accounts for", () => {
    // `delete_result` is the DeleteResult shape; `after_delete_scan2` is a table step whose
    // ledger/scan/observation fields are D3's 18/10/5.
    expect(Object.keys(flow.steps.delete_result).sort()).toEqual(
      [...PASSTHROUGH_DELETE_RESULT].sort(),
    );
    const step = flow.steps.after_delete_scan2;
    expect(Object.keys(step).sort()).toEqual(
      ["episodes", "ledger", "observations", "scans"],
    );
    const ledgerFields = fieldsOf(Object.values(step.ledger));
    const accounted = new Set([
      ...Object.keys(RENAMED), ...Object.keys(UNMAPPED), ...PASSTHROUGH,
    ]);
    expect([...ledgerFields].filter((f) => !accounted.has(f)).sort()).toEqual([]);
    expect(ledgerFields.size).toBe(18); // 5 renamed + 3 unmapped + 10 passed through

    const scanFields = fieldsOf(step.scans);
    const scanAccounted = new Set([...Object.keys(UNMAPPED_SCAN), ...PASSTHROUGH_SCAN]);
    expect([...scanFields].filter((f) => !scanAccounted.has(f)).sort()).toEqual([]);
    expect(scanFields.size).toBe(10);
    expect(ADDED_SCAN.every((c) => !scanFields.has(c))).toBe(true);

    expect([...fieldsOf(step.observations)].sort()).toEqual(
      ["present", "scan_id", "severity", "status", "vuln_key"],
    );
    expect(step.episodes).toEqual([]);
  });

  it("ledger_compaction's top level is `now`, `retention_days`, `scans`, `expected`", () => {
    expect(Object.keys(comp).sort()).toEqual(["expected", "now", "retention_days", "scans"]);
    expect(Object.keys(comp.expected).sort()).toEqual([
      "after_compact", "after_delete_s3", "checkpoint", "delete_s3_result", "dry_run",
      "real", "sealed_delete_error",
    ]);
    expect(comp.retention_days).toBe(30);
  });

  it("every RESULT field the fixture carries is a CompactionResult / DeleteResult field", () => {
    // dry_run carries all nine; the real run's golden omits the two byte counters, which is
    // why the parity assertion below filters them off the actual side too.
    expect(Object.keys(comp.expected.dry_run).sort()).toEqual([...PASSTHROUGH_RESULT].sort());
    const real = new Set(Object.keys(comp.expected.real));
    expect([...real].filter((f) => !PASSTHROUGH_RESULT.includes(f)).sort()).toEqual([]);
    expect([...PASSTHROUGH_RESULT].filter((f) => !real.has(f)).sort()).toEqual([
      "archive_bytes_freed", "db_bytes_freed",
    ]);
    expect(Object.keys(comp.expected.delete_s3_result).sort()).toEqual(
      [...PASSTHROUGH_DELETE_RESULT].sort(),
    );
    expect(typeof comp.expected.sealed_delete_error).toBe("string");
  });

  it("every LEDGER / SCAN / OBSERVATION / EPISODE / CHECKPOINT field is accounted for", () => {
    const steps = [comp.expected.after_compact, comp.expected.after_delete_s3];
    const ledgerAccounted = new Set([
      ...Object.keys(RENAMED), ...Object.keys(UNMAPPED), ...PASSTHROUGH,
    ]);
    const scanAccounted = new Set([...Object.keys(UNMAPPED_SCAN), ...PASSTHROUGH_SCAN]);
    const episodeAccounted = new Set([
      ...Object.keys(RENAMED_EPISODE), ...PASSTHROUGH_EPISODE,
    ]);

    for (const step of steps) {
      const lf = fieldsOf(Object.values(step.ledger));
      expect([...lf].filter((f) => !ledgerAccounted.has(f)).sort()).toEqual([]);
      expect(lf.size).toBe(18);

      const sf = fieldsOf(step.scans);
      expect([...sf].filter((f) => !scanAccounted.has(f)).sort()).toEqual([]);
      expect(sf.size).toBe(10);
      expect(ADDED_SCAN.every((c) => !sf.has(c))).toBe(true);

      expect([...fieldsOf(step.observations)].sort()).toEqual(
        ["present", "scan_id", "severity", "status", "vuln_key"],
      );

      const ef = fieldsOf(step.episodes);
      expect([...ef].filter((f) => !episodeAccounted.has(f)).sort()).toEqual([]);
      expect(ef.size).toBe(8); // 2 renamed + 6 passed through
      // The fixture cannot carry these three: gas/'s test strips compaction_id, and gas/ has
      // no `scope` and no `component` on an episode.
      for (const added of ["compaction_id", "scope", "component"]) {
        expect(ef.has(added)).toBe(false);
      }
    }

    expect(Object.keys(comp.expected.checkpoint).sort()).toEqual(
      [...PASSTHROUGH_CHECKPOINT].sort(),
    );
    const cf = fieldsOf(comp.expected.checkpoint.ledger);
    expect([...cf].filter((f) => !ledgerAccounted.has(f)).sort()).toEqual([]);
    expect(cf.size).toBe(18);
  });
});

// --------------------------------------------------------------------------- #
//  ledger_flow.json — persist x4 then delete s2
// --------------------------------------------------------------------------- #

describe("ledger flow delete (SQLite fixture parity, scope sca)", () => {
  const fx = fixture("ledger_flow");
  const ids = ["s1", "s2", "s3", "s4"] as const;

  it("persist x4 then delete s2 reproduces every table state", () => {
    const state = emptyState();
    const obsByScan: Record<string, Observation[]> = {};
    const stepNames = ["after_scan1", "after_scan2", "after_scan3", "after_scan4"];

    ids.forEach((key, i) => {
      const scan = fx.scans[key];
      const { observations } = persistFlatScan(state, scan.records, {
        scope: "sca",
        mode: "live",
        scanId: scan.id,
      });
      obsByScan[scan.id] = observations;
      const expected = fx.steps[stepNames[i]!];
      expectParity(scansAsc(state.scans), shimScans(expected.scans));
      expectParity(state.ledger, shimLedger(expected.ledger));
      expectParity(obsTable(obsByScan), shimObservations(expected.observations));
      expectParity(state.episodes, expected.episodes);
    });

    // Delete s2 -> replay survivors; identical to a ledger that never saw s2.
    const readPayload = (row: ScanRow) => {
      const key = ids.find((k) => fx.scans[k].id === row.scan_id)!;
      return envelope(fx.scans[key].records);
    };
    const del = deleteScansCore(state, [fx.scans.s2.id], readPayload, null);
    expectParity(del.result, fx.steps.delete_result);
    const expected = fx.steps.after_delete_scan2;
    expectParity(scansAsc(del.state.scans), shimScans(expected.scans));
    expectParity(del.state.ledger, shimLedger(expected.ledger));
    expectParity(obsTable(del.observationsByScan), shimObservations(expected.observations));
    expectParity(del.state.episodes, expected.episodes);

    // The input state is not mutated — the caller decides whether to apply the rebuild.
    expect(state.scans.length).toBe(4);
    expect(Object.keys(state.ledger).sort()).toEqual(
      ["sca:id:A", "sca:id:B", "sca:id:C", "sca:id:D", "sca:id:E"],
    );
  });

  it("every replayed scan row keeps its scope", () => {
    const state = emptyState();
    for (const key of ids) {
      persistFlatScan(state, fx.scans[key].records, {
        scope: "sca", mode: "live", scanId: fx.scans[key].id,
      });
    }
    const readPayload = (row: ScanRow) =>
      envelope(fx.scans[ids.find((k) => fx.scans[k].id === row.scan_id)!].records);
    const del = deleteScansCore(state, [fx.scans.s2.id], readPayload, null);
    expect(del.state.scans.map((r) => r.scope)).toEqual(["sca", "sca", "sca"]);
    for (const row of Object.values(del.state.ledger)) {
      expect(row.scope).toBe("sca");
      expect(row.finding_key.startsWith("sca:")).toBe(true);
    }
  });

  it("deleting an unknown scan id is a no-op that returns the state unchanged", () => {
    const state = emptyState();
    persistFlatScan(state, fx.scans.s1.records, {
      scope: "sca", mode: "live", scanId: fx.scans.s1.id,
    });
    const never = () => {
      throw new Error("readPayload must not be called for a no-op delete");
    };
    for (const ids2 of [[], ["no-such-scan"]]) {
      const del = deleteScansCore(state, ids2, never, null);
      expect(del.result).toEqual({ deleted: 0, scans: 0, tracked: 0 });
      expect(del.state).toBe(state);
      expect(del.observationsByScan).toEqual({});
    }
  });

  it("a survivor with an unreadable archive refuses BEFORE any state change", () => {
    const state = emptyState();
    for (const key of ids) {
      persistFlatScan(state, fx.scans[key].records, {
        scope: "sca", mode: "live", scanId: fx.scans[key].id,
      });
    }
    const before = JSON.stringify(state);
    const readPayload = (row: ScanRow) =>
      row.scan_id === fx.scans.s3.id
        ? null
        : envelope(fx.scans[ids.find((k) => fx.scans[k].id === row.scan_id)!].records);
    expect(() => deleteScansCore(state, [fx.scans.s2.id], readPayload, null)).toThrow(
      LedgerRebuildError,
    );
    expect(() => deleteScansCore(state, [fx.scans.s2.id], readPayload, null)).toThrow(
      new RegExp(fx.scans.s3.id),
    );
    expect(JSON.stringify(state)).toBe(before);
  });
});

// --------------------------------------------------------------------------- #
//  ledger_compaction.json — the compaction flow
// --------------------------------------------------------------------------- #

describe("compaction flow (SQLite fixture parity, scope sca)", () => {
  const fx = fixture("ledger_compaction");
  const ids = ["s1", "s2", "s3", "s4"] as const;
  const now = Date.parse(fx.now);

  function build(): { state: LedgerState; obsByScan: Record<string, Observation[]> } {
    const state = emptyState();
    const obsByScan: Record<string, Observation[]> = {};
    for (const key of ids) {
      const scan = fx.scans[key];
      const { observations } = persistFlatScan(state, scan.records, {
        scope: "sca",
        mode: "live",
        scanId: scan.id,
      });
      obsByScan[scan.id] = observations;
    }
    return { state, obsByScan };
  }

  const readPayload = (row: ScanRow) => {
    const key = ids.find((k) => fx.scans[k].id === row.scan_id);
    return key ? envelope(fx.scans[key].records) : null;
  };

  const counts = (obsByScan: Record<string, Observation[]>) =>
    Object.fromEntries(Object.entries(obsByScan).map(([id, obs]) => [id, obs.length]));

  it("dry run computes the exact preview", () => {
    const { state, obsByScan } = build();
    const plan = compactLedgerCore(state, fx.retention_days, null, readPayload, {
      dryRun: true,
      now,
      compactionId: "cmp-test",
      obsCountByScan: counts(obsByScan),
      archiveBytes: fx.expected.dry_run.archive_bytes_freed,
    });
    expectParity(plan.result, fx.expected.dry_run);
    expect(plan.state).toBeNull();
    expect(plan.compactionId).toBeNull();
    expect(plan.checkpoint!.version).toBe(CHECKPOINT_VERSION);
  });

  it("real run seals, converts episodes, and keeps the checkpoint faithful", () => {
    const { state, obsByScan } = build();
    const plan = compactLedgerCore(state, fx.retention_days, null, readPayload, {
      now,
      compactionId: "cmp-test",
      obsCountByScan: counts(obsByScan),
    });
    expectParity(
      Object.fromEntries(
        Object.entries(plan.result).filter(
          ([k]) => !["archive_bytes_freed", "db_bytes_freed"].includes(k),
        ),
      ),
      fx.expected.real,
    );

    const applied = plan.state!;
    const expected = fx.expected.after_compact;
    expectParity(scansAsc(applied.scans), shimScans(expected.scans));
    expectParity(applied.ledger, shimLedger(expected.ledger));
    expectParity(
      episodesWithoutId(applied.episodes as unknown as Record<string, unknown>[]),
      shimEpisodes(expected.episodes),
    );
    // Every sealed episode carries its scope out of the compaction (rule 6).
    for (const e of applied.episodes) {
      expect(e.scope).toBe("sca");
      expect(e.compaction_id).toBe("cmp-test");
      expect(e.finding_key.startsWith("sca:")).toBe(true);
    }

    // Checkpoint parity (keyed by finding_key; row order is storage-specific).
    expect(plan.checkpoint!.floor_scan_id).toBe(fx.expected.checkpoint.floor_scan_id);
    expect(plan.checkpoint!.floor_ts).toBe(fx.expected.checkpoint.floor_ts);
    expect(plan.checkpoint!.version).toBe(fx.expected.checkpoint.version);
    const cpByKey = Object.fromEntries(plan.checkpoint!.ledger.map((r) => [r.finding_key, r]));
    const expByKey = shimLedger(
      Object.fromEntries(fx.expected.checkpoint.ledger.map((r: any) => [r.vuln_key, r])),
    );
    expectParity(cpByKey, expByKey);
    for (const row of plan.checkpoint!.ledger) expect(row.scope).toBe("sca");

    // The scans the checkpoint seals keep their scope too.
    for (const r of plan.newly) expect(r.scope).toBe("sca");

    // Sealed scans refuse deletion, and the refusal names the scan id.
    expect(() =>
      deleteScansCore(applied, [fx.scans.s1.id], readPayload, plan.checkpoint),
    ).toThrow(SealedScanError);
    try {
      deleteScansCore(applied, [fx.scans.s1.id], readPayload, plan.checkpoint);
      expect.unreachable("expected SealedScanError");
    } catch (err) {
      expect((err as Error).message).toBe(fx.expected.sealed_delete_error);
      expect((err as Error).message).toContain(fx.scans.s1.id);
    }

    // Deleting a post-floor scan replays from the checkpoint.
    const del = deleteScansCore(applied, [fx.scans.s3.id], readPayload, plan.checkpoint, now);
    expectParity(del.result, fx.expected.delete_s3_result);
    const afterDel = fx.expected.after_delete_s3;
    expectParity(scansAsc(del.state.scans), shimScans(afterDel.scans));
    expectParity(del.state.ledger, shimLedger(afterDel.ledger));
    expectParity(
      episodesWithoutId(del.state.episodes as unknown as Record<string, unknown>[]),
      shimEpisodes(afterDel.episodes),
    );
    expectParity(obsTable(del.observationsByScan), shimObservations(afterDel.observations));
  });

  it("baseRows surfaces episodes with the (compacted) placeholder", () => {
    const { state, obsByScan } = build();
    const plan = compactLedgerCore(state, fx.retention_days, null, readPayload, {
      now,
      compactionId: "cmp-test",
      obsCountByScan: counts(obsByScan),
    });
    const rows = baseRows(plan.state!, { now });
    const compacted = rows.filter((r) => r.repo_name === "(compacted)");
    expect(compacted.map((r) => r.finding_key).sort()).toEqual(["sca:id:B", "sca:id:D"]);
    for (const r of compacted) {
      expect(r.status).toBe("RESOLVED");
      expect(r.mttr_days).not.toBeNull();
    }
  });

  it("a second compaction over the same state is a no-op (the cutoff is inside the seal)", () => {
    const { state, obsByScan } = build();
    const first = compactLedgerCore(state, fx.retention_days, null, readPayload, {
      now, compactionId: "cmp-1", obsCountByScan: counts(obsByScan),
    });
    const second = compactLedgerCore(first.state!, fx.retention_days, first.checkpoint, readPayload, {
      now, compactionId: "cmp-2", obsCountByScan: counts(obsByScan),
    });
    expect(second.result.no_op).toBe(true);
    expect(second.state).toBeNull();
    expect(second.checkpoint).toBeNull();
  });

  it("a newly-sealed scan with an unreadable archive refuses before any state change", () => {
    const { state, obsByScan } = build();
    const before = JSON.stringify(state);
    const blind = (row: ScanRow) => (row.scan_id === fx.scans.s1.id ? null : readPayload(row));
    expect(() =>
      compactLedgerCore(state, fx.retention_days, null, blind, {
        now, compactionId: "cmp-test", obsCountByScan: counts(obsByScan),
      }),
    ).toThrow(LedgerRebuildError);
    expect(JSON.stringify(state)).toBe(before);
  });

  it("a null retention window never compacts", () => {
    const { state } = build();
    const plan = compactLedgerCore(state, null, null, readPayload, {
      now, compactionId: "cmp-test",
    });
    expect(plan.result.no_op).toBe(true);
    expect(plan.result.scans_sealed).toBe(0);
  });
});

// --------------------------------------------------------------------------- #
//  Three scopes, one ledger — the behaviour gas/ has no golden for
// --------------------------------------------------------------------------- #

const SECRET_RECORDS = [
  {
    secretDataId: "sd-1",
    path: "config/.env",
    lineNumber: 3,
    type: "PASSWORD",
    confidence: "HIGH",
    severity: "MEDIUM",
    status: "OPEN",
    firstSeenAt: "2026-01-10T00:00:00Z",
    lastSeenAt: "2026-02-02T00:00:00Z",
    resource: { id: "repo-1", name: "github.com/acme/app", type: "REPOSITORY" },
  },
  {
    secretDataId: "sd-2",
    path: "deploy/keys.yaml",
    lineNumber: 11,
    type: "CLOUD_KEY",
    confidence: "MEDIUM",
    severity: "LOW",
    status: "OPEN",
    firstSeenAt: "2026-01-20T00:00:00Z",
    lastSeenAt: "2026-02-02T00:00:00Z",
    resource: { id: "repo-1", name: "github.com/acme/app", type: "REPOSITORY" },
  },
];

describe("delete replay across scopes — one ledger, three registers", () => {
  const fx = fixture("ledger_flow");
  const SCA_1 = "2026-02-01T00:00:00Z";
  const SECRETS = "2026-02-02T00:00:00Z";
  const SCA_2 = "2026-02-03T00:00:00Z";

  const payloads: Record<string, Rec[]> = {
    [SCA_1]: fx.scans.s1.records,
    [SECRETS]: SECRET_RECORDS,
    [SCA_2]: fx.scans.s3.records,
  };
  const readPayload = (row: ScanRow) => envelope(payloads[row.scan_id]!);

  function build(): LedgerState {
    const state = emptyState();
    persistFlatScan(state, payloads[SCA_1]!, { scope: "sca", mode: "live", scanId: SCA_1 });
    persistFlatScan(state, payloads[SECRETS]!, {
      scope: "secrets", mode: "live", scanId: SECRETS,
    });
    persistFlatScan(state, payloads[SCA_2]!, { scope: "sca", mode: "live", scanId: SCA_2 });
    return state;
  }

  it("deleting a sca scan leaves every secrets row byte-identical", () => {
    const state = build();
    const secretKeys = Object.keys(state.ledger).filter((k) => k.startsWith("secrets:"));
    expect(secretKeys.length).toBe(2);
    const before = Object.fromEntries(
      secretKeys.map((k) => [k, JSON.parse(JSON.stringify(state.ledger[k]))]),
    );

    const del = deleteScansCore(state, [SCA_1], readPayload, null);
    expect(del.result.deleted).toBe(1);
    expect(del.result.scans).toBe(2);

    // The secrets register is untouched: same keys, byte-identical rows, and each row's
    // last_scan_id still names the SECRETS scan rather than the sca scan replayed after it.
    expect(Object.keys(del.state.ledger).filter((k) => k.startsWith("secrets:")).sort()).toEqual(
      secretKeys.sort(),
    );
    for (const k of secretKeys) {
      expect(del.state.ledger[k]).toEqual(before[k]);
      expect(del.state.ledger[k]!.last_scan_id).toBe(SECRETS);
      expect(del.state.ledger[k]!.status).toBe("OPEN");
      expect(del.state.ledger[k]!.scope).toBe("secrets");
    }
    // And the sca half really was re-derived: s1's first_scan_id is gone from the ledger.
    for (const row of Object.values(del.state.ledger)) {
      if (row.scope === "sca") expect(row.first_scan_id).toBe(SCA_2);
    }
  });

  it("the replayed scan log keeps each scan under its own scope", () => {
    const del = deleteScansCore(build(), [SCA_1], readPayload, null);
    expect(scansAsc(del.state.scans).map((r) => [r.scan_id, r.scope])).toEqual([
      [SECRETS, "secrets"],
      [SCA_2, "sca"],
    ]);
    // Replaying the secrets scan as `sca` would key its nodes on a missing `id` and throw
    // (lifecycle.findingKey); replaying the sca scan as `secrets` would key on a missing
    // secretDataId. Both refusals are what makes the scope stamp above load-bearing rather
    // than cosmetic.
    expect(() =>
      persistFlatScan(emptyState(), SECRET_RECORDS, {
        scope: "sca", mode: "live", scanId: SECRETS,
      }),
    ).toThrow(/no id/);
  });
});

describe("the compaction floor is global, not per scope", () => {
  const fx = fixture("ledger_compaction");
  const now = Date.parse(fx.now);
  const SCA_1 = "2026-01-01T06:00:00Z";
  const SECRETS = "2026-01-08T06:00:00Z";
  const SCA_2 = "2026-06-01T06:00:00Z";
  const SCA_3 = "2026-06-15T06:00:00Z";

  const payloads: Record<string, Rec[]> = {
    [SCA_1]: fx.scans.s1.records,
    [SECRETS]: SECRET_RECORDS,
    [SCA_2]: fx.scans.s3.records,
    [SCA_3]: fx.scans.s4.records,
  };
  const readPayload = (row: ScanRow) => envelope(payloads[row.scan_id]!);

  function build(): LedgerState {
    const state = emptyState();
    persistFlatScan(state, payloads[SCA_1]!, { scope: "sca", mode: "live", scanId: SCA_1 });
    persistFlatScan(state, payloads[SECRETS]!, {
      scope: "secrets", mode: "live", scanId: SECRETS,
    });
    persistFlatScan(state, payloads[SCA_2]!, { scope: "sca", mode: "live", scanId: SCA_2 });
    persistFlatScan(state, payloads[SCA_3]!, { scope: "sca", mode: "live", scanId: SCA_3 });
    return state;
  }

  /**
   * An unsealed secrets scan sits BETWEEN two old sca scans, and the floor lands on it.
   *
   * The arithmetic: now = 2026-07-01, retention 30 d, so the cutoff is 2026-06-01T00:00:00Z.
   * MIN_UNSEALED_FLAT_SCANS (2) protects the last two scans of the WHOLE log — SCA_2 and
   * SCA_3 — so the candidate prefix is [SCA_1, SECRETS] and the floor is the SECRETS scan.
   *
   * Per scope it would be a different answer, and a wrong one: sca's own log is
   * [SCA_1, SCA_2, SCA_3], whose last two are protected, so a sca-only run would seal SCA_1
   * alone and floor there — leaving the SECRETS scan UNSEALED inside a sealed prefix of the
   * shared log, where deleteScansCore is free to delete it even though the checkpoint has
   * already baked its effects in.
   */
  it("seals across scopes and floors on the secrets scan sitting between two sca scans", () => {
    const state = build();
    const plan = compactLedgerCore(state, fx.retention_days, null, readPayload, {
      now, compactionId: "cmp-mixed",
    });
    expect(plan.result.no_op).toBe(false);
    expect(plan.result.scans_sealed).toBe(2);
    expect(plan.result.floor_scan_id).toBe(SECRETS);
    expect(plan.result.floor_ts).toBe(SECRETS);
    expect(plan.newly.map((r) => [r.scan_id, r.scope])).toEqual([
      [SCA_1, "sca"],
      [SECRETS, "secrets"],
    ]);

    const sealed = scansAsc(plan.state!.scans).filter((r) => r.sealed === 1);
    expect(sealed.map((r) => r.scan_id)).toEqual([SCA_1, SECRETS]);
    // The sealed prefix is contiguous in the shared log — nothing unsealed sits inside it.
    const order = scansAsc(plan.state!.scans).map((r) => r.sealed);
    expect(order).toEqual([1, 1, 0, 0]);

    // The checkpoint carries both scopes, and every row is scope-stamped.
    const scopes = new Set(plan.checkpoint!.ledger.map((r) => r.scope));
    expect([...scopes].sort()).toEqual(["sca", "secrets"]);

    // The per-scope answer, computed the same way, is measurably different — which is the
    // whole reason the global one is written down.
    const scaOnly = selectSealCandidates(
      scansAsc(state.scans, "sca"),
      now - fx.retention_days * 86_400_000,
    );
    expect(scaOnly.map((r) => r.scan_id)).toEqual([SCA_1]);
    expect(MIN_UNSEALED_FLAT_SCANS).toBe(2);
  });

  it("a sealed secrets scan cannot be deleted, and the refusal names it", () => {
    const plan = compactLedgerCore(build(), fx.retention_days, null, readPayload, {
      now, compactionId: "cmp-mixed",
    });
    expect(() => deleteScansCore(plan.state!, [SECRETS], readPayload, plan.checkpoint)).toThrow(
      SealedScanError,
    );
    try {
      deleteScansCore(plan.state!, [SECRETS], readPayload, plan.checkpoint);
      expect.unreachable("expected SealedScanError");
    } catch (err) {
      expect((err as Error).message).toContain(SECRETS);
      expect((err as Error).message).toContain("compacted baseline");
    }
    // Two sealed targets are named together, sorted.
    try {
      deleteScansCore(plan.state!, [SECRETS, SCA_1], readPayload, plan.checkpoint);
      expect.unreachable("expected SealedScanError");
    } catch (err) {
      expect((err as Error).message).toContain(`${SCA_1}, ${SECRETS}`);
    }
  });
});

// --------------------------------------------------------------------------- #
//  Column contracts and the small pure helpers
// --------------------------------------------------------------------------- #

function ledgerRowFixture(over: Partial<LedgerRow> = {}): LedgerRow {
  return {
    finding_key: "sca:id:X", scope: "sca", identifier: "CVE-X", component: "braces",
    severity: "HIGH", repo_id: "repo-1", repo_name: "acme/app", branch: "main",
    platform: "GITHUB", first_seen: "2026-01-01T00:00:00Z",
    last_seen: "2026-02-01T00:00:00Z", status: "RESOLVED",
    resolved_at: "2026-02-01T00:00:00Z", resolution_src: "api", reopened_count: 2,
    first_scan_id: "s1", last_scan_id: "s2", fix_date: "2026-01-15T00:00:00Z",
    fix_observed_at: "2026-01-16T00:00:00Z", fixed_version: "1.2.3", has_kev: true,
    has_exploit: false, epss: 0.42, risk_observed_at: "2026-01-16T00:00:00Z",
    cwe: "CWE-79", ai_verdict: "EXPLOITABLE", language: "js", file_path: null,
    start_line: null, origin: null, secret_kind: null, rotated_at: null, removed_at: null,
    validation_state: null, validated_at: null, confidence: null,
    owner_project: "payments", owner_path: "acme/payments", tags_json: null,
    ...over,
  };
}

describe("toEpisodeRow — the resolved_episodes column contract", () => {
  it("produces exactly TAB_HEADERS[TABS.episodes], no more and no less", () => {
    const row = toEpisodeRow(ledgerRowFixture(), "cmp-1");
    expect(Object.keys(row).sort()).toEqual([...TAB_HEADERS[TABS.episodes]!].sort());
  });

  it("carries scope, the classifier columns and the owner through the seal", () => {
    const row = toEpisodeRow(ledgerRowFixture(), "cmp-1");
    expect(row.scope).toBe("sca");
    expect(row.finding_key).toBe("sca:id:X");
    expect(row.identifier).toBe("CVE-X");
    expect(row.component).toBe("braces");
    expect(row.reopened_count).toBe(2);
    expect(row.compaction_id).toBe("cmp-1");
    expect(row.superseded_by_scan).toBeNull();
    expect(row.has_kev).toBe(true);
    expect(row.has_exploit).toBe(false);
    expect(row.epss).toBe(0.42);
    expect(row.cwe).toBe("CWE-79");
    expect(row.language).toBe("js");
    expect(row.owner_project).toBe("payments");
    expect(row.fix_date).toBe("2026-01-15T00:00:00Z");
    expect(row.fix_observed_at).toBe("2026-01-16T00:00:00Z");
  });

  it("keeps the tri-state: an unmeasured signal seals as null, never false", () => {
    const row = toEpisodeRow(
      ledgerRowFixture({ has_kev: null, has_exploit: null, epss: null }),
      "cmp-1",
    );
    expect(row.has_kev).toBeNull();
    expect(row.has_exploit).toBeNull();
    expect(row.epss).toBeNull();
  });

  it("a secrets lifecycle seals under its own scope", () => {
    const row = toEpisodeRow(
      ledgerRowFixture({ finding_key: "secrets:h:abc", scope: "secrets", identifier: "sd-1" }),
      "cmp-1",
    );
    expect(row.scope).toBe("secrets");
    expect(row.finding_key).toBe("secrets:h:abc");
  });
});

describe("compactionRow — the compactions tab column contract", () => {
  const plan = {
    result: {
      no_op: false, dry_run: false, scans_sealed: 2, episodes_created: 3,
      observations_pruned: 5, archive_bytes_freed: 615, db_bytes_freed: 0,
      floor_scan_id: "s2", floor_ts: "2026-01-08T06:00:00Z",
    },
    checkpoint: null,
    newly: [],
    state: null,
    compactionId: "cmp-1",
  };

  it("produces exactly TAB_HEADERS[TABS.compactions]", () => {
    const row = compactionRow(plan, "drive-cp-1", Date.parse("2026-07-01T00:00:00Z"));
    expect(Object.keys(row).sort()).toEqual([...TAB_HEADERS[TABS.compactions]!].sort());
    expect(row.compaction_id).toBe("cmp-1");
    expect(row.checkpoint_ref).toBe("drive-cp-1");
    expect(row.scans_sealed).toBe(2);
    expect(row.episodes_created).toBe(3);
    expect(row.archive_bytes_freed).toBe(615);
    expect(row.ts).toBe("2026-07-01T00:00:00Z");
  });

  /**
   * THE DIVERGENCE, PINNED. gas/'s compactions tab has ten columns; this one has eight. The
   * two counters live on CompactionResult (a caller can surface them) and have nowhere to be
   * written, and sheetsDb maps by header NAME — so emitting them would produce keys silently
   * dropped on the way to the sheet, which reads as data captured when it is data lost.
   */
  it("omits the two counters the tab has no columns for", () => {
    const row = compactionRow(plan, null);
    expect("observations_pruned" in row).toBe(false);
    expect("db_bytes_freed" in row).toBe(false);
    expect(TAB_HEADERS[TABS.compactions]).not.toContain("observations_pruned");
    expect(TAB_HEADERS[TABS.compactions]).not.toContain("db_bytes_freed");
  });
});

describe("settledEpisodeRows", () => {
  const cpRow = ledgerRowFixture({ status: "RESOLVED", last_scan_id: "s2" });

  it("takes a checkpoint-RESOLVED row whose live state is untouched post-floor", () => {
    const live = { ...cpRow };
    const out = settledEpisodeRows([cpRow], { [cpRow.finding_key]: live }, new Set(["s2"]));
    expect(out).toEqual([live]);
  });

  it("skips a row the live ledger reopened, re-dated, or re-saw after the floor", () => {
    const key = cpRow.finding_key;
    const sealed = new Set(["s2"]);
    expect(settledEpisodeRows([cpRow], {}, sealed)).toEqual([]);
    expect(
      settledEpisodeRows([cpRow], { [key]: { ...cpRow, status: "OPEN" } }, sealed),
    ).toEqual([]);
    expect(
      settledEpisodeRows(
        [cpRow], { [key]: { ...cpRow, resolved_at: "2026-03-01T00:00:00Z" } }, sealed,
      ),
    ).toEqual([]);
    expect(
      settledEpisodeRows([cpRow], { [key]: { ...cpRow, last_scan_id: "s3" } }, sealed),
    ).toEqual([]);
    // A checkpoint row that was never resolved is not an episode at all.
    expect(
      settledEpisodeRows(
        [{ ...cpRow, status: "OPEN" }], { [key]: { ...cpRow } }, sealed,
      ),
    ).toEqual([]);
  });
});

describe("loadReplayPayloads", () => {
  const scan = (over: Partial<ScanRow>): ScanRow => ({
    scan_id: "s1", ts: "2026-01-01T00:00:00Z", scope: "sca", mode: "live",
    severities: null, total: 0, new_count: 0, resolved_count: 0, reopened_count: 0,
    raw_ref: null, obs_ref: null, sealed: 0, ...over,
  });

  it("skips sealed rows and never reads their archives", () => {
    const read = (r: ScanRow) => {
      if (r.sealed) throw new Error("sealed archives must not be read");
      return envelope([]);
    };
    const out = loadReplayPayloads(
      [scan({ scan_id: "a", sealed: 1 }), scan({ scan_id: "b" })],
      read,
      (id) => id,
    );
    expect(out.map((i) => i.row.scan_id)).toEqual(["b"]);
  });

  /**
   * DIVERGENCE (gas/), pinned. gas/ guarded this throw with `shape === "flat"`, because a
   * grouped scan never touched the ledger. There is no grouped shape here, so EVERY unsealed
   * scan is load-bearing and a missing archive is fatal for any of them.
   */
  it("throws LedgerRebuildError naming the scan when an unsealed archive is missing", () => {
    expect(() =>
      loadReplayPayloads([scan({ scan_id: "b" })], () => null, (id) => `gone: ${id}`),
    ).toThrow(new LedgerRebuildError("gone: b"));
  });
});

describe("recordsFromPayload", () => {
  const recs = [{ id: "A" }, { id: "B" }];

  it("unwraps every envelope shape the archive can hold", () => {
    expect(recordsFromPayload({ data: { libraryVulnerabilities: { nodes: recs } } })).toEqual(recs);
    expect(recordsFromPayload({ data: { sastFindings: { nodes: recs } } })).toEqual(recs);
    expect(recordsFromPayload({ data: { secretInstances: { nodes: recs } } })).toEqual(recs);
    expect(recordsFromPayload({ nodes: recs })).toEqual(recs);
    expect(recordsFromPayload(recs)).toEqual(recs);
    expect(recordsFromPayload(JSON.stringify({ nodes: recs }))).toEqual(recs);
  });

  it("merges a list of page envelopes", () => {
    expect(
      recordsFromPayload([
        { data: { secretInstances: { nodes: [recs[0]] } } },
        { data: { secretInstances: { nodes: [recs[1]] } } },
      ]),
    ).toEqual(recs);
  });

  it("an absent or empty payload is an empty record list, never a throw", () => {
    expect(recordsFromPayload(null)).toEqual([]);
    expect(recordsFromPayload(undefined)).toEqual([]);
    expect(recordsFromPayload([])).toEqual([]);
    expect(recordsFromPayload({ nodes: null })).toEqual([]);
  });
});

describe("cutoffMs / isAfter — the retention boundary", () => {
  const now = Date.parse("2026-07-01T00:00:00Z");

  it("cutoffMs subtracts the window and never less than RETENTION_MIN_DAYS", () => {
    expect(RETENTION_MIN_DAYS).toBe(30);
    expect(cutoffMs(now, 180)).toBe(now - 180 * 86_400_000);
    expect(cutoffMs(now, 30)).toBe(now - 30 * 86_400_000);
    // Below the floor, and at zero / negative, the floor wins.
    expect(cutoffMs(now, 1)).toBe(now - 30 * 86_400_000);
    expect(cutoffMs(now, 0)).toBe(now - 30 * 86_400_000);
    expect(cutoffMs(now, -5)).toBe(now - 30 * 86_400_000);
  });

  it("isAfter is strict, and an unparseable or absent ts is never after", () => {
    const cutoff = cutoffMs(now, 30); // 2026-06-01T00:00:00Z
    expect(isAfter("2026-06-01T00:00:01Z", cutoff)).toBe(true);
    expect(isAfter("2026-06-01T00:00:00Z", cutoff)).toBe(false); // the boundary itself
    expect(isAfter("2026-05-31T23:59:59Z", cutoff)).toBe(false);
    expect(isAfter(null, cutoff)).toBe(false);
    expect(isAfter("not-a-date", cutoff)).toBe(false);
  });
});

describe("deleteScansCore seeded from a checkpoint", () => {
  it("seeds the rebuilt ledger from the checkpoint, minus keys already sealed as episodes", () => {
    const sealedKey = "sca:id:SEALED";
    const liveKey = "sca:id:LIVE";
    const checkpoint: Checkpoint = {
      version: CHECKPOINT_VERSION,
      floor_scan_id: "s1",
      floor_ts: "2026-01-01T00:00:00Z",
      ledger: [
        ledgerRowFixture({ finding_key: sealedKey }),
        ledgerRowFixture({ finding_key: liveKey, status: "OPEN", resolved_at: null }),
      ],
    };
    const state: LedgerState = {
      scans: [
        {
          scan_id: "s1", ts: "2026-01-01T00:00:00Z", scope: "sca", mode: "live",
          severities: null, total: 1, new_count: 1, resolved_count: 0, reopened_count: 0,
          raw_ref: null, obs_ref: null, sealed: 1,
        },
        {
          scan_id: "s2", ts: "2026-02-01T00:00:00Z", scope: "sca", mode: "live",
          severities: null, total: 0, new_count: 0, resolved_count: 0, reopened_count: 0,
          raw_ref: null, obs_ref: null, sealed: 0,
        },
      ],
      ledger: {},
      episodes: [toEpisodeRow(ledgerRowFixture({ finding_key: sealedKey }), "cmp-1")],
    };
    // Deleting the only unsealed scan leaves nothing to replay; the checkpoint is the state.
    const del = deleteScansCore(state, ["s2"], () => envelope([]), checkpoint);
    expect(Object.keys(del.state.ledger)).toEqual([liveKey]);
    expect(del.state.scans.map((r) => r.scan_id)).toEqual(["s1"]);
    expect(del.state.episodes.map((e) => e.finding_key)).toEqual([sealedKey]);
    // Supersessions reset — a post-floor survivor re-derives them during replay.
    expect(del.state.episodes.every((e) => e.superseded_by_scan === null)).toBe(true);
    expect(del.result).toEqual({ deleted: 1, scans: 1, tracked: 2 });
  });
});
