// Port of gas/test/reconcile.test.ts, reshaped for the three-scope code register.
//
// Two populations of test live here and it matters which is which:
//
//   FIXTURE PARITY — test/fixtures/reconcile.json and tags_json.json are BYTE COPIES from
//   gas/, generated by the Python domain layer and pinned a second time by
//   brick/tests/test_ledger.py::test_matches_the_gas_reconcile_fixture. They are never
//   edited or regenerated here. reconcile.json is fed through a RENAME SHIM (below) that
//   maps gas/'s column names onto sheetsDb.ts's, and nothing else: the records, the ledger,
//   the options and every expected value go in verbatim.
//
//   HAND-WRITTEN — the behaviour this register adds and gas/ has no golden for: SAST's
//   birth date, the secrets twin fold, the validation axis, removed-vs-rotated, and the
//   per-scope column projections. Every number in these is either read off the fixture or
//   derived with the arithmetic written out in the test.

import { describe, expect, it } from "vitest";
import { findingKey } from "../src/domain/lifecycle";
import {
  emptyRiskSignals,
  foldSecretTwins,
  ownerPath,
  ownerProject,
  projectsJson,
  projectsListJson,
  reconcile,
  tagsJson,
} from "../src/domain/reconcile";
import type { LedgerRow } from "../src/domain/ledgerTypes";
import { expectParity, fixture } from "./helpers";

// --------------------------------------------------------------------------- #
//  tags_json parity
// --------------------------------------------------------------------------- #

describe("tagsJson (fixture parity)", () => {
  const { cases } = fixture("tags_json");
  cases.forEach((c: any, i: number) => {
    it(`case ${i}`, () => {
      expectParity(tagsJson(c.input), c.expected);
    });
  });
});

// --------------------------------------------------------------------------- #
//  reconcile.json parity, through the rename shim
// --------------------------------------------------------------------------- #

/**
 * gas/ column -> gas_devsecops column. The rename is the ONLY transformation the shim makes.
 * Source of truth for the right-hand side is TAB_HEADERS[TABS.ledger] in
 * src/server/sheetsDb.ts, mirrored as LEDGER_COLUMNS in src/domain/ledgerTypes.ts.
 */
const RENAMED: Record<string, string> = {
  vuln_key: "finding_key",
  cve: "identifier",
  asset_id: "repo_id",
  asset_name: "repo_name",
  cloud: "platform",
};

/**
 * THE FIXTURE FIELDS WITH NO COUNTERPART, listed rather than silently dropped.
 *
 * All three describe a CLOUD asset, and this register's asset is a repository. They are not
 * renames that were forgotten; there is no column on the devsecops ledger that means the
 * same thing, and inventing one would put a null in front of an analyst under a heading that
 * promises a value.
 */
const UNMAPPED: Record<string, string> = {
  // The devsecops asset is always a repository, so a per-row asset TYPE carries no
  // information — except REPOSITORY vs REPOSITORY_BRANCH, which is exactly what the `branch`
  // column encodes (see splitRepoBranch). Dropped, not renamed.
  asset_type: "the asset is always a repository; REPOSITORY vs REPOSITORY_BRANCH is `branch`",
  // wizQueries.ts: "subscriptionName is always null on a repository branch". The ownership
  // dimension in this register is the project hierarchy — owner_project / owner_path, from
  // projects[] — which Q_SCA/Q_SAST/Q_SECRETS all select and gas/'s query does not.
  subscription_name: "no cloud subscription on a repo; ownership is owner_project from projects[]",
  subscription_ext_id: "same — see owner_project / owner_path",
};

/** Everything else passes through under its own name. */
const PASSTHROUGH = [
  "severity", "first_seen", "last_seen", "status", "resolved_at", "resolution_src",
  "reopened_count", "first_scan_id", "last_scan_id", "tags_json",
];

describe("reconcile.json rename shim — the mapping itself", () => {
  const { scenarios } = fixture("reconcile");
  const seenFields = new Set<string>();
  for (const sc of scenarios) {
    for (const row of Object.values<any>(sc.expected.ledger)) {
      for (const k of Object.keys(row)) seenFields.add(k);
    }
    for (const row of Object.values<any>(sc.input.ledger)) {
      for (const k of Object.keys(row)) seenFields.add(k);
    }
  }

  it("every field the fixture carries is either renamed, passed through, or listed as unmapped", () => {
    const accounted = new Set([
      ...Object.keys(RENAMED),
      ...Object.keys(UNMAPPED),
      ...PASSTHROUGH,
    ]);
    const unaccounted = [...seenFields].filter((f) => !accounted.has(f)).sort();
    expect(unaccounted, "fixture fields with no shim entry").toEqual([]);
    // 18 fields: 5 renamed + 3 unmapped + 10 passed through.
    expect(seenFields.size).toBe(18);
    expect(Object.keys(RENAMED).length + Object.keys(UNMAPPED).length + PASSTHROUGH.length)
      .toBe(18);
  });
});

/**
 * gas/'s vulnKey falls back to a content hash ("h:<16 hex>") when a node carries no `id`.
 * findingKey deliberately does NOT port that fallback — src/domain/lifecycle.ts states the
 * reason: sca and sast nodes always carry a Wiz-assigned id, since Q_SCA and Q_SAST both
 * select it. The fixture's `first_scan` has exactly ONE id-less record.
 *
 * D9b task 3 (see test/lifecycle.test.ts's "refuses a node with no id" suite): findingKey now
 * THROWS on a missing/blank id rather than keying it as the EMPTY identity "sca:id:" — the
 * old behaviour here, which this file used to shim onto with `HASH_FALLBACK_KEY = "sca:id:"`.
 * That was a FINDING about the fixture, not a safe fallback to keep: a second id-less node in
 * the same scan would have collided into the same "sca:id:" ledger row, silently merging two
 * distinct findings. So rather than route this one record through findingKey's now-removed
 * empty-identity path, the shim gives it a SYNTHETIC id — deterministic, derived from the
 * fixture's own "h:<hash>" fallback key (gas/'s vulnKey content hash for this record, computed
 * from its OTHER fields and therefore stable regardless of what id it carries) — before
 * reconcile ever sees it, and maps the fixture's "h:<hash>" key onto that same synthetic
 * "sca:id:fixture-<hash>" identity everywhere the shim rewrites a key.
 */
const { scenarios } = fixture("reconcile");
const idLessRecords = scenarios
  .flatMap((sc: any) => sc.input.records)
  .filter((r: any) => !String(r.id ?? "").trim());

const FIXTURE_HASH_KEYS = new Set<string>();
for (const sc of scenarios) {
  for (const k of Object.keys(sc.expected.ledger)) if (k.startsWith("h:")) FIXTURE_HASH_KEYS.add(k);
  for (const k of Object.keys(sc.input.ledger)) if (k.startsWith("h:")) FIXTURE_HASH_KEYS.add(k);
}
const [ONLY_HASH_KEY] = [...FIXTURE_HASH_KEYS];
// "fixture-<hash>" per the D9b brief's own example (id: "fixture-b9db6107009435fc") — derived
// from the fixture's one observed "h:" key rather than hardcoded, so this still fails loudly
// (a mismatched idLessRecords.length below) if a future fixture regeneration changes the shape.
const SYNTHETIC_ID = "fixture-" + String(ONLY_HASH_KEY ?? "").slice("h:".length);
// Mutates the shared fixture record in place, once, at module load — before any scenario's
// reconcile() call can reach it. findingKey("sca", record) would otherwise throw on this
// record's blank id (see the block comment above).
if (idLessRecords.length === 1) (idLessRecords[0] as Record<string, unknown>).id = SYNTHETIC_ID;
const HASH_FALLBACK_KEY = findingKey("sca", { id: SYNTHETIC_ID });

const renameKey = (k: string): string => (k.startsWith("h:") ? HASH_FALLBACK_KEY : `sca:${k}`);

function shimRow(row: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = { scope: "sca" };
  for (const [k, v] of Object.entries(row)) {
    if (k in UNMAPPED) continue;
    out[RENAMED[k] ?? k] = k === "vuln_key" ? renameKey(String(v)) : v;
  }
  return out;
}

function shimLedger(ledger: Record<string, any>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, row] of Object.entries(ledger)) out[renameKey(k)] = shimRow(row);
  return out;
}

function shimObservations(obs: any[]): unknown[] {
  return obs.map((o) => ({
    scan_id: o.scan_id,
    finding_key: renameKey(o.vuln_key),
    present: o.present,
    severity: o.severity,
    status: o.status,
  }));
}

describe("reconcile (reconcile.json parity, scope sca)", () => {
  // FALSIFIED CLAIM, from before D9b task 3: "the hash-fallback collapse is unambiguous" —
  // that asserted `HASH_FALLBACK_KEY === "sca:id:"`, i.e. that it was SAFE for findingKey to
  // key an id-less node as the empty identity, because the fixture happens to carry only one
  // such record. It is not safe in general (a second id-less node in the same scan would have
  // collided into that same row), which is exactly why findingKey now throws instead. This
  // fixture's one id-less record no longer reaches that path at all: the shim above gives it a
  // synthetic id before reconcile ever sees it, so what this test can honestly pin is that the
  // synthetic id is exactly what it claims to be — derived from the fixture's own "h:" key.
  it("the fixture's one id-less record is given a synthetic id derived from its own fixture hash", () => {
    expect(idLessRecords.length).toBe(1);
    expect((idLessRecords[0] as Record<string, unknown>).id).toBe(SYNTHETIC_ID);
    expect(SYNTHETIC_ID).toBe("fixture-b9db6107009435fc");
    expect(HASH_FALLBACK_KEY).toBe("sca:id:fixture-b9db6107009435fc");
    expect([...FIXTURE_HASH_KEYS]).toEqual(["h:b9db6107009435fc"]);
  });

  for (const sc of scenarios) {
    it(sc.name, () => {
      const o = sc.input.options ?? {};
      const { ledger, observations, deltas } = reconcile(
        sc.input.records,
        shimLedger(sc.input.ledger) as unknown as Record<string, LedgerRow>,
        sc.input.scan_id,
        sc.input.scan_ts,
        sc.input.prev_scan_id,
        {
          scope: "sca",
          ...(o.disappearance_mode ? { disappearanceMode: o.disappearance_mode } : {}),
          ...(o.prev_scan_ts ? { prevScanTs: o.prev_scan_ts } : {}),
          ...(o.scanned_severities ? { scannedSeverities: o.scanned_severities } : {}),
          ...(o.prev_scan_id_by_severity
            ? { prevScanIdBySeverity: o.prev_scan_id_by_severity }
            : {}),
        },
      );
      expectParity(deltas, sc.expected.deltas);
      expectParity(ledger, shimLedger(sc.expected.ledger));
      expectParity(observations, shimObservations(sc.expected.observations));
    });
  }

  it("does not mutate its inputs", () => {
    const sc = scenarios[1];
    const shimmed = shimLedger(sc.input.ledger) as unknown as Record<string, LedgerRow>;
    const ledgerCopy = JSON.stringify(shimmed);
    const recordsCopy = JSON.stringify(sc.input.records);
    reconcile(sc.input.records, shimmed, sc.input.scan_id, sc.input.scan_ts, sc.input.prev_scan_id, {
      scope: "sca",
    });
    expectParity(JSON.parse(ledgerCopy), shimmed);
    expectParity(JSON.parse(recordsCopy), sc.input.records);
  });

  it("twinStats is zeroed on a non-secrets scope — there are no twins to fold", () => {
    const sc = scenarios[0];
    const { twinStats } = reconcile(sc.input.records, {}, sc.input.scan_id, sc.input.scan_ts, null, {
      scope: "sca",
    });
    expect(twinStats).toEqual({ keys: 0, folded: 0, medianGapDays: null });
  });
});

// --------------------------------------------------------------------------- #
//  Hand-written: shared builders
// --------------------------------------------------------------------------- #

const S1 = "2026-03-10T00:00:00Z";
const S2 = "2026-03-17T00:00:00Z";

const scaNode = (over: Record<string, unknown> = {}) => ({
  id: "sca-1",
  name: "CVE-2026-1",
  detailedName: "braces",
  severity: "HIGH",
  status: "OPEN",
  firstDetectedAt: "2026-03-01T00:00:00Z",
  vulnerableAsset: {
    id: "repo-1",
    type: "REPOSITORY_BRANCH",
    name: "dktunited/retbox-front/main",
    cloudPlatform: "GitHub",
  },
  artifactType: { codeLibraryLanguage: "JAVASCRIPT" },
  ...over,
});

const sastNode = (over: Record<string, unknown> = {}) => ({
  id: "sast-1",
  name: "Unsafe XML Processing with XMLInputFactory in Java",
  status: "OPEN",
  severity: "HIGH",
  originalSeverity: null,
  filePath: "tattoo/src/com/decathlon/Bo.java",
  startLine: 133,
  codeLibraryLanguage: ["JAVA"],
  origin: "WIZ",
  createdAt: "2026-03-01T00:00:00Z",
  resource: { id: "res-1", name: "dktunited/tattoo/stab", type: "REPOSITORY_BRANCH" },
  weaknesses: [{ id: "CWE-611", name: "CWE-611: Improper Restriction of XXE" }],
  aiAnalysis: { verdict: "NON_EXPLOITABLE" },
  ...over,
});

const secretNode = (over: Record<string, unknown> = {}) => ({
  id: "sec-1",
  externalId: "github.com##dktunited/kconnect##/resources/prod.txt##abc##4",
  secretDataId: "0dd42a12-52f3-50e1-9b3f-c3053ca9d45d",
  name: "Aiven Service Password",
  type: "SAAS_API_KEY",
  confidence: "High",
  severity: "HIGH",
  path: "/resources/prod.txt",
  lineNumber: 6,
  status: "OPEN",
  resolvedAt: null,
  validationStatus: "UNKNOWN",
  lastValidatedAt: null,
  firstSeenAt: "2026-03-01T00:00:00Z",
  lastSeenAt: S1,
  resource: {
    id: "res-1",
    name: "dktunited/kconnect",
    type: "REPOSITORY",
    cloudPlatform: "GitHub",
  },
  ...over,
});

const run = (
  scope: "sca" | "sast" | "secrets",
  records: Record<string, unknown>[],
  ledger: Record<string, LedgerRow>,
  scanId: string,
  prevScanId: string | null = null,
  extra: Record<string, unknown> = {},
) => reconcile(records, ledger, scanId, scanId, prevScanId, { scope, ...extra } as any);

// --------------------------------------------------------------------------- #
//  Rule 1 / rule 2: scope, keys and the per-scope column projection
// --------------------------------------------------------------------------- #

describe("scope is part of the key and is stamped on the row", () => {
  it("keys come from findingKey(scope, node), so the same id in two scopes is two findings", () => {
    const sca = run("sca", [scaNode({ id: "shared" })], {}, S1);
    const sast = run("sast", [sastNode({ id: "shared" })], {}, S1);
    expect(Object.keys(sca.ledger)).toEqual(["sca:id:shared"]);
    expect(Object.keys(sast.ledger)).toEqual(["sast:id:shared"]);
    expect(sca.ledger["sca:id:shared"].scope).toBe("sca");
    expect(sast.ledger["sast:id:shared"].scope).toBe("sast");
  });

  it("a stored row that predates the scope column is re-stamped rather than left blank", () => {
    const stored = {
      "sca:id:sca-1": {
        finding_key: "sca:id:sca-1", severity: "HIGH", status: "OPEN",
        first_seen: "2026-03-01T00:00:00Z", last_seen: S1, last_scan_id: "s0",
        reopened_count: 0,
      },
    } as unknown as Record<string, LedgerRow>;
    const { ledger } = run("sca", [scaNode()], stored, S2);
    expect(ledger["sca:id:sca-1"].scope).toBe("sca");
  });
});

describe("per-scope column projection (rule 2)", () => {
  it("sca: identifier <- name, component <- detailedName, repo/branch/platform, language", () => {
    const row = run("sca", [scaNode()], {}, S1).ledger["sca:id:sca-1"];
    expect(row.identifier).toBe("CVE-2026-1");
    expect(row.component).toBe("braces");
    expect(row.repo_id).toBe("repo-1");
    expect(row.repo_name).toBe("dktunited/retbox-front");
    expect(row.branch).toBe("main");
    expect(row.platform).toBe("GitHub");
    expect(row.language).toBe("JAVASCRIPT");
    // The SAST/secrets columns stay null on an SCA row.
    expect(row.cwe).toBeNull();
    expect(row.file_path).toBeNull();
    expect(row.secret_kind).toBeNull();
    expect(row.validation_state).toBeNull();
  });

  it("sast: identifier <- name, cwe <- weaknesses[].id, file_path/start_line, ai_verdict, origin", () => {
    const row = run("sast", [sastNode()], {}, S1).ledger["sast:id:sast-1"];
    expect(row.identifier).toBe("Unsafe XML Processing with XMLInputFactory in Java");
    expect(row.cwe).toBe("CWE-611");
    expect(row.ai_verdict).toBe("NON_EXPLOITABLE");
    expect(row.language).toBe("JAVA");
    expect(row.file_path).toBe("tattoo/src/com/decathlon/Bo.java");
    expect(row.start_line).toBe(133);
    expect(row.origin).toBe("WIZ");
    expect(row.repo_name).toBe("dktunited/tattoo");
    expect(row.branch).toBe("stab");
    // Q_SAST's `resource { id name type }` selects no cloudPlatform — an honest gap.
    expect(row.platform).toBeNull();
  });

  it("cwe joins several weaknesses with ',' in a stable (sorted) order", () => {
    const row = run(
      "sast",
      [sastNode({ weaknesses: [{ id: "CWE-89" }, { id: "CWE-20" }, { id: "CWE-611" }] })],
      {},
      S1,
    ).ledger["sast:id:sast-1"];
    expect(row.cwe).toBe("CWE-20,CWE-611,CWE-89");
  });

  it("no weaknesses leaves cwe NULL, not '' — an absent weakness is unclassified, not low risk", () => {
    expect(run("sast", [sastNode({ weaknesses: [] })], {}, S1).ledger["sast:id:sast-1"].cwe)
      .toBeNull();
    expect(run("sast", [sastNode({ weaknesses: null })], {}, S1).ledger["sast:id:sast-1"].cwe)
      .toBeNull();
  });

  it("sast severity falls back to originalSeverity when Wiz reports none", () => {
    const row = run(
      "sast",
      [sastNode({ severity: null, originalSeverity: "CRITICAL" })],
      {},
      S1,
    ).ledger["sast:id:sast-1"];
    expect(row.severity).toBe("CRITICAL");
  });

  it("secrets: identifier <- secretDataId, secret_kind <- type, file_path <- path, start_line <- lineNumber", () => {
    const node = secretNode();
    const key = findingKey("secrets", node);
    const row = run("secrets", [node], {}, S1).ledger[key];
    expect(row.identifier).toBe("0dd42a12-52f3-50e1-9b3f-c3053ca9d45d");
    expect(row.secret_kind).toBe("SAAS_API_KEY");
    expect(row.confidence).toBe("High");
    expect(row.file_path).toBe("/resources/prod.txt");
    expect(row.start_line).toBe(6);
    expect(row.repo_name).toBe("dktunited/kconnect");
    expect(row.branch).toBeNull(); // resource.type REPOSITORY carries no branch
    expect(row.platform).toBe("GitHub");
    expect(row.validation_state).toBe("UNKNOWN");
  });

  it("component is NULL for sast and secrets — the located artefact lives in file_path", () => {
    expect(run("sast", [sastNode()], {}, S1).ledger["sast:id:sast-1"].component).toBeNull();
    const node = secretNode();
    expect(run("secrets", [node], {}, S1).ledger[findingKey("secrets", node)].component).toBeNull();
  });
});

describe("ownership from projects[] (all three scopes)", () => {
  // The live probe sample's shape: folders and leaves interleaved, no parent links.
  const projects = [
    { id: "p1", name: "VALUE-CHAIN", isFolder: true, slug: "value-chain" },
    { id: "p2", name: "product-TATTOO-idp", isFolder: false, slug: "product-tattoo-idp" },
    { id: "p3", name: "CE-TRANSPORT", isFolder: true, slug: "ce-transport" },
    { id: "p4", name: "GITHUB-DKTUNITED", isFolder: false, slug: "github-dktunited" },
  ];

  it("owner_project is the first leaf; owner_path is the folders, sorted", () => {
    expect(ownerProject({ projects })).toBe("product-TATTOO-idp");
    expect(ownerPath({ projects })).toBe("CE-TRANSPORT / VALUE-CHAIN");
  });

  it("tags_json renders projects[] as canonical sorted-key JSON keyed on slug", () => {
    expect(projectsJson({ projects })).toBe(
      '{"ce-transport": "CE-TRANSPORT", "github-dktunited": "GITHUB-DKTUNITED", ' +
        '"product-tattoo-idp": "product-TATTOO-idp", "value-chain": "VALUE-CHAIN"}',
    );
  });

  it("a node with no projects leaves all three null", () => {
    const row = run("sast", [sastNode()], {}, S1).ledger["sast:id:sast-1"];
    expect(row.owner_project).toBeNull();
    expect(row.owner_path).toBeNull();
    expect(row.tags_json).toBeNull();
  });

  it("the ledger row carries them", () => {
    const row = run("sast", [sastNode({ projects })], {}, S1).ledger["sast:id:sast-1"];
    expect(row.owner_project).toBe("product-TATTOO-idp");
    expect(row.owner_path).toBe("CE-TRANSPORT / VALUE-CHAIN");
    expect(row.tags_json).toContain('"value-chain": "VALUE-CHAIN"');
  });
});

// --------------------------------------------------------------------------- #
//  projectsListJson (P1: the flat projects[] list, uncollapsed) — additive alongside
//  projectsJson, which stays byte-identical (test/reconcile.test.ts:441-ish above).
// --------------------------------------------------------------------------- #

describe("projectsListJson — the flat projects[] list, additive alongside projectsJson", () => {
  const projects = [
    { id: "p1", name: "VALUE-CHAIN", isFolder: true, slug: "value-chain" },
    { id: "p2", name: "product-TATTOO-idp", isFolder: false, slug: "product-tattoo-idp" },
    { id: "p3", name: "CE-TRANSPORT", isFolder: true, slug: "ce-transport" },
    { id: "p4", name: "GITHUB-DKTUNITED", isFolder: false, slug: "github-dktunited" },
  ];

  it("renders [{slug, name, isFolder}], sorted by slug, through the SAME canonical writer", () => {
    expect(projectsListJson({ projects })).toBe(
      '[{"isFolder": true, "name": "CE-TRANSPORT", "slug": "ce-transport"}, ' +
        '{"isFolder": false, "name": "GITHUB-DKTUNITED", "slug": "github-dktunited"}, ' +
        '{"isFolder": false, "name": "product-TATTOO-idp", "slug": "product-tattoo-idp"}, ' +
        '{"isFolder": true, "name": "VALUE-CHAIN", "slug": "value-chain"}]',
    );
  });

  it("projectsJson's own output is UNCHANGED on the same input — side by side", () => {
    const record = { projects };
    // projectsJson still collapses to {slug: name}; projectsListJson is the new, additive,
    // uncollapsed sibling. Asserted together so a future edit to one cannot silently start
    // moving the other's pinned bytes (test/reconcile.test.ts's original assertion at line
    // ~441 already pins projectsJson alone; this is the side-by-side the package asked for).
    expect(projectsJson(record)).toBe(
      '{"ce-transport": "CE-TRANSPORT", "github-dktunited": "GITHUB-DKTUNITED", ' +
        '"product-tattoo-idp": "product-TATTOO-idp", "value-chain": "VALUE-CHAIN"}',
    );
    expect(projectsListJson(record)).not.toBe(projectsJson(record));
  });

  it("isFolder is TRI-STATE: omitted entirely when the API did not report it, never false", () => {
    const noFlag = [{ slug: "no-flag", name: "No Flag" }];
    const rendered = projectsListJson({ projects: noFlag });
    expect(rendered).toBe('[{"name": "No Flag", "slug": "no-flag"}]');
    expect(rendered).not.toContain("isFolder");
    // And round-trips through JSON.parse as a key genuinely absent, not `false`.
    const parsed = JSON.parse(rendered!);
    expect("isFolder" in parsed[0]).toBe(false);
  });

  it("keys on slug, falling back to id, matching projectsJson's rule", () => {
    const noSlug = [{ id: "p-only-id", name: "Only Id", isFolder: false }];
    expect(projectsListJson({ projects: noSlug })).toBe(
      '[{"isFolder": false, "name": "Only Id", "slug": "p-only-id"}]',
    );
  });

  it("a record with no projects at all returns null, same convention as projectsJson", () => {
    expect(projectsListJson({})).toBeNull();
    expect(projectsListJson({ projects: [] })).toBeNull();
  });

  it("the ledger row carries it, additively — tags_json/owner_project are untouched", () => {
    const row = run("sast", [sastNode({ projects })], {}, S1).ledger["sast:id:sast-1"];
    expect(row.projects_json).toContain('"slug": "value-chain"');
    expect(row.projects_json).toContain('"isFolder": true');
    expect(row.owner_project).toBe("product-TATTOO-idp");
    expect(row.tags_json).toContain('"value-chain": "VALUE-CHAIN"');
  });

  it("a node with no projects leaves projects_json null too", () => {
    const row = run("sast", [sastNode()], {}, S1).ledger["sast:id:sast-1"];
    expect(row.projects_json).toBeNull();
  });

  it("latest-wins-never-erased: a later scan with no projects[] does not blank the column", () => {
    const s1 = run("sast", [sastNode({ projects })], {}, S1);
    const s2 = run("sast", [sastNode({ projects: undefined })], s1.ledger, S2);
    expect(s2.ledger["sast:id:sast-1"].projects_json).toBe(s1.ledger["sast:id:sast-1"].projects_json);
  });
});

// --------------------------------------------------------------------------- #
//  Rule 3: the birth date, and SAST's in particular
// --------------------------------------------------------------------------- #

describe("apiFirst = firstDetectedAt ?? firstSeenAt ?? createdAt (rule 3)", () => {
  it("SAST's birth date is createdAt", () => {
    const row = run("sast", [sastNode()], {}, S1).ledger["sast:id:sast-1"];
    expect(row.first_seen).toBe("2026-03-01T00:00:00Z");
  });

  it("secrets' birth date is firstSeenAt", () => {
    const node = secretNode({ firstSeenAt: "2026-02-14T06:00:00Z" });
    const row = run("secrets", [node], {}, S1).ledger[findingKey("secrets", node)];
    expect(row.first_seen).toBe("2026-02-14T06:00:00Z");
  });

  it("firstDetectedAt wins over both when present", () => {
    const row = run(
      "sast",
      [sastNode({ firstDetectedAt: "2026-01-05T00:00:00Z", createdAt: "2026-03-01T00:00:00Z" })],
      {},
      S1,
    ).ledger["sast:id:sast-1"];
    expect(row.first_seen).toBe("2026-01-05T00:00:00Z");
  });

  it("a node with no birth date at all falls back to the scan ts, never to null", () => {
    const row = run("sast", [sastNode({ createdAt: null })], {}, S1).ledger["sast:id:sast-1"];
    expect(row.first_seen).toBe(S1);
  });

  it("SAST resolves by DISAPPEARANCE and gets a real MTTR from its own two dates", () => {
    // Scan 1 sees it (createdAt 2026-03-01); scan 2 does not.
    const s1 = run("sast", [sastNode()], {}, S1);
    expect(s1.ledger["sast:id:sast-1"].status).toBe("OPEN");

    const s2 = run("sast", [], s1.ledger, S2, S1);
    const row = s2.ledger["sast:id:sast-1"];
    expect(row.status).toBe("RESOLVED");
    expect(row.resolution_src).toBe("disappeared");
    expect(row.resolved_at).toBe(S2);
    expect(row.first_seen).toBe("2026-03-01T00:00:00Z");
    // Arithmetic, by hand: 2026-03-17T00:00:00Z - 2026-03-01T00:00:00Z
    //   = 16 whole days (March 1 -> March 17), 16 * 86_400_000 ms.
    const mttrMs = Date.parse(row.resolved_at!) - Date.parse(row.first_seen!);
    expect(mttrMs).toBe(16 * 86_400_000);
    expect(mttrMs).toBeGreaterThan(0);
    expect(s2.deltas.resolved_count).toBe(1);
  });
});

// --------------------------------------------------------------------------- #
//  Rule 5: the secrets twin fold
// --------------------------------------------------------------------------- #

describe("secrets twin fold (rule 5)", () => {
  // ONE credential, ONE file, ONE line — recorded by Wiz twice, against the REPOSITORY
  // resource and against REPOSITORY_BRANCH, with different id, different externalId and
  // different birth dates. PROBE_FINDINGS.md §10.6/§10.7.
  const repositoryTwin = secretNode({
    id: "sec-repo",
    externalId: "github.com##dktunited/kconnect##/resources/prod.txt##abc##4",
    firstSeenAt: "2026-05-20T00:00:00Z",
    lastSeenAt: "2026-06-01T00:00:00Z", // the FRESHER of the two
    validationStatus: "VALID",
    lastValidatedAt: "2026-05-31T00:00:00Z",
    resource: {
      id: "res-repo", name: "dktunited/kconnect", type: "REPOSITORY", cloudPlatform: "GitHub",
    },
  });
  const branchTwin = secretNode({
    id: "sec-branch",
    externalId: "github.com##dktunited/kconnect##main##/resources/prod.txt##abc##4",
    firstSeenAt: "2026-04-30T12:00:00Z", // the EARLIER of the two
    lastSeenAt: "2026-05-25T00:00:00Z",
    validationStatus: "UNKNOWN",
    lastValidatedAt: null,
    resource: {
      id: "res-branch", name: "dktunited/kconnect/main", type: "REPOSITORY_BRANCH",
      cloudPlatform: "GitHub",
    },
  });

  it("the two twins already share a finding_key but differ on id and externalId", () => {
    expect(findingKey("secrets", repositoryTwin)).toBe(findingKey("secrets", branchTwin));
    expect(repositoryTwin.id).not.toBe(branchTwin.id);
    expect(repositoryTwin.externalId).not.toBe(branchTwin.externalId);
  });

  it("folds to ONE row: earliest first_seen, branch from the branch twin, status from the fresher twin", () => {
    const key = findingKey("secrets", repositoryTwin);
    const { ledger, deltas, twinStats } = run(
      "secrets",
      [repositoryTwin, branchTwin],
      {},
      "2026-06-05T00:00:00Z",
    );

    expect(Object.keys(ledger)).toEqual([key]);
    expect(deltas.new_count).toBe(1);

    const row = ledger[key];
    // Earliest firstSeenAt across the twins — the branch twin's here.
    expect(row.first_seen).toBe("2026-04-30T12:00:00Z");
    // resource / branch from the REPOSITORY_BRANCH twin, even though it is the STALER one.
    expect(row.repo_id).toBe("res-branch");
    expect(row.repo_name).toBe("dktunited/kconnect");
    expect(row.branch).toBe("main");
    // validationStatus from the twin with the LATER lastSeenAt — the repository twin here,
    // which is the one carrying the measured VALID.
    expect(row.validation_state).toBe("VALID");
    expect(row.validated_at).toBe("2026-05-31T00:00:00Z");

    // THE ARITHMETIC, by hand:
    //   branch twin firstSeenAt  2026-04-30T12:00:00Z
    //   repo   twin firstSeenAt  2026-05-20T00:00:00Z
    //   Apr 30 12:00 -> May  1 00:00 =  0.5 d
    //   May  1 00:00 -> May 20 00:00 = 19.0 d
    //                             gap = 19.5 d, and the median of one value is that value.
    // (The measured tenant-wide median is 19.9 d — §10.7 — which is why this is the shape of
    // the fixture rather than a round number.)
    expect(twinStats).toEqual({ keys: 1, folded: 1, medianGapDays: 19.5 });
    const gapMs = Date.parse("2026-05-20T00:00:00Z") - Date.parse("2026-04-30T12:00:00Z");
    expect(gapMs / 86_400_000).toBe(19.5);
  });

  it("keying on externalId instead would DOUBLE the ledger — the defect the fold exists to stop", () => {
    // Same two nodes, keyed the way §9.5 recommended and §10.6 falsified.
    const byExternalId = new Set([repositoryTwin.externalId, branchTwin.externalId]);
    expect(byExternalId.size).toBe(2);
    const { ledger } = run("secrets", [repositoryTwin, branchTwin], {}, "2026-06-05T00:00:00Z");
    expect(Object.keys(ledger).length).toBe(1);
  });

  it("a single untwinned node folds to itself and reports no twins", () => {
    const node = secretNode();
    const { ledger, twinStats } = run("secrets", [node], {}, S1);
    expect(Object.keys(ledger)).toEqual([findingKey("secrets", node)]);
    expect(twinStats).toEqual({ keys: 0, folded: 0, medianGapDays: null });
  });

  it("foldSecretTwins counts keys and folded nodes independently", () => {
    // Two twins of one credential (2 nodes -> 1) plus a triple of another (3 nodes -> 1),
    // plus one untwinned node. keys = 2, folded = (2-1) + (3-1) = 3.
    const other = (over: Record<string, unknown>) =>
      secretNode({ secretDataId: "other-credential", path: "/b.txt", lineNumber: 9, ...over });
    const { nodes, stats } = foldSecretTwins([
      repositoryTwin,
      branchTwin,
      other({ id: "o1", firstSeenAt: "2026-01-01T00:00:00Z", lastSeenAt: "2026-02-01T00:00:00Z" }),
      other({ id: "o2", firstSeenAt: "2026-01-11T00:00:00Z", lastSeenAt: "2026-02-02T00:00:00Z" }),
      other({ id: "o3", firstSeenAt: "2026-01-21T00:00:00Z", lastSeenAt: "2026-02-03T00:00:00Z" }),
      secretNode({ id: "lone", secretDataId: "third", path: "/c.txt", lineNumber: 1 }),
    ]);
    expect(nodes.length).toBe(3);
    expect(stats.keys).toBe(2);
    expect(stats.folded).toBe(3);
    // Gaps, by hand: twin pair 19.5 d (above); the triple spans 2026-01-01 -> 2026-01-21 =
    // 20 d. Median of [19.5, 20] = (19.5 + 20) / 2 = 19.75.
    expect(stats.medianGapDays).toBe(19.75);
  });
});

// --------------------------------------------------------------------------- #
//  Rule 6: the update disciplines
// --------------------------------------------------------------------------- #

describe("update disciplines (rule 6)", () => {
  it("latest-wins: severity and identifier follow the newest observation", () => {
    const s1 = run("sca", [scaNode({ severity: "HIGH" })], {}, S1);
    const s2 = run("sca", [scaNode({ severity: "CRITICAL", name: "CVE-2026-9" })], s1.ledger, S2);
    expect(s2.ledger["sca:id:sca-1"].severity).toBe("CRITICAL");
    expect(s2.ledger["sca:id:sca-1"].identifier).toBe("CVE-2026-9");
  });

  it("latest-wins-NEVER-ERASED: a scan that omits an attribute does not wipe it", () => {
    const s1 = run("sca", [scaNode({ fixedVersion: "3.0.3" })], {}, S1);
    expect(s1.ledger["sca:id:sca-1"].repo_name).toBe("dktunited/retbox-front");
    expect(s1.ledger["sca:id:sca-1"].fixed_version).toBe("3.0.3");

    const s2 = run(
      "sca",
      [{ id: "sca-1", name: "CVE-2026-1", severity: "HIGH", status: "OPEN" }],
      s1.ledger,
      S2,
    );
    const row = s2.ledger["sca:id:sca-1"];
    expect(row.repo_name).toBe("dktunited/retbox-front");
    expect(row.repo_id).toBe("repo-1");
    expect(row.branch).toBe("main");
    expect(row.platform).toBe("GitHub");
    expect(row.language).toBe("JAVASCRIPT");
    expect(row.fixed_version).toBe("3.0.3");
  });

  it("sticky first-wins, reset by reopen: the vendor-fix clock", () => {
    const s1 = run("sca", [scaNode({ fixedVersion: null, fixDate: null })], {}, S1);
    expect(s1.ledger["sca:id:sca-1"].fix_observed_at).toBeNull();

    const s2 = run(
      "sca",
      [scaNode({ fixedVersion: "1.2.3", fixDate: "2026-03-15T00:00:00Z" })],
      s1.ledger,
      S2,
    );
    expect(s2.ledger["sca:id:sca-1"].fix_observed_at).toBe(S2);
    expect(s2.ledger["sca:id:sca-1"].fix_date).toBe("2026-03-15T00:00:00Z");

    const s3 = run(
      "sca",
      [scaNode({ fixedVersion: "1.2.4", fixDate: "2026-03-20T00:00:00Z" })],
      s2.ledger,
      "2026-03-25T00:00:00Z",
    );
    expect(s3.ledger["sca:id:sca-1"].fix_observed_at).toBe(S2);
    expect(s3.ledger["sca:id:sca-1"].fix_date).toBe("2026-03-15T00:00:00Z");
  });

  it("tri-state risk signals: a record carrying no signal keys leaves all four NULL", () => {
    const row = run("sca", [scaNode()], {}, S1).ledger["sca:id:sca-1"];
    expect(row.has_kev).toBeNull();
    expect(row.has_exploit).toBeNull();
    expect(row.epss).toBeNull();
    expect(row.risk_observed_at).toBeNull();
  });

  it("tri-state risk signals: an observed false is false — distinct from not-captured null", () => {
    const row = run(
      "sca",
      [scaNode({ hasCisaKevExploit: false, hasExploit: false, epssProbability: 0.02 })],
      {},
      S1,
    ).ledger["sca:id:sca-1"];
    expect(row.has_kev).toBe(false);
    expect(row.has_exploit).toBe(false);
    expect(row.epss).toBe(0.02);
    expect(row.risk_observed_at).toBe(S1);
  });

  it("monotone: false -> true sticks, and true never reverts; epss keeps the peak", () => {
    const s1 = run("sca", [scaNode({ hasExploit: false, epssProbability: 0.4 })], {}, S1);
    expect(s1.ledger["sca:id:sca-1"].has_exploit).toBe(false);

    const s2 = run("sca", [scaNode({ hasExploit: true, epssProbability: 0.82 })], s1.ledger, S2);
    expect(s2.ledger["sca:id:sca-1"].has_exploit).toBe(true);
    expect(s2.ledger["sca:id:sca-1"].epss).toBe(0.82);

    const s3 = run(
      "sca",
      [scaNode({ hasExploit: false, epssProbability: 0.05 })],
      s2.ledger,
      "2026-03-25T00:00:00Z",
    );
    expect(s3.ledger["sca:id:sca-1"].has_exploit).toBe(true);
    expect(s3.ledger["sca:id:sca-1"].epss).toBe(0.82);
    // risk_observed_at pins to the EARLIEST witnessing scan, in either replay order.
    expect(s3.ledger["sca:id:sca-1"].risk_observed_at).toBe(S1);
  });

  it("a reopen resets the fix clock but NOT the risk signals", () => {
    const resolved: Record<string, LedgerRow> = {
      "sca:id:sca-1": {
        finding_key: "sca:id:sca-1", scope: "sca", identifier: "CVE-2026-1", component: "braces",
        severity: "HIGH", repo_id: "repo-1", repo_name: "dktunited/retbox-front",
        branch: "main", platform: "GitHub", first_seen: "2026-03-01T00:00:00Z", last_seen: S1,
        status: "RESOLVED", resolved_at: S1, resolution_src: "api", reopened_count: 0,
        first_scan_id: "s0", last_scan_id: "s0", fix_date: "2026-02-20T00:00:00Z",
        fix_observed_at: S1, fixed_version: "1.2.3",
        has_kev: true, has_exploit: true, epss: 0.7, risk_observed_at: "2026-03-01T00:00:00Z",
        cwe: null, ai_verdict: null, language: "JAVASCRIPT", file_path: null, start_line: null,
        origin: null, secret_kind: null, rotated_at: null, removed_at: null,
        validation_state: null, validated_at: null, confidence: null,
        owner_project: null, owner_path: null, tags_json: null, projects_json: null,
      },
    };
    const { ledger, deltas } = run("sca", [scaNode()], resolved, S2);
    const row = ledger["sca:id:sca-1"];
    expect(deltas.reopened_count).toBe(1);
    expect(row.reopened_count).toBe(1);
    expect(row.status).toBe("OPEN");
    expect(row.fix_date).toBeNull(); // per-episode: cleared
    expect(row.fix_observed_at).toBeNull();
    expect(row.has_kev).toBe(true); // per-vulnerability: kept
    expect(row.has_exploit).toBe(true);
    expect(row.epss).toBe(0.7);
    expect(row.risk_observed_at).toBe("2026-03-01T00:00:00Z");
  });

  it("emptyRiskSignals is all-null, never false or 0", () => {
    expect(emptyRiskSignals()).toEqual({
      has_kev: null, has_exploit: null, epss: null, risk_observed_at: null,
    });
  });
});

// --------------------------------------------------------------------------- #
//  Rule 7: the secrets validation axis
// --------------------------------------------------------------------------- #

describe("validation is latest-wins among MEASURED states only (rule 7)", () => {
  const node = secretNode();
  const key = findingKey("secrets", node);

  it("UNKNOWN does not overwrite VALID — 99.6% of this tenant's instances read UNKNOWN", () => {
    const s1 = run(
      "secrets",
      [secretNode({ validationStatus: "VALID", lastValidatedAt: "2026-03-05T00:00:00Z" })],
      {},
      S1,
    );
    expect(s1.ledger[key].validation_state).toBe("VALID");
    expect(s1.ledger[key].validated_at).toBe("2026-03-05T00:00:00Z");

    const s2 = run(
      "secrets",
      [secretNode({ validationStatus: "UNKNOWN", lastValidatedAt: null })],
      s1.ledger,
      S2,
    );
    expect(s2.ledger[key].validation_state).toBe("VALID");
    expect(s2.ledger[key].validated_at).toBe("2026-03-05T00:00:00Z");
  });

  it("ERROR does not overwrite INVALID either", () => {
    const s1 = run(
      "secrets",
      [secretNode({ validationStatus: "INVALID", lastValidatedAt: "2026-03-05T00:00:00Z" })],
      {},
      S1,
    );
    const s2 = run("secrets", [secretNode({ validationStatus: "ERROR" })], s1.ledger, S2);
    expect(s2.ledger[key].validation_state).toBe("INVALID");
  });

  it("an unmeasured state may still FILL a null column — looked-and-got-UNKNOWN is not never-looked", () => {
    expect(run("secrets", [node], {}, S1).ledger[key].validation_state).toBe("UNKNOWN");
  });

  it("a measured state DOES overwrite a measured one: VALID -> INVALID", () => {
    const s1 = run(
      "secrets",
      [secretNode({ validationStatus: "VALID", lastValidatedAt: "2026-03-05T00:00:00Z" })],
      {},
      S1,
    );
    const s2 = run(
      "secrets",
      [secretNode({ validationStatus: "INVALID", lastValidatedAt: "2026-03-16T00:00:00Z" })],
      s1.ledger,
      S2,
    );
    expect(s2.ledger[key].validation_state).toBe("INVALID");
    expect(s2.ledger[key].validated_at).toBe("2026-03-16T00:00:00Z");
  });

  it("rotated_at is set ONCE, from validated_at, on the first INVALID", () => {
    const s1 = run(
      "secrets",
      [secretNode({ validationStatus: "INVALID", lastValidatedAt: "2026-03-05T00:00:00Z" })],
      {},
      S1,
    );
    expect(s1.ledger[key].rotated_at).toBe("2026-03-05T00:00:00Z");

    // A second INVALID with a LATER validated_at moves validated_at and not rotated_at.
    const s2 = run(
      "secrets",
      [secretNode({ validationStatus: "INVALID", lastValidatedAt: "2026-03-16T00:00:00Z" })],
      s1.ledger,
      S2,
    );
    expect(s2.ledger[key].validated_at).toBe("2026-03-16T00:00:00Z");
    expect(s2.ledger[key].rotated_at).toBe("2026-03-05T00:00:00Z");
  });

  it("an INVALID with no lastValidatedAt dates rotation by OBSERVATION rather than dropping it", () => {
    const s1 = run(
      "secrets",
      [secretNode({ validationStatus: "INVALID", lastValidatedAt: null })],
      {},
      S1,
    );
    expect(s1.ledger[key].validated_at).toBeNull();
    expect(s1.ledger[key].rotated_at).toBe(S1);
  });

  it("an UNKNOWN row is not rotated — absent is never zero", () => {
    expect(run("secrets", [node], {}, S1).ledger[key].rotated_at).toBeNull();
  });

  it("a reopen clears removed_at and rotated_at but KEEPS validation_state", () => {
    const resolved: Record<string, LedgerRow> = {
      [key]: {
        finding_key: key, scope: "secrets",
        identifier: "0dd42a12-52f3-50e1-9b3f-c3053ca9d45d", component: null, severity: "HIGH",
        repo_id: "res-1", repo_name: "dktunited/kconnect", branch: null, platform: "GitHub",
        first_seen: "2026-03-01T00:00:00Z", last_seen: S1, status: "RESOLVED",
        resolved_at: S1, resolution_src: "disappeared", reopened_count: 0,
        first_scan_id: "s0", last_scan_id: "s0",
        fix_date: null, fix_observed_at: null, fixed_version: null,
        has_kev: null, has_exploit: null, epss: null, risk_observed_at: null,
        cwe: null, ai_verdict: null, language: null,
        file_path: "/resources/prod.txt", start_line: 6, origin: null,
        secret_kind: "SAAS_API_KEY",
        rotated_at: "2026-03-05T00:00:00Z", removed_at: S1,
        validation_state: "INVALID", validated_at: "2026-03-05T00:00:00Z",
        confidence: "High", owner_project: null, owner_path: null, tags_json: null,
        projects_json: null,
      },
    };
    // The string is back in HEAD; nobody re-checked the credential (UNKNOWN).
    const { ledger, deltas } = run(
      "secrets",
      [secretNode({ validationStatus: "UNKNOWN", lastValidatedAt: null })],
      resolved,
      S2,
    );
    const row = ledger[key];
    expect(deltas.reopened_count).toBe(1);
    expect(row.status).toBe("OPEN");
    expect(row.removed_at).toBeNull();
    expect(row.rotated_at).toBeNull();
    // The last measurement anyone made of the credential survives the reopen.
    expect(row.validation_state).toBe("INVALID");
    expect(row.validated_at).toBe("2026-03-05T00:00:00Z");
  });
});

// --------------------------------------------------------------------------- #
//  Rule 8: disappearance, and removed-is-not-rotated
// --------------------------------------------------------------------------- #

describe("disappearance (rule 8)", () => {
  it("a secrets row that disappears sets removed_at = resolved_at and leaves rotated_at null", () => {
    const node = secretNode();
    const key = findingKey("secrets", node);
    const s1 = run("secrets", [node], {}, S1);
    const s2 = run("secrets", [], s1.ledger, S2, S1);
    const row = s2.ledger[key];
    expect(row.status).toBe("RESOLVED");
    expect(row.resolution_src).toBe("disappeared");
    expect(row.resolved_at).toBe(S2);
    expect(row.removed_at).toBe(S2);
    // REMOVED IS NOT ROTATED: the string left HEAD; the credential is live until measured dead.
    expect(row.rotated_at).toBeNull();
    expect(row.validation_state).toBe("UNKNOWN");
    expect(s2.observations).toEqual([
      { scan_id: S2, finding_key: key, present: 0, severity: "HIGH", status: "RESOLVED" },
    ]);
  });

  it("an API-declared resolution on secrets is also a removal (PROBE_FINDINGS.md §3)", () => {
    const node = secretNode({ status: "RESOLVED", resolvedAt: "2026-03-09T12:00:00Z" });
    const key = findingKey("secrets", node);
    const row = run("secrets", [node], {}, S1).ledger[key];
    expect(row.resolution_src).toBe("api");
    expect(row.resolved_at).toBe("2026-03-09T12:00:00Z");
    expect(row.removed_at).toBe("2026-03-09T12:00:00Z");
    expect(row.rotated_at).toBeNull();
  });

  it("the midpoint mode dates the resolution halfway between the two scans", () => {
    const s1 = run("sast", [sastNode()], {}, S1);
    const s2 = run("sast", [], s1.ledger, S2, S1, {
      disappearanceMode: "midpoint",
      prevScanTs: S1,
    });
    // 2026-03-10T00:00:00Z .. 2026-03-17T00:00:00Z is 7 days; the midpoint is +3.5 d,
    // i.e. 2026-03-13T12:00:00Z.
    expect(s2.ledger["sast:id:sast-1"].resolved_at).toBe("2026-03-13T12:00:00Z");
  });

  it("a row last seen before the previous scan is not re-resolved", () => {
    const stale = {
      "sast:id:sast-1": {
        finding_key: "sast:id:sast-1", scope: "sast", severity: "HIGH", status: "OPEN",
        first_seen: "2026-03-01T00:00:00Z", last_seen: "2026-03-03T00:00:00Z",
        last_scan_id: "an-older-scan", reopened_count: 0,
      },
    } as unknown as Record<string, LedgerRow>;
    const { ledger, deltas } = run("sast", [], stale, S2, S1);
    expect(ledger["sast:id:sast-1"].status).toBe("OPEN");
    expect(deltas.resolved_count).toBe(0);
  });
});

// --------------------------------------------------------------------------- #
//  Rule 9: the severity-scope guard
// --------------------------------------------------------------------------- #

describe("severity-scope guard (rule 9)", () => {
  it("a MEDIUM row is untouched by a scan whose scannedSeverities is [CRITICAL, HIGH]", () => {
    const medium: LedgerRow = {
      finding_key: "sca:id:med-1", scope: "sca", identifier: "CVE-2026-MED", component: "lodash",
      severity: "MEDIUM", repo_id: "repo-2", repo_name: "dktunited/other", branch: "main",
      platform: "GitHub", first_seen: "2026-02-01T00:00:00Z", last_seen: S1, status: "OPEN",
      resolved_at: null, resolution_src: null, reopened_count: 0,
      first_scan_id: S1, last_scan_id: S1,
      fix_date: null, fix_observed_at: null, fixed_version: null,
      has_kev: null, has_exploit: null, epss: null, risk_observed_at: null,
      cwe: null, ai_verdict: null, language: null, file_path: null, start_line: null,
      origin: null, secret_kind: null, rotated_at: null, removed_at: null,
      validation_state: null, validated_at: null, confidence: null,
      owner_project: null, owner_path: null, tags_json: null, projects_json: null,
    };
    const before = JSON.stringify(medium);

    // A CRITICAL/HIGH-scoped scan that sees a different finding entirely. Without the guard
    // the MEDIUM row would "disappear" and mass-resolve — absence of something nobody looked
    // for is not evidence.
    const { ledger, deltas } = run(
      "sca",
      [scaNode()],
      { "sca:id:med-1": medium },
      S2,
      S1,
      { scannedSeverities: ["CRITICAL", "HIGH"] },
    );
    expect(JSON.stringify(ledger["sca:id:med-1"])).toBe(before);
    expect(deltas.resolved_count).toBe(0);

    // …and the same scan WITHOUT the scope does resolve it, which is what makes the guard
    // the cause rather than a coincidence.
    const unscoped = run("sca", [scaNode()], { "sca:id:med-1": medium }, S2, S1);
    expect(unscoped.ledger["sca:id:med-1"].status).toBe("RESOLVED");
    expect(unscoped.deltas.resolved_count).toBe(1);
  });
});
