// Trend series for the code register (domain/trend.ts).
//
// Three populations of test live here and it matters which is which:
//
//   FIXTURE PARITY — test/fixtures/trend.json is a BYTE COPY from gas/, generated by the
//   Python domain layer (gas/test/export_*.py). It is never edited or regenerated here. It
//   is fed through a RENAME SHIM (below) that maps gas/'s scan-log shape onto this
//   register's, and NOTHING ELSE: every base row, every option and every expected value
//   goes in verbatim.
//
//   PORTED HAND CASES — gas/test/trend.test.ts's own hand-computed blocks, carried across
//   with their arithmetic comments intact. Three adaptations, each stated at the site:
//     * scans carry no `shape` — the column does not exist here (see `pointTimes`), so the
//       "ignores non-flat scans" assertions are replaced by their opposite: a scan is
//       counted whatever stray `shape` it carries.
//     * the group dimension is `repo_name` read through `groupKeyOf("repo")`, not gas/'s
//       host-only `asset` — insights.GROUP_COLUMNS is the only dimension list.
//     * `withCoverageEfficiency`'s block comes from gas/test/program.test.ts (it tests
//        trend.ts through program.ts) and its rows carry `scope: "sca"`, because
//        program.classifyRisk resolves the rule per scope.
//
//   NEW — the scope filter (rule 2 of the D8 brief), the per-scope stack, the secrets
//   refusal, and the backfill/scope interaction. Every number is derived with the
//   arithmetic written out.

import { describe, expect, it } from "vitest";
import { DEFAULT_RISK_RULE, SCOPES, type RiskRule } from "../src/domain/config";
import { GROUP_COLUMNS } from "../src/domain/insights";
import { RISK_TIER_ORDER } from "../src/domain/program";
import {
  awaitingFixAsOf,
  cohortSlaAttainment,
  groupKeyOf,
  kmMedianAsOf,
  kmMedianByGroupTrend,
  kmSkipMask,
  medianMttrByGroupTrend,
  openByGroupTrend,
  openByRiskTierTrend,
  openBySeverityTrend,
  perScopeSeries,
  trendByScope,
  trendFromBase,
  trendFromFrames,
  withCoverageEfficiency,
  withKmMedian,
  withOpenPastSla,
  withSlaBurn,
} from "../src/domain/trend";
import type { Rec } from "../src/domain/util";
import { expectParity, fixture } from "./helpers";

// --------------------------------------------------------------------------- #
//  trend.json rename shim
// --------------------------------------------------------------------------- #

/**
 * gas/ column -> gas_devsecops column, for the columns THIS module reads.
 *
 * It is empty, and that is the finding rather than an oversight: trend.ts reads `severity`,
 * `first_seen`, `resolved_at`, `mttr_days`, `fix_available_at` and `actionable_from`, and not
 * one of them is renamed in this register. The renames ledgerTypes.ts's header lists
 * (vuln_key -> finding_key, cve -> identifier, asset_* -> repo_*, cloud -> platform) all land
 * on columns the trend never touches. The mapping is declared anyway so the accounting test
 * below is a real check and not a tautology.
 */
const RENAMED: Record<string, string> = {};

/** THE FIXTURE FIELDS WITH NO COUNTERPART, listed rather than silently dropped. */
const UNMAPPED: Record<string, string> = {
  // ledgerTypes.ScanRow has no `shape`: gas/'s flat-vs-grouped split describes a fetch that
  // aggregates findings per asset, and every scope's fetch here is a flat per-finding scan.
  // The fixture's one `grouped` scan exists ONLY to exercise the filter this port removes
  // (see trend.pointTimes's DIVERGENCE note), so the shim drops that row rather than
  // inventing a column for it — and the assertion below makes the drop visible.
  shape: "no shape column on this register's scans tab; every scope's fetch is a flat scan",
};

/** Everything else passes through under its own name. */
const PASSTHROUGH = ["scan_id", "ts", "severity", "first_seen", "resolved_at", "mttr_days"];

/** Added by the shim: `scope` is part of every row's identity here and gas/ has no such column. */
const ADDED = ["scope"];

const RAW = fixture("trend");

function shimScans(scans: any[]): Rec[] {
  return scans
    .filter((s) => s.shape === "flat")
    .map(({ shape: _shape, ...rest }) => ({ ...rest, scope: "sca" }));
}

function shimBase(base: any[]): Rec[] {
  return base.map((r) => ({ ...r, scope: "sca" }));
}

const FX_SCANS = shimScans(RAW.scans);
const FX_BASE = shimBase(RAW.base);

describe("trend.json rename shim — the mapping itself", () => {
  const seenFields = new Set<string>();
  for (const s of RAW.scans) for (const k of Object.keys(s)) seenFields.add(k);
  for (const r of RAW.base) for (const k of Object.keys(r)) seenFields.add(k);

  it("every field the fixture carries is either renamed, passed through, or listed as unmapped", () => {
    const accounted = new Set([
      ...Object.keys(RENAMED),
      ...Object.keys(UNMAPPED),
      ...PASSTHROUGH,
    ]);
    const unaccounted = [...seenFields].filter((f) => !accounted.has(f)).sort();
    expect(unaccounted, "fixture fields with no shim entry").toEqual([]);
    // 7 fields: 0 renamed + 1 unmapped + 6 passed through. Nothing this module reads is renamed.
    expect(seenFields.size).toBe(7);
    expect(Object.keys(RENAMED).length + Object.keys(UNMAPPED).length + PASSTHROUGH.length)
      .toBe(7);
  });

  it("the shim drops exactly the one grouped scan, and stamps every row with a scope", () => {
    expect(RAW.scans.length).toBe(4);
    expect(FX_SCANS.length).toBe(3); // s1, s2, s3 — `sg` is the grouped one
    expect(RAW.scans.filter((s: any) => s.shape !== "flat").map((s: any) => s.scan_id))
      .toEqual(["sg"]);
    expect(FX_SCANS.every((s) => s["scope"] === "sca" && !("shape" in s))).toBe(true);
    expect(FX_BASE.every((r) => r["scope"] === "sca")).toBe(true);
    expect(ADDED).toEqual(["scope"]);
  });
});

describe("trendFromFrames (fixture parity)", () => {
  it("matches the unscoped Python trend", () => {
    expectParity(trendFromFrames(FX_SCANS, FX_BASE), RAW.expected.all);
  });
  it("matches the CRITICAL+HIGH scoped trend", () => {
    expectParity(
      trendFromFrames(FX_SCANS, FX_BASE, ["CRITICAL", "HIGH"]),
      RAW.expected.scoped_critical_high,
    );
  });
  it("returns [] for empty inputs", () => {
    expectParity(trendFromFrames([], FX_BASE), []);
    expectParity(trendFromFrames(FX_SCANS, []), []);
  });
  it("the fixture is all-sca, so scope:'sca' is the same series and scope:'sast' is empty", () => {
    expectParity(trendFromFrames(FX_SCANS, FX_BASE, null, { scope: "sca" }), RAW.expected.all);
    expect(trendFromFrames(FX_SCANS, FX_BASE, null, { scope: "sast" })).toEqual([]);
  });
});

// --------------------------------------------------------------------------- #
//  ported hand cases
// --------------------------------------------------------------------------- #

describe("awaitingFixAsOf", () => {
  // Millisecond scalars keep the arithmetic legible: open as of d iff first<=d and not
  // resolved by d; awaiting iff also no fix available by d (fixAvail null or > d).
  it("open with no fix ever -> awaiting", () => {
    expect(awaitingFixAsOf(5, null, null, 10)).toBe(true);
  });
  it("open with a fix available by d -> not awaiting", () => {
    expect(awaitingFixAsOf(5, null, 8, 10)).toBe(false);
  });
  it("open with a fix that only lands after d -> awaiting (re-enters later)", () => {
    expect(awaitingFixAsOf(5, null, 20, 10)).toBe(true);
  });
  it("resolved by d -> not open as of d -> not awaiting", () => {
    expect(awaitingFixAsOf(5, 8, null, 10)).toBe(false);
  });
  it("not yet detected as of d -> not open -> not awaiting", () => {
    expect(awaitingFixAsOf(15, null, null, 10)).toBe(false);
  });
  it("open now, resolves after d, no fix -> still awaiting as of d", () => {
    expect(awaitingFixAsOf(5, 20, null, 10)).toBe(true);
  });
});

describe("no shape gate (DIVERGENCE from gas/)", () => {
  // gas/ samples only at scans with `shape === "flat"`. This register's scans tab has no
  // `shape` column at all, so the branch is gone: EVERY scan in the log is a sample point.
  // The inverted assertion is deliberate — a port that silently kept the filter would read
  // every trend empty (no writer sets the column), which looks exactly like an empty
  // register, and "a zero has to prove it looked".
  const base = [
    { severity: "HIGH", first_seen: "2025-12-31T00:00:00Z", resolved_at: null, mttr_days: null },
  ];

  it("counts a scan carrying a stray non-flat shape value", () => {
    const out = trendFromFrames([{ ts: "2026-01-01T00:00:00Z", shape: "grouped" }], base);
    expect(out.map((p) => p.date)).toEqual(["2026-01-01T00:00:00Z"]);
    expect(out[0].open).toBe(1);
  });

  it("counts a scan with no shape column at all — the real row shape here", () => {
    expect(trendFromFrames([{ ts: "2026-01-01T00:00:00Z" }], base).map((p) => p.open)).toEqual([1]);
  });

  it("the whole group family agrees — none of them gate on shape either", () => {
    const scans = [{ ts: "2026-01-01T00:00:00Z", shape: "grouped" }];
    const groupBase = [{ ...base[0], repo_name: "web" }];
    const keyOf = groupKeyOf("repo");
    expect(openBySeverityTrend(scans, base).length).toBe(1);
    expect(openByGroupTrend(scans, groupBase, keyOf, ["web"]).length).toBe(1);
    expect(medianMttrByGroupTrend(scans, groupBase, keyOf, ["web"]).length).toBe(1);
    expect(kmMedianByGroupTrend(scans, groupBase, keyOf, ["web"]).length).toBe(1);
    expect(trendFromBase(scans, base).length).toBe(1);
  });
});

describe("trendFromFrames hideNoFix (as-of-date open exclusion)", () => {
  // Three findings first seen 2026-07-03:
  //   R1 open, no fix ever;  R2 open, fix available 07-10;  R3 resolved 07-08, fix 07-04.
  // Points d1 = 07-05, d2 = 07-15.
  const scans = [{ ts: "2026-07-05T00:00:00Z" }, { ts: "2026-07-15T00:00:00Z" }];
  const base = [
    { severity: "HIGH", first_seen: "2026-07-03T00:00:00Z", resolved_at: null, mttr_days: null, fix_available_at: null },
    { severity: "HIGH", first_seen: "2026-07-03T00:00:00Z", resolved_at: null, mttr_days: null, fix_available_at: "2026-07-10T00:00:00Z" },
    { severity: "HIGH", first_seen: "2026-07-03T00:00:00Z", resolved_at: "2026-07-08T00:00:00Z", mttr_days: 5, fix_available_at: "2026-07-04T00:00:00Z" },
  ];

  it("hideNoFix:true steps the open count down, R2 re-entering once its fix lands", () => {
    const out = trendFromFrames(scans, base, null, { hideNoFix: true });
    // d1: R1 hidden (no fix), R2 hidden (fix 07-10 > 07-05), R3 open + fix-by-d1 -> shown. open 1.
    // d2: R1 hidden, R2 re-enters (fix 07-10 <= 07-15), R3 resolved. open 1.
    expect(out.map((p) => p.open)).toEqual([1, 1]);
    // Resolved series is independent of hideNoFix: none by d1, R3 by d2.
    expect(out.map((p) => p.resolved)).toEqual([0, 1]);
  });

  it("hideNoFix absent / false is byte-identical to today (parity lock)", () => {
    const today = trendFromFrames(scans, base);
    expect(trendFromFrames(scans, base, null, {})).toEqual(today);
    expect(trendFromFrames(scans, base, null, { hideNoFix: false })).toEqual(today);
    // With the toggle off (today), all three are open at d1 and R1+R2 at d2.
    expect(today.map((p) => p.open)).toEqual([3, 2]);
    expect(today.map((p) => p.resolved)).toEqual([0, 1]);
    // The resolved-derived series match between hideNoFix on and off.
    const hidden = trendFromFrames(scans, base, null, { hideNoFix: true });
    expect(hidden.map((p) => p.median_days)).toEqual(today.map((p) => p.median_days));
    expect(hidden.map((p) => p.sla_pct)).toEqual(today.map((p) => p.sla_pct));
  });
});

describe("openBySeverityTrend", () => {
  // Two scans a day apart. A CRITICAL first seen before scan 1 and resolved between the two
  // must read open at scan 1, resolved (absent) at scan 2. A HIGH first seen before both and
  // never resolved stays open at both. A LOW first seen only after scan 1 appears at scan 2.
  const scans = [{ ts: "2026-01-01T00:00:00Z" }, { ts: "2026-01-02T00:00:00Z" }];
  const base = [
    { severity: "CRITICAL", first_seen: "2025-12-31T00:00:00Z", resolved_at: "2026-01-01T12:00:00Z" },
    { severity: "HIGH", first_seen: "2025-12-30T00:00:00Z", resolved_at: null },
    { severity: "LOW", first_seen: "2026-01-01T06:00:00Z", resolved_at: null },
  ];

  it("counts open per severity as of each scan", () => {
    expect(openBySeverityTrend(scans, base)).toEqual([
      { date: "2026-01-01T00:00:00Z", bySev: { CRITICAL: 1, HIGH: 1 } },
      { date: "2026-01-02T00:00:00Z", bySev: { HIGH: 1, LOW: 1 } },
    ]);
  });

  it("restricts to the requested severities (+ UNKNOWN)", () => {
    expect(openBySeverityTrend(scans, base, ["HIGH"])).toEqual([
      { date: "2026-01-01T00:00:00Z", bySev: { HIGH: 1 } },
      { date: "2026-01-02T00:00:00Z", bySev: { HIGH: 1 } },
    ]);
  });

  it("returns [] for empty inputs", () => {
    expect(openBySeverityTrend([], base)).toEqual([]);
    expect(openBySeverityTrend(scans, [])).toEqual([]);
  });

  it("hideNoFix excludes awaiting-as-of-date findings; a fixed-later severity re-enters", () => {
    const nfScans = [{ ts: "2026-07-05T00:00:00Z" }, { ts: "2026-07-15T00:00:00Z" }];
    const nfBase = [
      { severity: "HIGH", first_seen: "2026-07-03T00:00:00Z", resolved_at: null, fix_available_at: null }, // awaiting -> hidden both
      { severity: "CRITICAL", first_seen: "2026-07-03T00:00:00Z", resolved_at: null, fix_available_at: "2026-07-10T00:00:00Z" }, // fix 07-10: hidden at d1, shown at d2
      { severity: "LOW", first_seen: "2026-07-03T00:00:00Z", resolved_at: null, fix_available_at: "2026-07-01T00:00:00Z" }, // fix before: shown both
    ];
    expect(openBySeverityTrend(nfScans, nfBase, null, { hideNoFix: true })).toEqual([
      { date: "2026-07-05T00:00:00Z", bySev: { LOW: 1 } },
      { date: "2026-07-15T00:00:00Z", bySev: { CRITICAL: 1, LOW: 1 } },
    ]);
    // Parity: absent/false is byte-identical, with all three open at both dates.
    const today = openBySeverityTrend(nfScans, nfBase);
    expect(openBySeverityTrend(nfScans, nfBase, null, { hideNoFix: false })).toEqual(today);
    expect(today).toEqual([
      { date: "2026-07-05T00:00:00Z", bySev: { HIGH: 1, CRITICAL: 1, LOW: 1 } },
      { date: "2026-07-15T00:00:00Z", bySev: { HIGH: 1, CRITICAL: 1, LOW: 1 } },
    ]);
  });
});

describe("groupKeyOf / GROUP_COLUMNS", () => {
  // The dimension list is insights.GROUP_COLUMNS, imported rather than restated so the trend
  // and the breakdown tree can never name a different set (D8 brief rule 1).
  it("is exactly the register's five dimensions", () => {
    expect(Object.keys(GROUP_COLUMNS).sort())
      .toEqual(["cwe", "language", "owner_project", "repo", "secret_kind"]);
  });

  it("reads each dimension's own ledger column", () => {
    const row = {
      repo_name: "svc-api", language: "python", owner_project: "platform",
      secret_kind: "PASSWORD", cwe: "CWE-79",
    };
    expect(groupKeyOf("repo")(row)).toBe("svc-api");
    expect(groupKeyOf("language")(row)).toBe("python");
    expect(groupKeyOf("owner_project")(row)).toBe("platform");
    expect(groupKeyOf("secret_kind")(row)).toBe("PASSWORD");
    expect(groupKeyOf("cwe")(row)).toBe("CWE-79");
  });

  it("refuses an unknown dimension rather than silently reading a missing column", () => {
    // A missing column would read "" -> "(none)" for every row, which looks like a register
    // where nobody set the field. Refusing names the mistake instead.
    expect(() => groupKeyOf("cloud")).toThrow(/unknown group dimension/);
  });
});

describe("openByGroupTrend", () => {
  // Two scans a day apart. The group dimension is `repo` (insights.GROUP_COLUMNS.repo ->
  // repo_name); groups ["web", "db"] each keep their own series, everything else -> "Other".
  const scans = [{ ts: "2026-01-01T00:00:00Z" }, { ts: "2026-01-02T00:00:00Z" }];
  const keyOf = groupKeyOf("repo");
  const groups = ["web", "db"];
  const open = (repo_name: unknown, over: Rec = {}) => ({
    repo_name, severity: "HIGH", first_seen: "2025-12-31T00:00:00Z", resolved_at: null, ...over,
  });

  it("returns [] with no scans or no base rows", () => {
    expect(openByGroupTrend([], [open("web")], keyOf, groups)).toEqual([]);
    expect(openByGroupTrend(scans, [], keyOf, groups)).toEqual([]);
  });

  it("counts open per group as of a single scan", () => {
    const base = [open("web"), open("web"), open("db")];
    expect(openByGroupTrend([scans[0]], base, keyOf, groups)).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { web: 2, db: 1 } },
    ]);
  });

  it("drops a row from its group at the scan after it resolves", () => {
    const base = [open("web", { resolved_at: "2026-01-01T12:00:00Z" }), open("db")];
    expect(openByGroupTrend(scans, base, keyOf, groups)).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { web: 1, db: 1 } },
      { date: "2026-01-02T00:00:00Z", byGroup: { db: 1 } },
    ]);
  });

  it("normalizes null / blank group values to (none)", () => {
    const base = [open(null), open(""), open("web")];
    // "(none)" only keeps its own series when it's one of the requested groups.
    expect(openByGroupTrend([scans[0]], base, keyOf, ["(none)", "web"])).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { "(none)": 2, web: 1 } },
    ]);
  });

  it("folds values outside groups into Other; includeOther:false drops them", () => {
    const base = [open("web"), open("cache"), open("queue")];
    expect(openByGroupTrend([scans[0]], base, keyOf, groups)).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { web: 1, Other: 2 } },
    ]);
    expect(openByGroupTrend([scans[0]], base, keyOf, groups, { includeOther: false })).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { web: 1 } },
    ]);
  });

  it("honors a custom otherLabel", () => {
    expect(
      openByGroupTrend([scans[0]], [open("cache")], keyOf, groups, { otherLabel: "Rest" }),
    ).toEqual([{ date: "2026-01-01T00:00:00Z", byGroup: { Rest: 1 } }]);
  });

  it("scopes to the chosen severities plus UNKNOWN", () => {
    const base = [
      open("web", { severity: "CRITICAL" }),
      open("web", { severity: "HIGH" }),   // filtered out when scoped to CRITICAL
      open("db", { severity: "UNKNOWN" }), // UNKNOWN is never hidden
    ];
    expect(openByGroupTrend([scans[0]], base, keyOf, groups, { severities: ["CRITICAL"] })).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { web: 1, db: 1 } },
    ]);
  });

  it("groups by any GROUP_COLUMNS dimension, not just repo", () => {
    const base = [
      open("web", { secret_kind: "PASSWORD" }),
      open("web", { secret_kind: "PASSWORD" }),
      open("db", { secret_kind: "SAAS_API_KEY" }),
    ];
    expect(
      openByGroupTrend([scans[0]], base, groupKeyOf("secret_kind"), ["PASSWORD", "SAAS_API_KEY"]),
    ).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { PASSWORD: 2, SAAS_API_KEY: 1 } },
    ]);
  });
});

describe("medianMttrByGroupTrend", () => {
  // Two scans a day apart, grouped by repo. `res` mints a resolved row with a fixed mttr
  // sample; resolved_at null (+ mttr null) is an open row.
  const scans = [{ ts: "2026-01-01T00:00:00Z" }, { ts: "2026-01-02T00:00:00Z" }];
  const keyOf = groupKeyOf("repo");
  const groups = ["web", "db"];
  const res = (
    repo_name: unknown,
    mttr: number | null,
    resolved_at: string | null,
    over: Rec = {},
  ) => ({
    repo_name, severity: "HIGH", first_seen: "2025-12-31T00:00:00Z", resolved_at,
    mttr_days: mttr, ...over,
  });

  it("computes the exact median per group per ts (odd + even counts, 3-dp rounding)", () => {
    const base = [
      res("web", 2, "2026-01-01T00:00:00Z"),
      res("web", 9, "2026-01-01T00:00:00Z"),
      res("web", 4, "2026-01-01T00:00:00Z"),     // odd -> middle sample 4
      res("db", 1, "2026-01-01T00:00:00Z"),
      res("db", 1.3334, "2026-01-01T00:00:00Z"), // even -> (1 + 1.3334)/2 = 1.1667 -> 1.167
    ];
    expect(medianMttrByGroupTrend([scans[1]], base, keyOf, groups)).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { web: 4, db: 1.167 } },
    ]);
  });

  it("emits null before a group's first resolution, then a number once one resolves <= ts", () => {
    // web resolves at noon on Jan 1 (after scan 1, before scan 2); db never resolves.
    const base = [res("web", 3, "2026-01-01T12:00:00Z")];
    expect(medianMttrByGroupTrend(scans, base, keyOf, groups)).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { web: null, db: null } },
      { date: "2026-01-02T00:00:00Z", byGroup: { web: 3, db: null } },
    ]);
  });

  it("excludes rows resolved after ts, includes them (and the <= boundary) once resolved", () => {
    const base = [
      res("web", 5, "2026-01-01T00:00:00Z"),  // resolved exactly at scan 1 -> included (<=)
      res("web", 7, "2026-01-01T18:00:00Z"),  // resolved after scan 1 -> in only at scan 2
    ];
    expect(medianMttrByGroupTrend(scans, base, keyOf, groups)).toEqual([
      { date: "2026-01-01T00:00:00Z", byGroup: { web: 5, db: null } }, // just [5]
      { date: "2026-01-02T00:00:00Z", byGroup: { web: 6, db: null } }, // median [5,7]
    ]);
  });

  it("never pools open rows or resolved rows without an mttr sample", () => {
    const base = [
      res("web", 4, "2026-01-01T00:00:00Z"),
      res("web", null, null),                   // still open -> skipped
      res("db", null, "2026-01-01T00:00:00Z"),  // resolved but mttr null -> skipped
    ];
    expect(medianMttrByGroupTrend([scans[1]], base, keyOf, groups)).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { web: 4, db: null } },
    ]);
  });

  it("scopes to the chosen severities plus UNKNOWN", () => {
    const base = [
      res("web", 2, "2026-01-01T00:00:00Z", { severity: "CRITICAL" }),
      res("web", 10, "2026-01-01T00:00:00Z", { severity: "HIGH" }),   // filtered out
      res("db", 6, "2026-01-01T00:00:00Z", { severity: "UNKNOWN" }),  // never hidden
    ];
    expect(medianMttrByGroupTrend([scans[1]], base, keyOf, groups, { severities: ["CRITICAL"] })).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { web: 2, db: 6 } },
    ]);
  });

  it("pools Other's median over the remainder (not a sum); includeOther:false drops; custom otherLabel", () => {
    const base = [
      res("web", 4, "2026-01-01T00:00:00Z"),
      res("cache", 2, "2026-01-01T00:00:00Z"),
      res("queue", 8, "2026-01-01T00:00:00Z"),
    ];
    // cache + queue fold to Other -> median([2, 8]) = 5, never the sum 10.
    expect(medianMttrByGroupTrend([scans[1]], base, keyOf, groups)).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { web: 4, db: null, Other: 5 } },
    ]);
    expect(medianMttrByGroupTrend([scans[1]], base, keyOf, groups, { includeOther: false })).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { web: 4, db: null } },
    ]);
    expect(
      medianMttrByGroupTrend(
        [scans[1]],
        [res("cache", 2, "2026-01-01T00:00:00Z"), res("queue", 8, "2026-01-01T00:00:00Z")],
        keyOf,
        groups,
        { otherLabel: "Rest" },
      ),
    ).toEqual([{ date: "2026-01-02T00:00:00Z", byGroup: { web: null, db: null, Rest: 5 } }]);
  });

  it("normalizes null / blank group values to (none)", () => {
    const base = [
      res(null, 3, "2026-01-01T00:00:00Z"),
      res("", 5, "2026-01-01T00:00:00Z"),
      res("web", 9, "2026-01-01T00:00:00Z"),
    ];
    // "(none)" only keeps its own series when requested; median([3,5]) = 4.
    expect(medianMttrByGroupTrend([scans[1]], base, keyOf, ["(none)", "web"])).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { "(none)": 4, web: 9 } },
    ]);
  });

  it("returns [] for empty inputs", () => {
    expect(medianMttrByGroupTrend([], [res("web", 3, "2026-01-01T00:00:00Z")], keyOf, groups)).toEqual([]);
    expect(medianMttrByGroupTrend(scans, [], keyOf, groups)).toEqual([]);
  });

  it("minMttrDays drops fast-lane samples (mttr <= threshold), strictly", () => {
    const base = [
      res("web", 0.5, "2026-01-01T00:00:00Z"), // fast lane — dropped
      res("web", 1, "2026-01-01T00:00:00Z"),   // exactly at threshold — dropped (strict >)
      res("web", 6, "2026-01-01T00:00:00Z"),
      res("web", 10, "2026-01-01T00:00:00Z"),  // tail median = (6+10)/2 = 8
      res("db", 0.2, "2026-01-01T00:00:00Z"),  // db has only fast-lane resolutions -> null
    ];
    expect(medianMttrByGroupTrend([scans[1]], base, keyOf, groups, { minMttrDays: 1 })).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { web: 8, db: null } },
    ]);
  });

  it("minMttrDays applies to the pooled Other remainder too", () => {
    const base = [
      res("cache", 0.5, "2026-01-01T00:00:00Z"), // dropped from the pool
      res("cache", 4, "2026-01-01T00:00:00Z"),
      res("queue", 12, "2026-01-01T00:00:00Z"),  // Other tail median = (4+12)/2 = 8
    ];
    expect(medianMttrByGroupTrend([scans[1]], base, keyOf, groups, { minMttrDays: 1 })).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { web: null, db: null, Other: 8 } },
    ]);
  });
});

describe("kmMedianByGroupTrend", () => {
  // Same repo-keyed groups as medianMttrByGroupTrend, but rows carry first_seen (for the
  // censored risk set) and open rows are real (resolved_at: null, mttr_days: null) instead of
  // being skipped — a KM curve needs its censored ages, not just its events.
  const keyOf = groupKeyOf("repo");
  const groups = ["web", "db"];
  const res = (
    repo_name: unknown,
    mttr: number | null,
    resolved_at: string | null,
    over: Rec = {},
  ) => ({
    repo_name, severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at,
    mttr_days: mttr, ...over,
  });

  it("per-group KM median, with censoring pulling it above the naive (closed-only) median", () => {
    // web: two events (2, 4) plus two still-open rows, all first seen Jan 1. As of Jan 10
    // (age 9 for the open pair): events [2,4], risk set [2,4,9,9].
    //   t=2: atRisk 4, d 1 -> S=.75.  t=4: atRisk 3, d 1 -> S=.75*(2/3)=.5 <= .5 -> median 4.
    const base = [
      res("web", 2, "2026-01-03T00:00:00Z"),
      res("web", 4, "2026-01-05T00:00:00Z"),
      res("web", null, null),
      res("web", null, null),
    ];
    const scan = { ts: "2026-01-10T00:00:00Z" };
    expect(kmMedianByGroupTrend([scan], base, keyOf, groups)).toEqual([
      { date: "2026-01-10T00:00:00Z", byGroup: { web: 4, db: null } },
    ]);
    // Naive median (closed-only [2,4]) is 3 — lower than KM's 4, proving the two open rows'
    // censoring is doing real work rather than KM silently matching the naive figure.
    expect(medianMttrByGroupTrend([scan], base, keyOf, groups)).toEqual([
      { date: "2026-01-10T00:00:00Z", byGroup: { web: 3, db: null } },
    ]);
  });

  it("emits null before any event and before the 0.5 crossing, then a number once crossed", () => {
    // Four web findings first seen Jan 1, resolved 2/4/6/8 days later.
    const base = [
      res("web", 2, "2026-01-03T00:00:00Z"),
      res("web", 4, "2026-01-05T00:00:00Z"),
      res("web", 6, "2026-01-07T00:00:00Z"),
      res("web", 8, "2026-01-09T00:00:00Z"),
    ];
    const scans = [
      { ts: "2026-01-02T00:00:00Z" }, // nothing resolved yet -> no curve -> null
      { ts: "2026-01-04T00:00:00Z" }, // event [2], 3 censored at age 3: S=.75 -> null
      { ts: "2026-01-10T00:00:00Z" }, // events [2,4,6,8]: t2 S=.75, t4 S=.5 -> median 4
    ];
    expect(kmMedianByGroupTrend(scans, base, keyOf, groups)).toEqual([
      { date: "2026-01-02T00:00:00Z", byGroup: { web: null, db: null } },
      { date: "2026-01-04T00:00:00Z", byGroup: { web: null, db: null } },
      { date: "2026-01-10T00:00:00Z", byGroup: { web: 4, db: null } },
    ]);
  });

  it("pools Other's KM median over the remainder (not per-repo); includeOther:false drops", () => {
    // cache + queue both fold into Other and share ONE risk set — proving Other's curve is
    // pooled, not computed per source repo. cache has an event (3) plus a still-open row
    // (censored at age 9); queue has an event (7).
    //   events [3,7], risk set [3,7,9]: t=3 atRisk 3 d1 -> S=.667; t=7 atRisk 2 d1 ->
    //   S=.667*.5=.333 <= .5 -> median 7.
    const base = [
      res("cache", 3, "2026-01-04T00:00:00Z"),
      res("cache", null, null),
      res("queue", 7, "2026-01-08T00:00:00Z"),
    ];
    const scan = { ts: "2026-01-10T00:00:00Z" };
    expect(kmMedianByGroupTrend([scan], base, keyOf, groups)).toEqual([
      { date: "2026-01-10T00:00:00Z", byGroup: { web: null, db: null, Other: 7 } },
    ]);
    expect(kmMedianByGroupTrend([scan], base, keyOf, groups, { includeOther: false })).toEqual([
      { date: "2026-01-10T00:00:00Z", byGroup: { web: null, db: null } },
    ]);
  });

  it("scopes to the chosen severities plus UNKNOWN", () => {
    const base = [
      res("web", 2, "2026-01-03T00:00:00Z", { severity: "CRITICAL" }),
      res("web", 10, "2026-01-01T00:00:00Z", { severity: "HIGH" }), // filtered out
      res("db", 6, "2026-01-05T00:00:00Z", { severity: "UNKNOWN" }), // never hidden
    ];
    const scan = { ts: "2026-01-10T00:00:00Z" };
    // web scoped to CRITICAL: only event [2] -> atRisk 1, d1 -> S=0 <= .5 -> median 2.
    // db (UNKNOWN, always kept): only event [6] -> median 6.
    expect(kmMedianByGroupTrend([scan], base, keyOf, groups, { severities: ["CRITICAL"] })).toEqual([
      { date: "2026-01-10T00:00:00Z", byGroup: { web: 2, db: 6 } },
    ]);
  });

  it("hideNoFix drops awaiting-as-of-ts rows from the censored risk set (median can appear)", () => {
    // One resolved event (mttr 2, fix available) plus three awaiting-vendor-fix open rows
    // (fix_available_at null).
    const base = [
      res("web", 2, "2026-01-03T00:00:00Z", { fix_available_at: "2026-01-01T00:00:00Z" }),
      res("web", null, null, { fix_available_at: null }),
      res("web", null, null, { fix_available_at: null }),
      res("web", null, null, { fix_available_at: null }),
    ];
    const scan = { ts: "2026-01-10T00:00:00Z" };
    // Default: the three awaiting rows stay censored at age 9 -> risk set [2,9,9,9] ->
    // t=2 atRisk 4 d1 -> S=.75 -> null.
    expect(kmMedianByGroupTrend([scan], base, keyOf, groups)[0].byGroup.web).toBeNull();
    // hideNoFix: those three leave the risk set entirely -> risk set [2] -> S=0 -> median 2.
    expect(kmMedianByGroupTrend([scan], base, keyOf, groups, { hideNoFix: true })[0].byGroup.web).toBe(2);
  });

  it("returns [] for empty inputs", () => {
    const base = [res("web", 3, "2026-01-05T00:00:00Z")];
    expect(kmMedianByGroupTrend([], base, keyOf, groups)).toEqual([]);
    expect(kmMedianByGroupTrend([{ ts: "2026-01-10T00:00:00Z" }], [], keyOf, groups)).toEqual([]);
  });
});

describe("trendFromBase (backfill)", () => {
  // One real scan on Jul 6. Two findings first seen in June (Jun 6, Jun 20); one critical is
  // API-resolved Jul 6 with a 2-day span. Backfill should reconstruct a daily backbone from
  // Jun 6 up to (excluding) Jul 6, tagged reconstructed, with exact cumulative open counts.
  const scans = [{ ts: "2026-07-06T10:00:00Z" }];
  const base = [
    { severity: "HIGH", first_seen: "2026-06-06T00:00:00Z", resolved_at: null, mttr_days: null },
    { severity: "MEDIUM", first_seen: "2026-06-20T00:00:00Z", resolved_at: null, mttr_days: null },
    {
      severity: "CRITICAL", first_seen: "2026-07-04T00:00:00Z",
      resolved_at: "2026-07-06T00:00:00Z", mttr_days: 2,
    },
  ];

  it("with backfill off is exactly trendFromFrames, all reconstructed:false", () => {
    const out = trendFromBase(scans, base);
    expect(out.length).toBe(1);
    expect(out[0].date).toBe("2026-07-06T10:00:00Z");
    expect(out[0].reconstructed).toBe(false);
    const { reconstructed: _r, ...bare } = out[0];
    expect([bare]).toEqual(trendFromFrames(scans, base));
  });

  it("reconstructs a daily backbone from the earliest first_seen to the first scan", () => {
    const out = trendFromBase(scans, base, null, { backfill: true });
    // 30 synthetic days (Jun 6 .. Jul 5 inclusive) + 1 real scan.
    expect(out[0].date).toBe("2026-06-06T00:00:00Z");
    expect(out.filter((p) => p.reconstructed).length).toBe(30);
    expect(out.filter((p) => !p.reconstructed).length).toBe(1);
    expect(out[out.length - 1].date).toBe("2026-07-06T10:00:00Z");
    expect(out[out.length - 1].reconstructed).toBe(false);
    // Open counts are the exact cumulative first_seen<=ts population.
    expect(out.find((p) => p.date === "2026-06-06T00:00:00Z")!.open).toBe(1);
    expect(out.find((p) => p.date === "2026-06-20T00:00:00Z")!.open).toBe(2);
  });

  it("does not backfill when the earliest first_seen is not before the first scan", () => {
    const laterBase = base.map((r) => ({ ...r, first_seen: "2026-07-06T00:00:00Z" }));
    const out = trendFromBase(scans, laterBase, null, { backfill: true });
    expect(out.length).toBe(1);
    expect(out.every((p) => !p.reconstructed)).toBe(true);
  });

  it("returns [] for empty inputs even with backfill on", () => {
    expect(trendFromBase([], base, null, { backfill: true })).toEqual([]);
    expect(trendFromBase(scans, [], null, { backfill: true })).toEqual([]);
  });

  it("stamps synthetic scans with the requested scope, so the backbone survives the filter", () => {
    // NEW (rule 2). trendFromFrames filters the SCAN LOG by scope as well as the rows, so a
    // synthetic backbone row without a `scope` would be dropped one line after it is built and
    // the backfill would silently vanish — the register reading as if it had no history.
    const scopedScans = [{ ts: "2026-07-06T10:00:00Z", scope: "sca" }];
    const scopedBase = base.map((r) => ({ ...r, scope: "sca" }));
    const out = trendFromBase(scopedScans, scopedBase, null, { backfill: true, scope: "sca" });
    expect(out.filter((p) => p.reconstructed).length).toBe(30);
    // And it is exactly the unscoped answer on an all-sca state.
    expect(out).toEqual(trendFromBase(scans, base, null, { backfill: true }));
  });
});

describe("withOpenPastSla", () => {
  // A CRITICAL (target 7) open all along, a HIGH resolved Jan 10, and an UNKNOWN (no target)
  // open all along, all first seen Jan 1.
  const base = [
    { severity: "CRITICAL", first_seen: "2026-01-01T00:00:00Z", resolved_at: null },
    { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-10T00:00:00Z" },
    { severity: "UNKNOWN", first_seen: "2026-01-01T00:00:00Z", resolved_at: null },
  ];

  it("counts open-past-SLA as of each point date and preserves existing fields", () => {
    // Jan 5: CRITICAL age 4d <= 7 -> none breached. Jan 15: CRITICAL age 14d > 7 -> 1
    // (HIGH is resolved by then; UNKNOWN has no target).
    const points = [
      { date: "2026-01-05T00:00:00Z", open: 99, foo: "a" },
      { date: "2026-01-15T00:00:00Z", open: 88, foo: "b" },
    ];
    expect(withOpenPastSla(points, base)).toEqual([
      { date: "2026-01-05T00:00:00Z", open: 99, foo: "a", open_past_sla: 0 },
      { date: "2026-01-15T00:00:00Z", open: 88, foo: "b", open_past_sla: 1 },
    ]);
  });

  it("scopes to the chosen severities plus UNKNOWN", () => {
    const b = [
      { severity: "CRITICAL", first_seen: "2026-01-01T00:00:00Z", resolved_at: null }, // 14d > 7 -> breached
      { severity: "MEDIUM", first_seen: "2025-11-01T00:00:00Z", resolved_at: null }, // ~75d > 30 -> breached
      { severity: "UNKNOWN", first_seen: "2026-01-01T00:00:00Z", resolved_at: null }, // no target
    ];
    const points = [{ date: "2026-01-15T00:00:00Z" }];
    // Unscoped: CRITICAL + MEDIUM breach = 2.
    expect(withOpenPastSla(points, b)[0].open_past_sla).toBe(2);
    // Scoped to CRITICAL: MEDIUM filtered out, UNKNOWN kept (but never breaches) -> 1.
    expect(withOpenPastSla(points, b, ["CRITICAL"])[0].open_past_sla).toBe(1);
  });

  it("a finding resolved before the point date drops out", () => {
    const b = [{ severity: "CRITICAL", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-10T00:00:00Z" }];
    // Jan 9: still open (resolved_at > d), age 8d > 7 -> breached.
    expect(withOpenPastSla([{ date: "2026-01-09T00:00:00Z" }], b)[0].open_past_sla).toBe(1);
    // Jan 20: resolved by then -> not open -> 0.
    expect(withOpenPastSla([{ date: "2026-01-20T00:00:00Z" }], b)[0].open_past_sla).toBe(0);
  });

  it("counts synthetic/reconstructed points the same as real ones (by date only)", () => {
    const b = [{ severity: "CRITICAL", first_seen: "2026-01-01T00:00:00Z", resolved_at: null }];
    const points = [
      { date: "2026-01-15T00:00:00Z", reconstructed: true }, // synthetic backfill day
      { date: "2026-01-15T00:00:00Z", reconstructed: false }, // real saved scan, same date
    ];
    const out = withOpenPastSla(points, b);
    expect(out[0].open_past_sla).toBe(1);
    expect(out[1].open_past_sla).toBe(out[0].open_past_sla);
    // Passthrough keeps the reconstructed flag untouched.
    expect(out.map((p) => p.reconstructed)).toEqual([true, false]);
  });

  it("fromField 'actionable_from' shifts breach ages and skips null-actionable rows", () => {
    // All CRITICAL (target 7). A has a fix from detection; B's fix arrived on Jan 10; C is
    // awaiting a vendor fix (null actionable_from). As of Jan 15:
    //   default (first_seen origin): all three age 14d > 7 -> 3 breached.
    //   actionable_from origin: A ages from Jan 1 (14d, breached); B ages from Jan 10 (5d,
    //   within target); C is skipped (null origin) -> 1 breached.
    const b = [
      { severity: "CRITICAL", first_seen: "2026-01-01T00:00:00Z", actionable_from: "2026-01-01T00:00:00Z", resolved_at: null },
      { severity: "CRITICAL", first_seen: "2026-01-01T00:00:00Z", actionable_from: "2026-01-10T00:00:00Z", resolved_at: null },
      { severity: "CRITICAL", first_seen: "2026-01-01T00:00:00Z", actionable_from: null, resolved_at: null },
    ];
    const points = [{ date: "2026-01-15T00:00:00Z" }];
    expect(withOpenPastSla(points, b)[0].open_past_sla).toBe(3);
    expect(withOpenPastSla(points, b, null, "actionable_from")[0].open_past_sla).toBe(1);
  });
});

describe("withSlaBurn", () => {
  // All CRITICAL (target 7), actionable_from Jan 1 -> deadline Jan 8. Scans Jan 1 / Jan 10 /
  // Jan 20 bracket the deadline (crossing in window 2) and B's late resolution (window 3).
  //   A: never resolved -> crosses into breach.
  //   B: resolved Jan 15, AFTER the deadline -> crosses, then clears.
  //   C: resolved Jan 5, BEFORE the deadline -> never breaches, never counts.
  //   D: awaiting a vendor fix (null actionable_from) -> never counts.
  //   E: UNKNOWN, no SLA target -> never counts.
  const base = [
    { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: null },
    { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: "2026-01-15T00:00:00Z" },
    { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: "2026-01-05T00:00:00Z" },
    { severity: "CRITICAL", actionable_from: null, resolved_at: null },
    { severity: "UNKNOWN", actionable_from: "2026-01-01T00:00:00Z", resolved_at: null },
  ];
  const points = [
    { date: "2026-01-01T00:00:00Z", foo: "a" },
    { date: "2026-01-10T00:00:00Z", foo: "b" },
    { date: "2026-01-20T00:00:00Z", foo: "c" },
  ];

  it("first point is null; entered/cleared/net per window; exclusions never count", () => {
    expect(withSlaBurn(points, base)).toEqual([
      { date: "2026-01-01T00:00:00Z", foo: "a", sla_entered: null, sla_cleared: null, sla_net: null },
      // Window (Jan 1, Jan 10]: A and B cross into breach (deadline Jan 8, unresolved by it);
      // C resolved before its deadline; D/E excluded. entered 2, cleared 0.
      { date: "2026-01-10T00:00:00Z", foo: "b", sla_entered: 2, sla_cleared: 0, sla_net: 2 },
      // Window (Jan 10, Jan 20]: no new deadlines; B's late resolution (Jan 15 > deadline)
      // clears. entered 0, cleared 1.
      { date: "2026-01-20T00:00:00Z", foo: "c", sla_entered: 0, sla_cleared: 1, sla_net: -1 },
    ]);
  });

  it("scopes to the chosen severities plus UNKNOWN", () => {
    const b = [
      { severity: "HIGH", actionable_from: "2026-01-01T00:00:00Z", resolved_at: null }, // deadline Jan 15
      { severity: "MEDIUM", actionable_from: "2025-12-01T00:00:00Z", resolved_at: null }, // deadline ~Dec 31
    ];
    const pts = [{ date: "2026-01-01T00:00:00Z" }, { date: "2026-01-20T00:00:00Z" }];
    // Unscoped window (Jan 1, Jan 20]: HIGH deadline Jan 15 in window; MEDIUM deadline Dec 31
    // is before Jan 1, so it does not cross this window -> only HIGH enters.
    expect(withSlaBurn(pts, b)[1].sla_entered).toBe(1);
    // Scoped to HIGH: MEDIUM filtered out entirely -> still 1.
    expect(withSlaBurn(pts, b, ["HIGH"])[1].sla_entered).toBe(1);
    // A window that brackets the MEDIUM deadline shows it unscoped but not when scoped to HIGH.
    const ptsDec = [{ date: "2025-12-01T00:00:00Z" }, { date: "2026-01-20T00:00:00Z" }];
    expect(withSlaBurn(ptsDec, b)[1].sla_entered).toBe(2);
    expect(withSlaBurn(ptsDec, b, ["HIGH"])[1].sla_entered).toBe(1);
  });
});

describe("cohortSlaAttainment", () => {
  // All CRITICAL (target 7), actionable_from Jan 1 -> deadline Jan 8.
  //   A: still open -> misses (open past deadline).
  //   B: resolved Jan 15, after the deadline -> misses (late).
  //   C: resolved Jan 5, on time -> hits.
  const base = [
    { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: null },
    { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: "2026-01-15T00:00:00Z" },
    { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: "2026-01-05T00:00:00Z" },
  ];

  it("cohort membership by deadline<=d; late/open miss, on-time hits; empty cohort null", () => {
    const points = [
      { date: "2026-01-05T00:00:00Z", foo: "a" }, // deadline Jan 8 not yet passed -> empty cohort
      { date: "2026-01-10T00:00:00Z", foo: "b" }, // all three in cohort; 1 of 3 on time -> 33.3
    ];
    expect(cohortSlaAttainment(points, base)).toEqual([
      { date: "2026-01-05T00:00:00Z", foo: "a", sla_attainment_pct: null },
      { date: "2026-01-10T00:00:00Z", foo: "b", sla_attainment_pct: 33.3 },
    ]);
  });

  it("excludes awaiting-vendor-fix and no-target rows from the cohort", () => {
    const b = [
      { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: "2026-01-05T00:00:00Z" }, // on time
      { severity: "CRITICAL", actionable_from: null, resolved_at: null }, // awaiting -> excluded
      { severity: "UNKNOWN", actionable_from: "2026-01-01T00:00:00Z", resolved_at: null }, // no target -> excluded
    ];
    // Only the one CRITICAL is in the cohort as of Jan 10, and it was on time -> 100.
    expect(cohortSlaAttainment([{ date: "2026-01-10T00:00:00Z" }], b)[0].sla_attainment_pct).toBe(100);
  });

  it("resolved exactly at the deadline counts as on time (<=)", () => {
    const b = [{ severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: "2026-01-08T00:00:00Z" }];
    // deadline is Jan 1 + 7d = Jan 8; resolved exactly then -> met.
    expect(cohortSlaAttainment([{ date: "2026-01-10T00:00:00Z" }], b)[0].sla_attainment_pct).toBe(100);
  });

  it("rounds attainment to one decimal place", () => {
    // 2 of 3 on time = 66.666… -> 66.7.
    const b = [
      { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: "2026-01-05T00:00:00Z" },
      { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: "2026-01-06T00:00:00Z" },
      { severity: "CRITICAL", actionable_from: "2026-01-01T00:00:00Z", resolved_at: null },
    ];
    expect(cohortSlaAttainment([{ date: "2026-01-10T00:00:00Z" }], b)[0].sla_attainment_pct).toBe(66.7);
  });
});

describe("withKmMedian", () => {
  // Four HIGH findings all first seen 2026-01-01, resolved 2/4/6/8 days later. As of an early
  // date only some have resolved (the rest are right-censored at their current age); as of a
  // late date all four are events and the KM staircase crosses 0.5.
  const base = [
    { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-03T00:00:00Z", mttr_days: 2 },
    { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-05T00:00:00Z", mttr_days: 4 },
    { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-07T00:00:00Z", mttr_days: 6 },
    { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-09T00:00:00Z", mttr_days: 8 },
  ];

  it("null before any event / before the 0.5 crossing; KM median as of each date", () => {
    const points = [
      { date: "2026-01-02T00:00:00Z", foo: "a" }, // nothing resolved yet -> null
      { date: "2026-01-04T00:00:00Z", foo: "b" }, // event [2], three censored at age 3: t2 n=4 S=.75 -> null
      { date: "2026-01-10T00:00:00Z", foo: "c" }, // events [2,4,6,8]: t2 S=.75, t4 S=.5 -> median 4
    ];
    expect(withKmMedian(points, base)).toEqual([
      { date: "2026-01-02T00:00:00Z", foo: "a", km_median_days: null },
      { date: "2026-01-04T00:00:00Z", foo: "b", km_median_days: null },
      { date: "2026-01-10T00:00:00Z", foo: "c", km_median_days: 4 },
    ]);
  });

  it("scopes to the chosen severities plus UNKNOWN", () => {
    const b = [
      { severity: "CRITICAL", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-03T00:00:00Z", mttr_days: 2 },
      { severity: "MEDIUM", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-05T00:00:00Z", mttr_days: 4 },
      { severity: "UNKNOWN", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-07T00:00:00Z", mttr_days: 6 },
    ];
    const points = [{ date: "2026-01-10T00:00:00Z" }];
    // Unscoped events [2,4,6]: t2 n=3 S=.667, t4 n=2 S=.333 <= .5 -> median 4.
    // Scoped to CRITICAL (UNKNOWN kept) events [2,6]: t2 n=2 S=.5 <= .5 -> median 2.
    expect(withKmMedian(points, b)[0].km_median_days).toBe(4);
    expect(withKmMedian(points, b, ["CRITICAL"])[0].km_median_days).toBe(2);
  });

  it("rounds the KM median to 3 decimals like trendFromFrames", () => {
    // A single event at 5.0006: S drops straight to 0, so the median is that event time.
    const b = [{ severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-06T00:00:00Z", mttr_days: 5.0006 }];
    expect(withKmMedian([{ date: "2026-01-15T00:00:00Z" }], b)[0].km_median_days).toBe(5.001);
  });

  it("hideNoFix drops awaiting-as-of-date rows from the censored risk set (median can appear)", () => {
    // One resolved event at 2 (fix available), plus three awaiting-vendor-fix rows open as of
    // the point date (age 9, no fix ever). Censored, those three keep S above 0.5 -> no median;
    // hideNoFix removes them from the risk set, so the lone event crosses to 0 -> median 2.
    const b = [
      { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-03T00:00:00Z", mttr_days: 2, fix_available_at: "2026-01-01T00:00:00Z" },
      { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: null, mttr_days: null, fix_available_at: null },
      { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: null, mttr_days: null, fix_available_at: null },
      { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: null, mttr_days: null, fix_available_at: null },
    ];
    const points = [{ date: "2026-01-10T00:00:00Z" }];
    // Default (toggle off): the three censored awaiting rows hold S at 0.75 -> null.
    expect(withKmMedian(points, b)[0].km_median_days).toBeNull();
    // Parity: absent vs explicit false are identical.
    expect(withKmMedian(points, b, null, { hideNoFix: false })).toEqual(withKmMedian(points, b));
    // hideNoFix: the awaiting rows leave the risk set; the resolved event still counts.
    expect(withKmMedian(points, b, null, { hideNoFix: true })[0].km_median_days).toBe(2);
  });

  describe("maxReconstructed sampling", () => {
    // A base whose events (as of a late date) give a stable KM median of 4, so every computed
    // point carries the same non-null value and only the compute/skip pattern varies.
    const late = base; // events [2,4,6,8] -> median 4 as of 2026-01-10+
    const mk = (n: number, reconstructed: boolean) =>
      Array.from({ length: n }, (_, i) => ({
        date: `2026-02-${String(i + 1).padStart(2, "0")}T00:00:00Z`,
        reconstructed,
      }));

    it("is byte-identical to unlimited when the backbone fits under the cap", () => {
      const points = mk(5, true);
      expect(withKmMedian(points, late, null, { maxReconstructed: 10 }))
        .toEqual(withKmMedian(points, late));
    });

    it("never skips real (non-reconstructed) points", () => {
      const points = mk(20, false);
      const out = withKmMedian(points, late, null, { maxReconstructed: 3 });
      expect(out.every((p) => p.km_median_days === 4)).toBe(true);
    });

    it("thins reconstructed points to an evenly spaced sample, keeping first + last", () => {
      const points = mk(20, true);
      const out = withKmMedian(points, late, null, { maxReconstructed: 5 });
      const computed = out.filter((p) => p.km_median_days !== null);
      expect(computed).toHaveLength(5);
      // Endpoints always retained.
      expect(out[0].km_median_days).toBe(4);
      expect(out[out.length - 1].km_median_days).toBe(4);
    });

    it("computes every real point and only samples the reconstructed backbone", () => {
      // 2 real points bracketing 10 reconstructed ones; cap the backbone at 4.
      const points = [
        { date: "2026-02-01T00:00:00Z", reconstructed: false },
        ...mk(10, true).map((p, i) => ({ ...p, date: `2026-02-${String(i + 2).padStart(2, "0")}T00:00:00Z` })),
        { date: "2026-02-20T00:00:00Z", reconstructed: false },
      ];
      const out = withKmMedian(points, late, null, { maxReconstructed: 4 });
      const realComputed = out.filter((p) => !p.reconstructed && p.km_median_days !== null);
      const reconComputed = out.filter((p) => p.reconstructed && p.km_median_days !== null);
      expect(realComputed).toHaveLength(2); // both real points always compute
      expect(reconComputed).toHaveLength(4); // backbone sampled to the cap
    });
  });

  describe("kmSkipMask", () => {
    it("returns null (skip nothing) when unset or the backbone fits", () => {
      const pts = [{ reconstructed: true }, { reconstructed: true }];
      expect(kmSkipMask(pts)).toBeNull();
      expect(kmSkipMask(pts, 5)).toBeNull();
    });

    it("skips only surplus reconstructed points, keeping evenly spaced endpoints", () => {
      const pts = [
        { reconstructed: false },
        { reconstructed: true }, { reconstructed: true }, { reconstructed: true },
        { reconstructed: true }, { reconstructed: true },
        { reconstructed: false },
      ];
      const mask = kmSkipMask(pts, 2)!;
      expect(mask[0]).toBe(false); // real point never skipped
      expect(mask[6]).toBe(false); // real point never skipped
      // Of the 5 reconstructed points (idx 1..5), exactly 2 kept (first + last of the run).
      const keptRecon = [1, 2, 3, 4, 5].filter((i) => !mask[i]);
      expect(keptRecon).toEqual([1, 5]);
    });

    it("the whole mask, index by index, at max 3 over 5 reconstructed points", () => {
      // NEW, and it is the perturbation guard: the ported test above reads only the kept SET,
      // so an off-by-one in `Math.round((k * last) / denom)` that still keeps the endpoints
      // slips through it. reconIdx = [1,2,3,4,5], last = 4, denom = 2:
      //   k=0 -> round(0)   = 0 -> keep idx 1
      //   k=1 -> round(4/2) = 2 -> keep idx 3
      //   k=2 -> round(8/2) = 4 -> keep idx 5
      const pts = [
        { reconstructed: false },
        { reconstructed: true }, { reconstructed: true }, { reconstructed: true },
        { reconstructed: true }, { reconstructed: true },
        { reconstructed: false },
      ];
      expect(kmSkipMask(pts, 3)).toEqual([false, false, true, false, true, false, false]);
    });

    it("max 0 skips every reconstructed point and max 1 keeps only the first", () => {
      const pts = [{ reconstructed: true }, { reconstructed: true }, { reconstructed: true }];
      expect(kmSkipMask(pts, 0)).toEqual([true, true, true]);
      // max 1: denom 1, k=0 -> round(0) = 0 -> the run's first index.
      expect(kmSkipMask(pts, 1)).toEqual([false, true, true]);
    });

    it("a negative cap means 'no cap', not 'skip everything'", () => {
      expect(kmSkipMask([{ reconstructed: true }], -1)).toBeNull();
    });
  });
});

describe("kmMedianAsOf", () => {
  // A mix of resolved (events) and still-open (censored) rows spanning several weeks.
  const base: Rec[] = [
    { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-05T00:00:00Z", mttr_days: 4, fix_available_at: null },
    { severity: "HIGH", first_seen: "2026-01-02T00:00:00Z", resolved_at: "2026-01-12T00:00:00Z", mttr_days: 10, fix_available_at: null },
    { severity: "CRITICAL", first_seen: "2026-01-03T00:00:00Z", resolved_at: null, mttr_days: null, fix_available_at: null },
    { severity: "LOW", first_seen: "2026-01-04T00:00:00Z", resolved_at: "2026-01-20T00:00:00Z", mttr_days: 16, fix_available_at: null },
  ];

  it("matches withKmMedian point-for-point across dates and severity scopes", () => {
    const dates = ["2026-01-06T00:00:00Z", "2026-01-13T00:00:00Z", "2026-01-21T00:00:00Z"];
    for (const severities of [null, ["HIGH"], ["CRITICAL", "HIGH"]] as (string[] | null)[]) {
      const series = withKmMedian(dates.map((date) => ({ date })), base, severities);
      dates.forEach((date, i) => {
        expect(kmMedianAsOf(base, severities, Date.parse(date))).toBe(series[i].km_median_days);
      });
    }
  });

  it("honors hideNoFix identically to withKmMedian (awaiting row drops from the risk set)", () => {
    const nfBase: Rec[] = [
      { severity: "HIGH", first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-01-05T00:00:00Z", mttr_days: 4, fix_available_at: "2026-01-02T00:00:00Z" },
      { severity: "HIGH", first_seen: "2026-01-02T00:00:00Z", resolved_at: null, mttr_days: null, fix_available_at: "2026-02-01T00:00:00Z" },
    ];
    const date = "2026-01-10T00:00:00Z";
    const [pt] = withKmMedian([{ date }], nfBase, null, { hideNoFix: true });
    expect(kmMedianAsOf(nfBase, null, Date.parse(date), { hideNoFix: true })).toBe(pt.km_median_days);
  });

  it("returns null for no rows or a null date", () => {
    expect(kmMedianAsOf([], null, Date.parse("2026-01-10T00:00:00Z"))).toBeNull();
    expect(kmMedianAsOf(base, null, null)).toBeNull();
  });
});

// --------------------------------------------------------------------------- #
//  withCoverageEfficiency — ported from gas/test/program.test.ts (it tests trend.ts)
// --------------------------------------------------------------------------- #

const RULE: RiskRule = DEFAULT_RISK_RULE; // KEV or exploit or EPSS >= 0.10

describe("withCoverageEfficiency (trend decorator)", () => {
  // Three high-risk lifecycles and one low-risk one, resolving on known dates, so the series
  // can be checked by hand at each point:
  //
  //   A  high, first seen 01-01, resolved 02-01
  //   B  high, first seen 01-01, still open
  //   C  high, first seen 03-01, resolved 03-15
  //   D  low,  first seen 01-01, resolved 02-01
  //   E  unknown signals, first seen 01-01, still open
  //
  //   as of 2026-01-15:  exists A,B,D,E. remediated none.
  //                      TP 0, FN 2 (A,B), FP 0  -> coverage 0%, efficiency null
  //   as of 2026-02-15:  A and D remediated.
  //                      TP 1, FN 1 (B), FP 1 (D) -> coverage 50%, efficiency 50%
  //   as of 2026-03-20:  C exists and is remediated too.
  //                      TP 2, FN 1 (B), FP 1 (D) -> coverage 66.7%, efficiency 66.7%
  //
  // ADAPTED: every row carries `scope: "sca"`. program.classifyRisk resolves the rule per
  // scope (`ruleForScope`), so a scope-less row would be refused — gas/ has one register and
  // needs no such column.
  const base = [
    { scope: "sca", severity: "HIGH", status: "RESOLVED", has_kev: true, has_exploit: false, epss: 0.01,
      first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-02-01T00:00:00Z" },
    { scope: "sca", severity: "HIGH", status: "OPEN", has_kev: true, has_exploit: false, epss: 0.01,
      first_seen: "2026-01-01T00:00:00Z", resolved_at: null },
    { scope: "sca", severity: "HIGH", status: "RESOLVED", has_kev: true, has_exploit: false, epss: 0.01,
      first_seen: "2026-03-01T00:00:00Z", resolved_at: "2026-03-15T00:00:00Z" },
    { scope: "sca", severity: "HIGH", status: "RESOLVED", has_kev: false, has_exploit: false, epss: 0.01,
      first_seen: "2026-01-01T00:00:00Z", resolved_at: "2026-02-01T00:00:00Z" },
    { scope: "sca", severity: "HIGH", status: "OPEN", has_kev: null, has_exploit: null, epss: null,
      first_seen: "2026-01-01T00:00:00Z", resolved_at: null },
  ];
  const points = [
    { date: "2026-01-15T00:00:00Z", open: 0 },
    { date: "2026-02-15T00:00:00Z", open: 0 },
    { date: "2026-03-20T00:00:00Z", open: 0 },
  ];
  const out = withCoverageEfficiency(points, base, RULE);

  it("computes both rates as of each point's date", () => {
    expect(out[0].coverage_pct).toBe(0);
    expect(out[0].efficiency_pct).toBeNull(); // nothing remediated yet
    expect(out[1].coverage_pct).toBe(50);
    expect(out[1].efficiency_pct).toBe(50);
    expect(out[2].coverage_pct).toBe(66.7);
    expect(out[2].efficiency_pct).toBe(66.7);
  });

  it("excludes rows that did not exist yet at the point's date", () => {
    // C is first seen 03-01, so it is absent from the first two points entirely.
    expect(out[0].high_risk_open).toBe(2); // A and B, not C
    expect(out[2].high_risk_remediated).toBe(2); // A and C
  });

  it("reports the unclassified share alongside the rates", () => {
    expect(out[0].unknown_pct).toBe(25); // E of the four rows that existed on 01-15
    expect(out[1].unknown_pct).toBe(25);
    expect(out[2].unknown_pct).toBe(20); // five rows exist by then
  });

  it("preserves the caller's existing point fields", () => {
    expect(out[0].date).toBe("2026-01-15T00:00:00Z");
    expect(out[0].open).toBe(0);
  });

  it("scopes to the given severities", () => {
    const scoped = withCoverageEfficiency(points, base, RULE, ["LOW"]);
    expect(scoped[2].coverage_pct).toBeNull(); // no HIGH rows left to score
  });

  it("omitting the rule falls back to each row's scope rule and gives the same answer", () => {
    // ruleForScope("sca") IS DEFAULT_RISK_RULE, so this must be identical, not merely close.
    expect(withCoverageEfficiency(points, base)).toEqual(out);
  });

  // ---- NEW: the secrets refusal -------------------------------------------------------
  it("excludes secrets rows and COUNTS them, rather than throwing or hiding them", () => {
    // program.classifyRisk THROWS on a secrets row (ruleForScope("secrets") is null): there is
    // no exploit intelligence for a hardcoded string. Two secrets rows are added to the same
    // base — one existing from 01-01, one only from 03-01.
    const mixed = [
      ...base,
      { scope: "secrets", severity: "LOW", status: "OPEN", has_kev: null, has_exploit: null, epss: null,
        first_seen: "2026-01-01T00:00:00Z", resolved_at: null },
      { scope: "secrets", severity: "CRITICAL", status: "OPEN", has_kev: null, has_exploit: null, epss: null,
        first_seen: "2026-03-01T00:00:00Z", resolved_at: null },
    ];
    const mixedOut = withCoverageEfficiency(points, mixed, RULE);
    // Every rate is BYTE-IDENTICAL to the sca-only series: the secrets rows leave both sides.
    expect(mixedOut.map((p) => p.coverage_pct)).toEqual(out.map((p) => p.coverage_pct));
    expect(mixedOut.map((p) => p.efficiency_pct)).toEqual(out.map((p) => p.efficiency_pct));
    expect(mixedOut.map((p) => p.unknown_pct)).toEqual(out.map((p) => p.unknown_pct));
    // And the exclusion is REPORTED as of each date: 1 secret exists on 01-15 and 02-15, 2 by 03-20.
    expect(mixedOut.map((p) => p.secrets_excluded)).toEqual([1, 1, 2]);
    // The sca-only series excludes nothing.
    expect(out.map((p) => p.secrets_excluded)).toEqual([0, 0, 0]);
  });

  it("a secrets-only register yields null rates and the whole population as excluded", () => {
    const secretsOnly = [
      { scope: "secrets", severity: "LOW", status: "OPEN", has_kev: null, has_exploit: null, epss: null,
        first_seen: "2026-01-01T00:00:00Z", resolved_at: null },
    ];
    const [p] = withCoverageEfficiency([points[2]], secretsOnly, RULE);
    expect(p.coverage_pct).toBeNull();
    expect(p.efficiency_pct).toBeNull();
    expect(p.unknown_pct).toBeNull(); // the classifiable population is empty, not 100% unknown
    expect(p.secrets_excluded).toBe(1);
  });
});

describe("openByRiskTierTrend", () => {
  // ADDITION over gas/, which has no risk-tier series. The tiers PARTITION the population
  // (program.RISK_TIER_ORDER), so `includeOther` is forced off and no row can fold away.
  const scans = [{ ts: "2026-02-15T00:00:00Z" }];
  const sca = (over: Rec) => ({
    scope: "sca", severity: "HIGH", status: "OPEN", has_kev: false, has_exploit: false, epss: 0.01,
    first_seen: "2026-01-01T00:00:00Z", resolved_at: null, ...over,
  });

  it("counts open findings per tier, and every tier is a RISK_TIER_ORDER name", () => {
    const base = [
      sca({ has_kev: true }),                       // kev
      sca({ has_exploit: true }),                   // exploit
      sca({ epss: 0.5 }),                           // epss
      sca({}),                                      // none (all observed, none fired)
      sca({ has_kev: null, has_exploit: null, epss: null }), // unknown
    ];
    const { points, secrets_excluded } = openByRiskTierTrend(scans, base, RULE);
    expect(points).toEqual([
      { date: "2026-02-15T00:00:00Z", byGroup: { kev: 1, exploit: 1, epss: 1, none: 1, unknown: 1 } },
    ]);
    expect(secrets_excluded).toBe(0);
    expect(Object.keys(points[0].byGroup).every((k) => (RISK_TIER_ORDER as string[]).includes(k)))
      .toBe(true);
  });

  it("drops secrets rows before classification and reports how many", () => {
    const base = [
      sca({ has_kev: true }),
      { scope: "secrets", severity: "LOW", status: "OPEN", first_seen: "2026-01-01T00:00:00Z", resolved_at: null },
      { scope: "secrets", severity: "LOW", status: "OPEN", first_seen: "2026-01-01T00:00:00Z", resolved_at: null },
    ];
    const { points, secrets_excluded } = openByRiskTierTrend(scans, base, RULE);
    expect(points[0].byGroup).toEqual({ kev: 1 });
    expect(secrets_excluded).toBe(2);
  });
});

// --------------------------------------------------------------------------- #
//  NEW: the scope filter (D8 brief rule 2) and the per-scope stack
// --------------------------------------------------------------------------- #

describe("scope filter — rows AND the scan log", () => {
  // A mixed sca/secrets state. The two registers have DIFFERENT scan cadences on purpose: if
  // a function filtered only the rows and not the scan log, the sca series would still carry
  // the secrets scan dates and the assertion below would fail on point count alone.
  //
  //   sca scans:     Jan 1, Jan 5      secrets scans: Jan 3, Jan 7
  //   sca rows:      S1 CRITICAL first 2025-12-20, resolved 2026-01-04, mttr 15  (late)
  //                  S2 HIGH     first 2025-12-25, still open
  //   secrets rows:  X1 LOW      first 2025-09-01, still open                    (breached)
  //                  X2 CRITICAL first 2025-12-02, resolved 2025-12-05, mttr 3   (on time)
  //
  // The secrets rows' dates are chosen so the mixed answer DIFFERS from the sca-only one on
  // every series checked below — X1 is old enough to breach LOW's 90-day target, and X2 is
  // the only row in the whole state that meets its deadline. A first draft had X1 at
  // 2025-12-01 and X2 resolving 2026-01-06: both `open_past_sla` and `sla_attainment_pct`
  // then came out IDENTICAL scoped and unscoped, so the "genuinely differ" guard passed
  // vacuously and would not have caught a dropped filter.
  const scans: Rec[] = [
    { scan_id: "a1", ts: "2026-01-01T00:00:00Z", scope: "sca" },
    { scan_id: "b1", ts: "2026-01-03T00:00:00Z", scope: "secrets" },
    { scan_id: "a2", ts: "2026-01-05T00:00:00Z", scope: "sca" },
    { scan_id: "b2", ts: "2026-01-07T00:00:00Z", scope: "secrets" },
  ];
  const base: Rec[] = [
    { scope: "sca", repo_name: "web", severity: "CRITICAL", status: "RESOLVED",
      has_kev: true, has_exploit: false, epss: 0.01,
      first_seen: "2025-12-20T00:00:00Z", resolved_at: "2026-01-04T00:00:00Z", mttr_days: 15,
      actionable_from: "2025-12-20T00:00:00Z", fix_available_at: "2025-12-20T00:00:00Z" },
    { scope: "sca", repo_name: "web", severity: "HIGH", status: "OPEN",
      has_kev: false, has_exploit: false, epss: 0.01,
      first_seen: "2025-12-25T00:00:00Z", resolved_at: null, mttr_days: null,
      actionable_from: "2025-12-25T00:00:00Z", fix_available_at: "2025-12-25T00:00:00Z" },
    { scope: "secrets", repo_name: "db", severity: "LOW", status: "OPEN",
      first_seen: "2025-09-01T00:00:00Z", resolved_at: null, mttr_days: null,
      actionable_from: "2025-09-01T00:00:00Z", fix_available_at: "2025-09-01T00:00:00Z" },
    { scope: "secrets", repo_name: "db", severity: "CRITICAL", status: "RESOLVED",
      first_seen: "2025-12-02T00:00:00Z", resolved_at: "2025-12-05T00:00:00Z", mttr_days: 3,
      actionable_from: "2025-12-02T00:00:00Z", fix_available_at: "2025-12-02T00:00:00Z" },
  ];
  const scaScans = scans.filter((s) => s["scope"] === "sca");
  const scaBase = base.filter((r) => r["scope"] === "sca");
  const points = [{ date: "2026-01-04T00:00:00Z" }, { date: "2026-01-31T00:00:00Z" }];
  const keyOf = groupKeyOf("repo");

  it("the mixed and sca-only answers genuinely differ, so the checks below are not vacuous", () => {
    // Unscoped: 4 scan points, 4 rows. sca-only: 2 scan points, 2 rows.
    expect(trendFromFrames(scans, base).length).toBe(4);
    expect(trendFromFrames(scaScans, scaBase).length).toBe(2);
    // As of Jan 5 the mixed register has 2 open (S2, X1 — S1 resolved Jan 4, X2 Dec 5)
    // against sca's 1 (S2).
    expect(trendFromFrames(scans, base)[2]).toMatchObject({ date: "2026-01-05T00:00:00Z", open: 2 });
    expect(trendFromFrames(scaScans, scaBase)[1]).toMatchObject({ date: "2026-01-05T00:00:00Z", open: 1 });
  });

  it("trendFromFrames scoped == the same computation over the sca-only subset", () => {
    expect(trendFromFrames(scans, base, null, { scope: "sca" }))
      .toEqual(trendFromFrames(scaScans, scaBase));
  });

  it("openBySeverityTrend / openByGroupTrend / the two MTTR group trends agree", () => {
    expect(openBySeverityTrend(scans, base, null, { scope: "sca" }))
      .toEqual(openBySeverityTrend(scaScans, scaBase));
    expect(openByGroupTrend(scans, base, keyOf, ["web", "db"], { scope: "sca" }))
      .toEqual(openByGroupTrend(scaScans, scaBase, keyOf, ["web", "db"]));
    expect(medianMttrByGroupTrend(scans, base, keyOf, ["web", "db"], { scope: "sca" }))
      .toEqual(medianMttrByGroupTrend(scaScans, scaBase, keyOf, ["web", "db"]));
    expect(kmMedianByGroupTrend(scans, base, keyOf, ["web", "db"], { scope: "sca" }))
      .toEqual(kmMedianByGroupTrend(scaScans, scaBase, keyOf, ["web", "db"]));
  });

  it("trendFromBase agrees with and without backfill", () => {
    expect(trendFromBase(scans, base, null, { scope: "sca" }))
      .toEqual(trendFromBase(scaScans, scaBase));
    expect(trendFromBase(scans, base, null, { backfill: true, scope: "sca" }))
      .toEqual(trendFromBase(scaScans, scaBase, null, { backfill: true }));
    // And backfill actually did something here — S1 is first seen 2025-12-20, 12 days before
    // the first sca scan (Dec 20 .. Dec 31 = 12 synthetic midnights + Jan 1..Jan 5 real).
    const withBackfill = trendFromBase(scans, base, null, { backfill: true, scope: "sca" });
    expect(withBackfill.filter((p) => p.reconstructed).length).toBe(12);
    expect(withBackfill[0].date).toBe("2025-12-20T00:00:00Z");
  });

  it("the point-decorators scope their ROWS (the point dates come from the caller)", () => {
    expect(withKmMedian(points, base, null, { scope: "sca" }))
      .toEqual(withKmMedian(points, scaBase));
    expect(withOpenPastSla(points, base, null, "first_seen", { scope: "sca" }))
      .toEqual(withOpenPastSla(points, scaBase));
    expect(withSlaBurn(points, base, null, { scope: "sca" })).toEqual(withSlaBurn(points, scaBase));
    expect(cohortSlaAttainment(points, base, null, { scope: "sca" }))
      .toEqual(cohortSlaAttainment(points, scaBase));
    expect(withCoverageEfficiency(points, base, RULE, null, { scope: "sca" }))
      .toEqual(withCoverageEfficiency(points, scaBase, RULE));
    const d = Date.parse("2026-01-31T00:00:00Z");
    expect(kmMedianAsOf(base, null, d, { scope: "sca" })).toBe(kmMedianAsOf(scaBase, null, d));
  });

  it("and the decorators' scoped answers differ from the unscoped ones", () => {
    // open_past_sla as of Jan 31. Mixed: S2 (HIGH, target 14, age 37d) and X1 (LOW, target
    // 90, age 152d) are both open past target -> 2. sca-only: S2 alone -> 1.
    expect(withOpenPastSla(points, base)[1].open_past_sla).toBe(2);
    expect(withOpenPastSla(points, scaBase)[1].open_past_sla).toBe(1);
    // Cohort attainment as of Jan 31. Every deadline has passed, so all four rows are in the
    // mixed cohort: S1 resolved Jan 4 after its Dec 27 deadline (miss), S2 open past Jan 8
    // (miss), X1 open past Nov 30 (miss), X2 resolved Dec 5 before its Dec 9 deadline (hit)
    // -> 1/4 = 25.0. sca-only: 0 of 2 -> 0.0.
    expect(cohortSlaAttainment(points, base)[1].sla_attainment_pct).toBe(25);
    expect(cohortSlaAttainment(points, scaBase)[1].sla_attainment_pct).toBe(0);
  });

  it("an unknown scope yields an empty series rather than the whole register", () => {
    expect(trendFromFrames(scans, base, null, { scope: "sast" })).toEqual([]);
    expect(openBySeverityTrend(scans, base, null, { scope: "sast" })).toEqual([]);
    expect(trendFromBase(scans, base, null, { backfill: true, scope: "sast" })).toEqual([]);
  });

  it("omitting the scope is byte-identical to today (parity lock)", () => {
    expect(trendFromFrames(scans, base, null, {})).toEqual(trendFromFrames(scans, base));
    expect(withKmMedian(points, base, null, {})).toEqual(withKmMedian(points, base));
    expect(withSlaBurn(points, base, null, {})).toEqual(withSlaBurn(points, base));
  });

  describe("perScopeSeries / trendByScope", () => {
    it("builds each scope's series from one pass, equal to the per-scope filtered call", () => {
      const byScope = trendByScope(scans, base);
      for (const scope of SCOPES) {
        expect(byScope[scope], scope).toEqual(trendFromBase(scans, base, null, { scope }));
      }
      // sast has no rows here, so its series is empty — an explicit answer, not a missing key.
      expect(Object.keys(byScope).sort()).toEqual([...SCOPES].sort());
      expect(byScope.sast).toEqual([]);
      expect(byScope.sca.length).toBe(2);
      expect(byScope.secrets.length).toBe(2);
    });

    it("agrees with the filtered call under backfill too (synthetic rows, both paths)", () => {
      const byScope = trendByScope(scans, base, null, { backfill: true });
      for (const scope of SCOPES) {
        expect(byScope[scope], scope)
          .toEqual(trendFromBase(scans, base, null, { backfill: true, scope }));
      }
      expect(byScope.sca.filter((p) => p.reconstructed).length).toBe(12);
    });

    it("hands `compute` the already-partitioned scans and rows", () => {
      const seen: Record<string, [number, number]> = {};
      perScopeSeries(scans, base, (s, b, scope) => {
        seen[scope] = [s.length, b.length];
        return null;
      });
      expect(seen).toEqual({ sca: [2, 2], sast: [0, 0], secrets: [2, 2] });
    });

    it("drops rows carrying a scope outside SCOPES — corrupt data, not a fourth register", () => {
      const seen: Record<string, number> = {};
      perScopeSeries(
        [...scans, { ts: "2026-01-09T00:00:00Z", scope: "iac" }],
        [...base, { scope: "iac", severity: "HIGH", first_seen: "2026-01-01T00:00:00Z" }],
        (s, b, scope) => {
          seen[scope] = s.length + b.length;
          return null;
        },
      );
      expect(seen).toEqual({ sca: 4, sast: 0, secrets: 4 });
    });
  });
});
