"""Regenerate gas/src/server/wizQuery.ts from os_vulns.py QUERY/VARIABLES.

Run from the repo root: python gas/test/extract_query.py
"""
import copy
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import os_vulns

# THE ONE FILTER THIS REGISTER DOES NOT INHERIT.
#
# os_vulns.py carries `hasFix: true` and this register deliberately does not — see
# REMEDIATION_ROLLOUT_ISO and the BASE_FILTER_WORDS note in src/server/wizClient.ts, which
# states the divergence in prose. The drop USED TO LIVE ONLY IN THE GENERATED FILE, as a hand
# edit, under a header that tells the next reader to "regenerate rather than hand-editing".
# Following that instruction silently put the filter back, and a register scanning with
# `hasFix: true` stops seeing every finding with no vendor fix available — the awaiting-vendor-
# fix population this app measures on purpose. A divergence that only one of the two files
# knows about is not a divergence, it is a trap, so it is APPLIED HERE where regeneration
# reproduces it and a reader of either file can see it.
#
# Named as a tuple of keys rather than a rewritten VARIABLES literal so that anything else
# os_vulns.py adds to filterBy still arrives by default: the rule is "this register drops
# exactly these", not "this register restates the filter".
DROPPED_FILTERS = ("hasFix",)


def base_variables():
    """os_vulns.VARIABLES minus the filters this register does not inherit.

    Deep-copied before mutating: os_vulns.VARIABLES is module state, and `_page_variables`
    in that module deep-copies it per page for the same reason. Nothing else runs in this
    process today, which is exactly when an in-place edit survives long enough to be missed.
    """
    variables = copy.deepcopy(os_vulns.VARIABLES)
    filter_by = variables.get("filterBy")
    if isinstance(filter_by, dict):
        for key in DROPPED_FILTERS:
            filter_by.pop(key, None)
    return variables


out = f'''// Verbatim GraphQL query + baseline variables from os_vulns.py (generated by
// gas/test/extract_query.py — regenerate rather than hand-editing).
// projectIdV2 and severity are injected at request time from Script Properties /
// settings; the baseline VARIABLES here carry the fixed scope filters.
//
// NOT QUITE VERBATIM IN ONE PLACE, and the generator owns the difference rather than a hand
// edit here: os_vulns.py's `hasFix: true` is dropped (extract_query.py's DROPPED_FILTERS).
// See src/server/wizClient.ts's BASE_FILTER_WORDS note for why this register wants the
// findings that have no vendor fix yet.

export const QUERY = {json.dumps(os_vulns.QUERY)};

export const BASE_VARIABLES = {json.dumps(base_variables(), indent=2)} as const;

export const PAGE_SIZE = 500;
export const PAGE_SIZE_FALLBACK = 250;
export const MAX_PAGES = 1000;
'''
Path("gas/src/server/wizQuery.ts").write_text(out)
print("wrote gas/src/server/wizQuery.ts")
