"""Regenerate gas/src/server/wizQuery.ts from os_vulns.py QUERY/VARIABLES.

Run from the repo root: python gas/test/extract_query.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import os_vulns

out = f'''// Verbatim GraphQL query + baseline variables from os_vulns.py (generated by
// gas/test/extract_query.py — regenerate rather than hand-editing).
// projectIdV2 and severity are injected at request time from Script Properties /
// settings; the baseline VARIABLES here carry the fixed scope filters.

export const QUERY = {json.dumps(os_vulns.QUERY)};

export const BASE_VARIABLES = {json.dumps(os_vulns.VARIABLES, indent=2)} as const;

export const PAGE_SIZE = 500;
export const PAGE_SIZE_FALLBACK = 250;
export const MAX_PAGES = 1000;
'''
Path("gas/src/server/wizQuery.ts").write_text(out)
print("wrote gas/src/server/wizQuery.ts")
