// Censoring-aware time-to-remediation: the Kaplan–Meier survival estimator (curve, median,
// RMST mean) over ledger rows, treating still-open findings as right-censored rather than
// excluding them.
//
// D4 work package. Port of the Kaplan–Meier engine in gas/src/domain/remediation.ts
// (kmCurve, kmQuantileFromCurve, kmMedianFromCurve, kaplanMeier, and the kmMedian wrapper) —
// near-verbatim, since none of it touches a renamed column (severity/status/mttr_days/age_days
// are unchanged names in this register; the vuln_key→finding_key / cve→identifier /
// asset_*→repo_* renames land in other columns this file never reads).
//
// gas/'s remediation.ts also carries mttrPercentiles, resolutionBuckets, openPastSla(FromRecords),
// actionableView, awaitingVendorFix, the latency clocks, baseRowNoFix/recordNoFix, and the
// end-of-life predicates. NONE of those are ported here: this package is scoped to Kaplan–Meier
// only (RemediationRow is deliberately "only the fields KM needs"). isEndOfLifeName / recordEol
// are dropped outright — a code register has no host OS to be end-of-life. The rest is left for
// whichever later package owns it; several of them depend on modules that don't exist in this
// tree yet (metrics.ts's findCol/recordColumns, a REMEDIATION_ROLLOUT_ISO-equivalent boundary),
// so porting them here would either dangle or duplicate config this package doesn't own.
//
// Second oracle: brick/devsecops/metrics.py::kaplan_meier, itself "a port of gas/'s
// kaplanMeier" (see that function's own docstring) and exported to
// test/fixtures/brick/km.json (12 cases, generated by brick/devsecops/export_fixtures.py).
// test/remediation.test.ts asserts all 12 against this file, per severity AND OVERALL.

import { RESOLVED_STATUSES } from "./config";
import type { BaseRow } from "./ledgerTypes";
import { maxNum, mean, median } from "./util";

// Ledger rows carry all Kaplan–Meier signal in these four columns; kaplanMeier and its
// helpers read only this projection. `severity` rides along for callers that filter a
// register down to one severity (or OVERALL) before calling kaplanMeier — the estimator
// itself never reads it.
export type RemediationRow = Pick<BaseRow, "severity" | "status" | "mttr_days" | "age_days">;

// Same open/resolved status test the rest of the domain uses: a row is open unless its
// status is one of the remediated/closed set.
function isOpen(status: unknown): boolean {
  return !RESOLVED_STATUSES.has(String(status ?? "").toUpperCase());
}

// A resolved row's remediation time, or null when it has no finite mttr_days sample.
function resolvedMttr(row: RemediationRow): number | null {
  const m = row.mttr_days;
  return typeof m === "number" && Number.isFinite(m) ? m : null;
}

// An open row's age, or null when resolved / missing an age_days sample.
function openAge(row: RemediationRow): number | null {
  if (!isOpen(row.status)) return null;
  const a = row.age_days;
  return typeof a === "number" && Number.isFinite(a) ? a : null;
}

// One step of the Kaplan–Meier staircase: the survival S(t) after the drop at a distinct
// event time t, the risk-set size just before it, and how many events landed at it.
export interface KMPoint {
  t: number;
  s: number; // S(t) after the drop
  atRisk: number;
  events: number;
}

export interface KMResult {
  curve: KMPoint[]; // distinct event times ascending; the implicit anchor S(0)=1 is not stored
  median: number | null; // smallest event time with S(t) <= 0.5
  medianLowerBound: number | null; // when median is null: the max observed time (else null)
  mean: number | null; // restricted mean (RMST); null when there are no events
  restrictionTime: number | null; // τ = max observed time (events ∪ censored); null when empty
  meanTruncated: boolean; // S(τ) > 0 → survival hadn't reached 0, so RMST is a lower bound
  naiveMean: number | null; // mean of closed-only mttr_days (util.mean); null with no events
  naiveMedian: number | null; // linear-interp median of closed-only (util.median); null likewise
  events: number;
  censored: number;
  total: number;
}

/**
 * The Kaplan–Meier survival staircase over `events` (resolved times) against `times` (the
 * full risk set — every observation, event OR censored). One point per distinct event time
 * in ascending order: the risk set is `atRisk = #{time >= t}` over `times`, `events = #{event
 * times == t}`, and survival `S(t) = Π (1 − events/atRisk)`. A distinct event time whose risk
 * set has already emptied (atRisk 0, possible only if a censored obs equals it exactly) is
 * skipped, matching the original scalar estimator.
 */
export function kmCurve(events: number[], times: number[]): KMPoint[] {
  const curve: KMPoint[] = [];
  let s = 1;
  for (const t of [...new Set(events)].sort((a, b) => a - b)) {
    const atRisk = times.filter((x) => x >= t).length;
    if (atRisk === 0) continue;
    const d = events.filter((x) => x === t).length;
    s *= 1 - d / atRisk;
    curve.push({ t, s, atRisk, events: d });
  }
  return curve;
}

/**
 * The Kaplan–Meier q-th quantile off a curve: the smallest event time whose survival has fallen
 * to `S(t) <= 1 − q`. q=0.5 is the median (S ≤ 0.5); q=0.9 is the p90 (S ≤ 0.10 — the time by
 * which nine in ten findings are remediated). Censoring-aware, so the slow tail isn't biased low
 * by the fast-patched findings that close first. Null when survival never falls that far (too
 * much still open) or the curve is empty; the UI renders that null as "—". The inclusive
 * crossing makes an exact tie (e.g. S(t) hits 0.5 exactly) return that time.
 */
export function kmQuantileFromCurve(curve: KMPoint[], q: number): number | null {
  const threshold = 1 - q;
  for (const p of curve) if (p.s <= threshold) return p.t;
  return null;
}

/**
 * The Kaplan–Meier median off a curve: the smallest event time whose survival has fallen to
 * `S(t) <= 0.5` (the inclusive crossing makes an exact-0.5 tie return that time). Null when S
 * never reaches 0.5 (too much censoring — over half of findings still open) or the curve is
 * empty; the UI renders that null as "—" (or "> X d" against medianLowerBound).
 */
export function kmMedianFromCurve(curve: KMPoint[]): number | null {
  return kmQuantileFromCurve(curve, 0.5);
}

/**
 * Kaplan–Meier time-to-remediation, treating still-open findings as right-censored so the
 * estimate isn't biased low by fresh fast-patched findings. Events are resolved rows at
 * `t = mttr_days`; censored rows are open findings at `c = age_days` (rows with a null time
 * drop out of both). Returns the survival curve plus the two headline stats and the naive
 * closed-only comparison:
 *
 *  - `median`: smallest event time with S(t) <= 0.5 (see kmMedianFromCurve); null under heavy
 *    censoring, in which case `medianLowerBound` carries the max observed time so the UI can
 *    say "> X d" instead of "—" — the curve never reaches half, so the lower bound is published
 *    rather than a fabricated number. When the median is known, medianLowerBound is null.
 *  - `mean`: the restricted mean survival time (RMST) — the area under the KM curve out to the
 *    restriction time τ = `restrictionTime` (the max observed time, event OR censored). With
 *    curve points (t_1,S_1)…(t_m,S_m) and the anchor t_0=0, S_0=1:
 *      RMST = Σ_{k=1..m} S_{k-1}·(t_k − t_{k-1}) + S_m·(τ − t_m).
 *    `meanTruncated` is `S_m > 0` — survival hadn't reached 0 by τ, so the RMST is a lower
 *    bound (UI shows "≥"). Null (with median/restrictionTime handled below) when no events.
 *  - `naiveMean` / `naiveMedian`: the plain mean / linear-interpolation median over the
 *    closed-only mttr_days (util.mean / util.median), the biased comparison stats; both null
 *    when nothing resolved.
 *  - counts: `events` (resolved with a finite time), `censored` (open with a finite age), and
 *    `total` = their sum (null-time rows contribute to none).
 *
 * No events → `curve: []`, median/mean null, `medianLowerBound = restrictionTime = max(times)`
 * (null when there are no observations at all), meanTruncated false, counts still filled.
 */
export function kaplanMeier(rows: RemediationRow[]): KMResult {
  const events: number[] = []; // resolved times
  const censored: number[] = []; // open ages
  for (const row of rows) {
    const m = resolvedMttr(row);
    if (m !== null) {
      events.push(m);
      continue;
    }
    const c = openAge(row);
    if (c !== null) censored.push(c);
  }
  const times = events.concat(censored); // the risk set: every observation time
  const total = events.length + censored.length;
  // maxNum, not Math.max(...times): `times` holds one entry per finding (the whole risk set),
  // so spreading it into Math.max overflows the call stack on large registers.
  const restrictionTime = times.length ? maxNum(times) : null;
  const naiveMean = mean(events);
  const naiveMedian = median(events);

  if (!events.length) {
    // Empty or all-censored: no curve, no median/mean. The max observed time is the lower
    // bound the UI shows for the (unreached) median.
    return {
      curve: [],
      median: null,
      medianLowerBound: restrictionTime,
      mean: null,
      restrictionTime,
      meanTruncated: false,
      naiveMean,
      naiveMedian,
      events: 0,
      censored: censored.length,
      total,
    };
  }

  const curve = kmCurve(events, times);
  const median_ = kmMedianFromCurve(curve);

  // RMST = area under the staircase to τ: rectangles S_{k-1}·(t_k − t_{k-1}) plus the final
  // S_m·(τ − t_m). After the loop prevS is S_m and prevT is t_m.
  const tau = restrictionTime!; // events non-empty → times non-empty → τ is finite
  let rmst = 0;
  let prevT = 0;
  let prevS = 1;
  for (const p of curve) {
    rmst += prevS * (p.t - prevT);
    prevT = p.t;
    prevS = p.s;
  }
  rmst += prevS * (tau - prevT);

  return {
    curve,
    median: median_,
    medianLowerBound: median_ === null ? restrictionTime : null,
    mean: rmst,
    restrictionTime,
    meanTruncated: prevS > 0, // S(τ) = S_m > 0
    naiveMean,
    naiveMedian,
    events: events.length,
    censored: censored.length,
    total,
  };
}

/** Scalar KM median — the thin wrapper preserving the original call/test semantics. */
export function kmMedian(rows: RemediationRow[]): number | null {
  return kaplanMeier(rows).median;
}
