// Censoring-aware time-to-remediation: the Kaplan–Meier survival estimator (curve, median,
// RMST mean), MTTR percentiles, the resolution-time histogram, the open-past-SLA backlog, the
// actionable/latency clock projections, and the awaiting-vendor-fix / no-fix predicates — every
// non-Kaplan–Meier function gas/src/domain/remediation.ts carries, over ledger rows that treat
// still-open findings as right-censored rather than excluded.
//
// D4 (Kaplan–Meier only) landed first; this is D4b, the rest of the file. Port notes:
//
//   RENAMES (D4b rule 1) — vuln_key -> finding_key, cve -> identifier, asset_* -> repo_* per
//   sheetsDb.ts's TAB_HEADERS[TABS.ledger] (mirrored in ledgerTypes.ts). None of the ported
//   functions read a renamed column directly (they all read severity/status/mttr_days-shaped
//   projections), so the rename touches nothing here — findCol/recordColumns for
//   openPastSlaFromRecords now come from metrics.ts, which already exists in this tree (D4's
//   own header worried it might not; it does).
//
//   NO REMEDIATION_ROLLOUT_ISO / ROLLOUT_MS / published_date (D4b rule 2) — this is a fresh
//   register with no legacy hasFix-only ingestion to grandfather in, and its ledger carries no
//   published_date column (LedgerRow in ledgerTypes.ts has no CVE-publication timestamp — sca,
//   sast and secrets all lack one). Three DIVERGENCEs follow from that:
//     - latencyObservation drops the "legacy row assumed a fix" branch outright; a row with no
//       captured first_seen is simply unmeasured, same as it would be anyway.
//     - recordNoFix drops the pre-rollout "legacy = fixed" exemption; only the fixedVersion /
//       fixDate presence test remains.
//     - LatencyOrigin drops "disclosure" (the vendor's CVE-publication-to-fix wait): with no
//       published_date to anchor it to, that clock has no data source in this schema. Only
//       "detection" (first_seen-anchored) survives the port.
//
//   SCOPE IS PART OF THE KEY (D4b rules 3-4) — three registers share one ledger here, which
//   gas/'s single-register version never had to account for:
//     - awaitingVendorFix / baseRowNoFix / recordNoFix (rule 3): sast and secrets have no
//       vendor to wait on (ledgerTypes.ts's BaseRow comment: fix_available_at collapses to
//       first_seen for those two scopes), so a non-sca row is NEVER counted as awaiting a
//       vendor fix — even if a caller upstream forgot the fix-clock rule and left
//       awaiting_vendor_fix true on one. Those rows land in a separate `notApplicable` count
//       instead, pinned per scope in the tests below.
//     - mttrPercentiles / resolutionBuckets / openPastSla / awaitingVendorFix / latencyView
//       (rule 4): each takes an optional `opts.scope` to narrow to one register before
//       computing, filtered by filterScope() below. Follows metrics.summarize()'s own
//       convention (and lifecycle.mttrFromLedger's, which feeds it): a row whose `scope` was
//       never attached passes the filter rather than being silently dropped.
//
//   EOL (isEndOfLifeName / recordEol) is dropped outright, same call the D4 package already
//   made: a code register has no host OS to be end-of-life.
//
// Second oracle: brick/metrics.py::kaplan_meier, itself "a port of gas/'s
// kaplanMeier" (see that function's own docstring) and exported to
// test/fixtures/brick/km.json (12 cases, generated by brick/tools/export_fixtures.py).
// test/remediation.test.ts asserts all 12 against this file, per severity AND OVERALL. The
// functions D4b adds have no brick counterpart and are pinned by hand-written cases instead.

import { RESOLVED_STATUSES, SEVERITY_ORDER, SLA_TARGETS, type Scope } from "./config";
import type { BaseRow } from "./ledgerTypes";
import { findCol, recordColumns } from "./metrics";
import { normalizeSeverity } from "./severity";
import {
  countBelow,
  entryDaysFrom,
  maxNum,
  mean,
  median,
  parseTs,
  present,
  quantile,
  type Rec,
} from "./util";

const DAY_MS = 86_400_000;

// Ledger rows carry all Kaplan–Meier signal in these four columns; kaplanMeier and its
// helpers read only this projection. `severity` rides along for callers that filter a
// register down to one severity (or OVERALL) before calling kaplanMeier — the estimator
// itself never reads it.
//
// `entry_days` (MTTR delayed-entry package) is a fifth, OPTIONAL column: the age, on this
// row's own clock, at which the row entered observation — e.g. a finding already 90 days old
// the day this register started scanning enters at age 90, not age 0, because nothing before
// that day was ever observable. It is declared as its own intersected field rather than via
// `Pick<BaseRow, ...>` so this file does not have to wait on BaseRow gaining the column
// (a later package's job) to compile. Absent, null, or <= 0 all mean "no delayed entry" (0) —
// see `normalizedEntry` below, the single place that rule is applied.
export type RemediationRow = Pick<BaseRow, "severity" | "status" | "mttr_days" | "age_days"> & {
  entry_days?: number | null;
};

/**
 * Options that switch `kaplanMeier` from its original scalar-population estimator into the
 * delayed-entry / reliability-cut / RMST-horizon estimator this package adds. Deliberately a
 * single optional second argument rather than a new function: every existing call site
 * (`kaplanMeier(rows)`, no second argument) keeps its exact original behavior — see
 * `kaplanMeier`'s own docstring for the precise bit-identical guarantee this rests on.
 */
export interface KMOptions {
  /** RMST horizon τ, in days. Unset ⇒ τ = max observed time, same as the original estimator. */
  horizonDays?: number;
  /**
   * Apply the Gebski et al. (Int J Epidemiol 2018) sensitivity-index reliability cut and report
   * it via `reliableUntil`. Unset/false ⇒ no cut: `curve`/`median`/`q25`/`q75`/RMST are computed
   * over the WHOLE curve, same as before this package (still delayed-entry-aware if any row
   * carries `entry_days`, but never truncated for reliability).
   */
  minRisk?: boolean;
}

// Same open/resolved status test the rest of the domain uses: a row is open unless its
// status is one of the remediated/closed set.
function isOpen(status: unknown): boolean {
  return !RESOLVED_STATUSES.has(String(status ?? "").toUpperCase());
}

// A resolved row's remediation time, or null when it has no finite mttr_days sample.
function resolvedMttr(row: RemediationRow): number | null {
  const m = row.mttr_days;
  return typeof m === "number" && Number.isFinite(m) ? m : null;
}

// An open row's age, or null when resolved / missing an age_days sample.
function openAge(row: RemediationRow): number | null {
  if (!isOpen(row.status)) return null;
  const a = row.age_days;
  return typeof a === "number" && Number.isFinite(a) ? a : null;
}

// One step of the Kaplan–Meier staircase: the survival S(t) after the drop at a distinct
// event time t, the risk-set size just before it, and how many events landed at it.
export interface KMPoint {
  t: number;
  s: number; // S(t) after the drop
  atRisk: number;
  events: number;
}

export interface KMResult {
  curve: KMPoint[]; // distinct event times ascending; the implicit anchor S(0)=1 is not stored
  median: number | null; // smallest event time with S(t) <= 0.5
  medianLowerBound: number | null; // when median is null: the max observed time (else null)
  mean: number | null; // restricted mean (RMST); null when there are no events
  restrictionTime: number | null; // τ = max observed time (events ∪ censored); null when empty
  meanTruncated: boolean; // S(τ) > 0 → survival hadn't reached 0, so RMST is a lower bound
  naiveMean: number | null; // mean of closed-only mttr_days (util.mean); null with no events
  naiveMedian: number | null; // linear-interp median of closed-only (util.median); null likewise
  events: number;
  censored: number;
  total: number;

  // ----------------------------------------------------------- delayed-entry package additions
  //
  // Every field below is OPTIONAL and, on the ORIGINAL one-argument call shape
  // (`kaplanMeier(rows)`, no `entry_days` on any row), is simply ABSENT from the returned
  // object — not present-and-null, not present-and-zero, genuinely not a key on the result —
  // so every pre-existing `toEqual({...11 fields...})` assertion in test/remediation.test.ts
  // still matches exactly (vitest's `toEqual` treats an absent key and an `undefined`-valued
  // key alike, but NOT an absent key and a `null`- or `0`-valued one — verified directly before
  // relying on it here). Call with a `KMOptions` (even `{}`) or put `entry_days` on a row and
  // every field below is populated for real, per its own note.

  /** The time by which 25% of findings were remediated (kmQuantileFromCurve(cutCurve, 0.25)). */
  q25?: number | null;
  /** The time by which 75% of findings were remediated (kmQuantileFromCurve(cutCurve, 0.75)). */
  q75?: number | null;
  /**
   * The last event time the Gebski reliability cut still trusts (see kaplanMeier's docstring).
   * `curve`/`median`/`q25`/`q75` are all read off the curve cut at this point. Null either
   * because `opts.minRisk` was not requested (no cut — the WHOLE curve ships) or because the
   * very first event already fails the reliability test (nothing is trustworthy).
   */
  reliableUntil?: number | null;
  /**
   * Rows dropped entirely because their own exit fell at-or-before their own entry — a finding
   * that resolved (or was already this old) before this register could have observed it. Never
   * an event, a censored observation, or part of any risk set. 0 (not absent) whenever the
   * extended estimator ran, even if nothing was actually excluded.
   */
  excludedPreEntry?: number;
  /**
   * The max exit time across the observed (post pre-entry-exclusion) population — what
   * `restrictionTime` unconditionally meant before this package let τ be capped by
   * `opts.horizonDays` or the reliability cut. `restrictionTime` itself now reports τ; this
   * field keeps the uncapped figure available (e.g. for "≥ N d still open" phrasing).
   */
  maxObserved?: number | null;

  // --------------------------------------------------------------- row-accounting package
  //
  // The estimator used to have THREE silent ways for a row to vanish without ever being
  // counted anywhere: a row with neither a resolved time nor an open age fell out of the loop
  // below with nothing incremented; an event past the reliability cut disappeared from `curve`
  // with nothing saying so; and a finding that entered the risk set late (the onboarding
  // backlog `entry_days` exists for) was invisible in every published count. These five fields
  // make every row this estimator was HANDED reach exactly one bucket, so
  // `rowsIn === events + censored + excludedPreEntry + noClock` always — see `noClock`'s own
  // comment for why `eventsPastCut` does not appear in that identity even though it is a real
  // partition of `events`. `test/kmDelayedEntry.test.ts`'s "row accounting" block pins it.

  /** Every row `kaplanMeier` was handed, before any exclusion — the header total the UI's
   *  accounting block reconciles every other field here against. */
  rowsIn?: number;
  /**
   * Rows where NEITHER `resolvedMttr` (a finite `mttr_days`) NOR `openAge` (an open row's
   * finite `age_days`) produced a reading — a resolved row with no captured remediation time,
   * or an open row with no captured age. These used to fall out of the loop below with nothing
   * incremented anywhere: not an event, not censored, not `excludedPreEntry` (which only counts
   * rows that DID have a reading, just one at-or-before their own entry). 0 whenever the
   * extended estimator ran and every row had a readable clock.
   */
  noClock?: number;
  /**
   * Of `events` (this result's own field — see its call site for which population that already
   * is: every row whose exit is a genuine post-entry event, REGARDLESS of the reliability cut),
   * the count whose time `t` fell PAST `reliableUntil` — a real fix this register observed and
   * excluded from the median because too little of the risk set remained to trust the curve out
   * that far. 0 when `opts.minRisk` was not requested (nothing is cut) or when every event
   * landed inside the cut.
   *
   * `events` already means "every observed event, pre-cut" (kaplanMeierExtended never narrows
   * it to the cut curve, for backward compatibility with every existing reader), so the events
   * actually USED by the shipped curve are `events − eventsPastCut`, computed by the one reader
   * that needs that split (the accounting block) rather than shipped as a seventh count nothing
   * else reads yet — which is also why `eventsPastCut` does not get its own term in the
   * `rowsIn` identity above: `events` already carries both eventsUsed and eventsPastCut summed.
   */
  eventsPastCut?: number;
  /** Of the rows that survived pre-entry exclusion (became an event or a censored
   *  observation), how many had `entry_days > 0` — the onboarding backlog: findings already
   *  open, on their own clock, the day this register started watching. 0 when nothing entered
   *  late. */
  lateEntrants?: number;
  /** The median `entry_days` among `lateEntrants`, in days — "half the backlog was already at
   *  least this old when we started watching". Null when `lateEntrants === 0` (nothing to take
   *  a median of, not a measured zero). */
  lateEntryMedianAge?: number | null;
}

/**
 * The Kaplan–Meier survival staircase over `events` (resolved times) against `times` (the
 * full risk set — every observation, event OR censored). One point per distinct event time
 * in ascending order: the risk set is `atRisk = #{time >= t}` over `times`, `events = #{event
 * times == t}`, and survival `S(t) = Π (1 − events/atRisk)`. A distinct event time whose risk
 * set has already emptied (atRisk 0, possible only if a censored obs equals it exactly) is
 * skipped, matching the original scalar estimator.
 */
export function kmCurve(events: number[], times: number[]): KMPoint[] {
  // ONE SORT AND ONE SWEEP, NOT A SCAN PER EVENT TIME. This used to re-filter both arrays for
  // every distinct event time — O(distinct × n) — and `mttr_days` is fractional, so on a real
  // register the distinct count is in the thousands. gas/ carried the same loop and measured
  // it in production at 19 s per curve over 58,679 rows (#320); here it sits under
  // `kaplanMeier`, i.e. the MTTR hero on the Executive and MTTR pages.
  //
  // THE ANSWER IS BIT-FOR-BIT THE OLD ONE, which is why the product below still runs over the
  // distinct event times in ascending order — S(t) is a running product, and a different order
  // of the same factors can land one ULP apart. `atRisk` is "times >= t" and `d` is
  // "events === t", read off the sorted arrays instead of counted by a scan. NaN is dropped
  // from both up front: it never satisfied `>=` or `===` in the old filters, so it was never
  // at risk and never an event, and left in it would break the sort's ordering.
  // test/kmCurveSweep.test.ts keeps the old loop verbatim as the oracle.
  const ev = events.filter((x) => !Number.isNaN(x)).sort((a, b) => a - b);
  const ts = times.filter((x) => !Number.isNaN(x)).sort((a, b) => a - b);
  const curve: KMPoint[] = [];
  let s = 1;
  let j = 0; // first index of `ts` with ts[j] >= t
  for (let i = 0; i < ev.length; ) {
    // `+ 0` turns -0 into +0, as the old `new Set(events)` did (a Set stores -0 as +0).
    const t = ev[i]! + 0;
    let d = 0;
    while (i < ev.length && ev[i] === t) {
      d += 1;
      i += 1;
    }
    while (j < ts.length && ts[j]! < t) j += 1;
    const atRisk = ts.length - j;
    if (atRisk === 0) continue;
    s *= 1 - d / atRisk;
    curve.push({ t, s, atRisk, events: d });
  }
  return curve;
}

/** One observation for `kmCurveEntry`: its exit time `t` (event OR censoring time, matching
 * `kmCurve`'s own `events`/`times` numbers) and the age at which it entered observation. */
export interface KMObservation {
  t: number;
  entry: number;
}

/**
 * `kmCurve`'s delayed-entry (left-truncation) sibling: the risk set at event time t is
 * `#{obs : entry < t <= exit}` rather than `kmCurve`'s `#{exit >= t}` — a finding only counts
 * as at risk once this register could have observed it (its own entry age), not from t=0. The
 * `entry < t` side is STRICT: a row whose entry lands exactly on another row's event time has
 * not yet entered as of that instant (test/kmDelayedEntry.test.ts pins this boundary by hand).
 * `kmCurve` itself is untouched — this is an addition, not a rewrite, so trend.ts's existing
 * calls and every pre-delayed-entry test keep reading the original function.
 *
 * O(n log n), same complexity class as `kmCurve`'s own sort, and NOT the O(n · distinct-times)
 * a delayed-entry port of `kmCurve`'s per-event `.filter()` would cost: every observation
 * carries two numbers now (entry and exit) rather than one, so a per-event linear scan over a
 * 50k-row register would double the cost `kmCurve` already pays. Instead:
 *   atRisk(t) = #{entry < t} − #{exit < t}
 * which holds because every observation here already has entry < exit (kaplanMeier's caller
 * drops exit <= entry rows before this function ever sees them — see `excludedPreEntry`), so
 * `exit < t` already implies `entry < exit < t`, making the two counts share no observation
 * that needs correcting for.  Each count is a binary search (`util.countBelow`) over a SORTED
 * copy of just the entries or just the exits, so `events` distinct times cost
 * O(events · log n) atop the O(n log n) sort — table-stakes for a register-scale curve.
 */
export function kmCurveEntry(events: KMObservation[], times: KMObservation[]): KMPoint[] {
  const eventCounts = new Map<number, number>();
  for (const e of events) eventCounts.set(e.t, (eventCounts.get(e.t) ?? 0) + 1);
  const distinctEventTimes = [...eventCounts.keys()].sort((a, b) => a - b);

  const sortedEntries = times.map((o) => o.entry).sort((a, b) => a - b);
  const sortedExits = times.map((o) => o.t).sort((a, b) => a - b);

  const curve: KMPoint[] = [];
  let s = 1;
  for (const t of distinctEventTimes) {
    const atRisk = countBelow(sortedEntries, t) - countBelow(sortedExits, t);
    if (atRisk <= 0) continue; // mirrors kmCurve's own atRisk === 0 skip
    const d = eventCounts.get(t)!;
    s *= 1 - d / atRisk;
    curve.push({ t, s, atRisk, events: d });
  }
  return curve;
}

/**
 * How far above a threshold a survival value may sit and still count as having crossed it.
 *
 * S(t) IS A RUNNING PRODUCT, so a curve that mathematically lands ON a threshold can land one
 * ULP above it. CLAUDE.md's own example, pinned by `test/kmCrossing.test.ts`: ten events at
 * times 1..10 with no censoring gives S(9) = 0.10000000000000002, while the p90 threshold
 * `1 - 0.9` evaluates to 0.09999999999999998 — two separate representation errors leaning
 * opposite ways — so a bare `s <= threshold` skips t=9 and reports 10. The answer would then
 * depend on the ORDER the products accumulated in, which is not a property any published
 * figure may have.
 */
export const CROSSING_EPSILON = 1e-9;

/**
 * The Kaplan–Meier q-th quantile off a curve: the smallest event time whose survival has fallen
 * to `S(t) <= 1 − q`, within CROSSING_EPSILON. q=0.5 is the median (S ≤ 0.5); q=0.9 is the p90
 * (S ≤ 0.10 — the time by which nine in ten findings are remediated). Censoring-aware, so the
 * slow tail isn't biased low by the fast-patched findings that close first. Null when survival
 * never falls that far (too much still open) or the curve is empty; the UI renders that null as
 * "—". The inclusive crossing makes an exact tie (e.g. S(t) hits 0.5 exactly) return that time.
 */
export function kmQuantileFromCurve(curve: KMPoint[], q: number): number | null {
  const threshold = 1 - q;
  for (const p of curve) if (p.s <= threshold + CROSSING_EPSILON) return p.t;
  return null;
}

/**
 * The Kaplan–Meier median off a curve: the smallest event time whose survival has fallen to
 * `S(t) <= 0.5` (the inclusive crossing makes an exact-0.5 tie return that time). Null when S
 * never reaches 0.5 (too much censoring — over half of findings still open) or the curve is
 * empty; the UI renders that null as "—" (or "> X d" against medianLowerBound).
 */
export function kmMedianFromCurve(curve: KMPoint[]): number | null {
  return kmQuantileFromCurve(curve, 0.5);
}

/**
 * Kaplan–Meier time-to-remediation, treating still-open findings as right-censored so the
 * estimate isn't biased low by fresh fast-patched findings. Events are resolved rows at
 * `t = mttr_days`; censored rows are open findings at `c = age_days` (rows with a null time
 * drop out of both). Returns the survival curve plus the two headline stats and the naive
 * closed-only comparison:
 *
 *  - `median`: smallest event time with S(t) <= 0.5 (see kmMedianFromCurve); null under heavy
 *    censoring, in which case `medianLowerBound` carries the max observed time so the UI can
 *    say "> X d" instead of "—" — the curve never reaches half, so the lower bound is published
 *    rather than a fabricated number. When the median is known, medianLowerBound is null.
 *  - `mean`: the restricted mean survival time (RMST) — the area under the KM curve out to the
 *    restriction time τ = `restrictionTime` (the max observed time, event OR censored). With
 *    curve points (t_1,S_1)…(t_m,S_m) and the anchor t_0=0, S_0=1:
 *      RMST = Σ_{k=1..m} S_{k-1}·(t_k − t_{k-1}) + S_m·(τ − t_m).
 *    `meanTruncated` is `S_m > 0` — survival hadn't reached 0 by τ, so the RMST is a lower
 *    bound (UI shows "≥"). Null (with median/restrictionTime handled below) when no events.
 *  - `naiveMean` / `naiveMedian`: the plain mean / linear-interpolation median over the
 *    closed-only mttr_days (util.mean / util.median), the biased comparison stats; both null
 *    when nothing resolved.
 *  - counts: `events` (resolved with a finite time), `censored` (open with a finite age), and
 *    `total` = their sum (null-time rows contribute to none).
 *
 * No events → `curve: []`, median/mean null, `medianLowerBound = restrictionTime = max(times)`
 * (null when there are no observations at all), meanTruncated false, counts still filled.
 *
 * DELAYED ENTRY / RELIABILITY CUT / RMST HORIZON (this package): `kaplanMeier(rows)` — this
 * EXACT one-argument shape, on rows carrying no `entry_days` — is guaranteed bit-identical to
 * every line above and to every pre-existing caller, dispatching straight to
 * `kaplanMeierLegacy`, the original function unchanged. That guarantee is deliberately narrow
 * (bullet 2 of the plan this shipped against): the moment a row carries a positive `entry_days`
 * OR the caller passes a second argument (even `{}`), `kaplanMeierExtended` runs instead and:
 *
 *   - treats each row as entering observation at `entry_days` on ITS OWN clock rather than at
 *     0 — a row whose exit falls at-or-before its own entry was never observable at all and is
 *     dropped outright (events/censored/risk-set), counted instead in `excludedPreEntry`;
 *   - computes the risk set with `kmCurveEntry` (entry < t <= exit) instead of `kmCurve`;
 *   - when `opts.minRisk`, cuts the curve at the Gebski et al. (Int J Epidemiol 2018)
 *     reliability boundary and reads `median`/`q25`/`q75` off the CUT curve only (see
 *     `reliableUntilFromCurve`);
 *   - when `opts.horizonDays`, restricts RMST to τ = min(horizonDays, the reliability cut (if
 *     any) else the max observed time), reporting that τ as `restrictionTime` and keeping the
 *     uncapped figure in the new `maxObserved` field.
 *
 * See `KMOptions`, `kmCurveEntry`, `reliableUntilFromCurve` and the new KMResult fields for the
 * per-mechanism detail; `test/kmDelayedEntry.test.ts` pins all of it, including a randomized
 * "no entry, no opts" property test run against a literal copy of the pre-package algorithm.
 *
 * ROW ACCOUNTING (row-accounting package, extended path only): `rowsIn` (every row handed in),
 * `noClock` (neither a resolved time nor an open age — the third silent drop this closes),
 * `eventsPastCut` (real events excluded by the reliability cut), `lateEntrants` and
 * `lateEntryMedianAge` (the onboarding backlog: rows already old on their own clock when this
 * register started watching) together make `rowsIn === events + censored + excludedPreEntry +
 * noClock` hold exactly — see `noClock`'s own KMResult comment for the identity and why
 * `eventsPastCut` is not a separate term in it. Absent from `kaplanMeierLegacy`'s return, same
 * as `q25`/`reliableUntil`.
 */
export function kaplanMeier(rows: RemediationRow[], opts?: KMOptions): KMResult {
  if (opts === undefined && !rows.some((r) => normalizedEntry(r) > 0)) {
    return kaplanMeierLegacy(rows);
  }
  return kaplanMeierExtended(rows, opts);
}

/**
 * The estimator as it existed before this package, PRESERVED VERBATIM (not merely "equivalent
 * to") — the dispatch in `kaplanMeier` routes here whenever nothing about the call could
 * possibly invoke delayed entry, so this is what makes that path bit-identical by construction
 * rather than by argument. Do not "clean this up" into `kaplanMeierExtended` — that is exactly
 * the refactor this split exists to avoid needing to prove safe.
 */
function kaplanMeierLegacy(rows: RemediationRow[]): KMResult {
  const events: number[] = []; // resolved times
  const censored: number[] = []; // open ages
  for (const row of rows) {
    const m = resolvedMttr(row);
    if (m !== null) {
      events.push(m);
      continue;
    }
    const c = openAge(row);
    if (c !== null) censored.push(c);
  }
  const times = events.concat(censored); // the risk set: every observation time
  const total = events.length + censored.length;
  // maxNum, not Math.max(...times): `times` holds one entry per finding (the whole risk set),
  // so spreading it into Math.max overflows the call stack on large registers.
  const restrictionTime = times.length ? maxNum(times) : null;
  const naiveMean = mean(events);
  const naiveMedian = median(events);

  if (!events.length) {
    // Empty or all-censored: no curve, no median/mean. The max observed time is the lower
    // bound the UI shows for the (unreached) median.
    return {
      curve: [],
      median: null,
      medianLowerBound: restrictionTime,
      mean: null,
      restrictionTime,
      meanTruncated: false,
      naiveMean,
      naiveMedian,
      events: 0,
      censored: censored.length,
      total,
    };
  }

  const curve = kmCurve(events, times);
  const median_ = kmMedianFromCurve(curve);

  // RMST = area under the staircase to τ: rectangles S_{k-1}·(t_k − t_{k-1}) plus the final
  // S_m·(τ − t_m). After the loop prevS is S_m and prevT is t_m.
  const tau = restrictionTime!; // events non-empty → times non-empty → τ is finite
  let rmst = 0;
  let prevT = 0;
  let prevS = 1;
  for (const p of curve) {
    rmst += prevS * (p.t - prevT);
    prevT = p.t;
    prevS = p.s;
  }
  rmst += prevS * (tau - prevT);

  return {
    curve,
    median: median_,
    medianLowerBound: median_ === null ? restrictionTime : null,
    mean: rmst,
    restrictionTime,
    meanTruncated: prevS > 0, // S(τ) = S_m > 0
    naiveMean,
    naiveMedian,
    events: events.length,
    censored: censored.length,
    total,
  };
}

// entry_days's normalization rule (D-entry bullet 1): absent, null, non-finite, or <= 0 all
// mean "no delayed entry" — a plain 0. The single place that rule is applied.
function normalizedEntry(row: RemediationRow): number {
  const e = row.entry_days;
  return typeof e === "number" && Number.isFinite(e) && e > 0 ? e : 0;
}

/**
 * RMST integration shared by both the pre-cut and post-cut curve: the area under the KM
 * staircase from 0 to τ. Written once so `kaplanMeierExtended` never has to choose between
 * "integrate the full curve" and "integrate the cut curve" — it always integrates whichever
 * curve it is handed, and callers decide which curve and which τ that is. Works whether τ lands
 * exactly on a curve point, strictly between two, or past the last one (the final rectangle
 * just runs longer) — same shape as kaplanMeierLegacy's own RMST loop, deliberately, since
 * that loop is exactly this function called with (curve, restrictionTime).
 */
function rmstToTau(curve: KMPoint[], tau: number): { rmst: number; sAtTau: number } {
  let rmst = 0;
  let prevT = 0;
  let prevS = 1;
  for (const p of curve) {
    if (p.t > tau) break; // curve is ascending; nothing past τ contributes
    rmst += prevS * (p.t - prevT);
    prevT = p.t;
    prevS = p.s;
  }
  rmst += prevS * (tau - prevT);
  return { rmst, sAtTau: prevS };
}

/**
 * The Gebski et al. (Int J Epidemiol 2018) sensitivity-index reliability cut: a KM curve is
 * only as trustworthy as its risk set is large relative to how far survival has already
 * fallen, because ONE MORE EVENT moves S(t) by S(t⁻)/n(t) — the size of the next possible drop.
 * Capping that drop at 2 percentage points (0.02) means requiring
 *   n(t) >= S(t⁻) / 0.02 = 50 · S(t⁻),
 * with an absolute floor of 10 so a curve that has already fallen very low (where 50·S is tiny)
 * doesn't get called "reliable" on a near-empty risk set. `S(t⁻)` is the survival level GOING
 * INTO event t — the previous curve point's `s`, or 1 for the first event (nothing has dropped
 * yet).
 *
 * Walks the curve ascending and returns the LAST event time before the first failure: null if
 * the very first event already fails (nothing on the curve is trustworthy), or the final event
 * time if nothing ever fails. `kaplanMeierExtended` cuts the shipped curve here and reads
 * median/q25/q75 off the cut curve only — see its own comment for why.
 *
 * Exported for `trend.ts`'s KM replays (`kmMedianAsOf` / `withKmMedian` /
 * `kmMedianByGroupTrend`), which build their own `KMPoint[]` curves via `kmCurveEntry` (one
 * per as-of date, rather than one per current-state call) and need the identical cut applied
 * so a week-over-week comparison is not reading a cut current figure against an uncut replay.
 */
export function reliableUntilFromCurve(curve: KMPoint[]): number | null {
  let prevS = 1;
  let lastReliable: number | null = null;
  for (const p of curve) {
    if (p.atRisk < Math.max(10, 50 * prevS)) return lastReliable;
    lastReliable = p.t;
    prevS = p.s;
  }
  return lastReliable;
}

/**
 * The delayed-entry / reliability-cut / RMST-horizon estimator — see `kaplanMeier`'s own
 * docstring for the contract. Structurally this mirrors `kaplanMeierLegacy` closely on purpose
 * (same event/censored split, same no-events early return, same RMST shape via `rmstToTau`) so
 * the two are easy to read against each other; the differences are exactly the four bullets
 * `kaplanMeier`'s docstring lists.
 */
function kaplanMeierExtended(rows: RemediationRow[], opts: KMOptions | undefined): KMResult {
  const rowsIn = rows.length;
  const events: { t: number; entry: number }[] = [];
  const censored: { t: number; entry: number }[] = [];
  let excludedPreEntry = 0;
  // Rows with neither a resolved time nor an open age — the third silent hole this package
  // closes. `lateEntryAges` collects the entry of every row that DID survive (event or
  // censored) with `entry_days > 0`, for `lateEntrants`/`lateEntryMedianAge` below.
  let noClock = 0;
  const lateEntryAges: number[] = [];
  for (const row of rows) {
    const entry = normalizedEntry(row);
    const m = resolvedMttr(row);
    if (m !== null) {
      if (m <= entry) {
        excludedPreEntry += 1; // resolved before this register could have observed it
      } else {
        events.push({ t: m, entry });
        if (entry > 0) lateEntryAges.push(entry);
      }
      continue;
    }
    const c = openAge(row);
    if (c !== null) {
      if (c <= entry) {
        excludedPreEntry += 1; // already this old, on this clock, before entry
      } else {
        censored.push({ t: c, entry });
        if (entry > 0) lateEntryAges.push(entry);
      }
    } else {
      noClock += 1; // neither resolvedMttr nor openAge produced a reading — dropped, uncounted
    }
  }
  const lateEntrants = lateEntryAges.length;
  const lateEntryMedianAge = lateEntrants > 0 ? median(lateEntryAges) : null;

  const total = events.length + censored.length;
  const obsTimes = events.concat(censored).map((o) => o.t);
  // maxNum, not Math.max(...arr) — same register-scale reason kaplanMeierLegacy avoids the
  // spread (see its own comment).
  const maxObserved = obsTimes.length ? maxNum(obsTimes) : null;
  // Naive stats are computed over the SAME post-exclusion event population as the KM estimate:
  // an excludedPreEntry row was never observed by this register at all, so it can no more
  // contribute to the naive average than to the censoring-aware one.
  const eventTimes = events.map((e) => e.t);
  const naiveMean = mean(eventTimes);
  const naiveMedian = median(eventTimes);

  if (!events.length) {
    // No observed events (all-censored, all-excluded, or empty): no curve, no median/mean/
    // quantiles, same shape kaplanMeierLegacy returns in this case — including restrictionTime
    // staying at the UNCAPPED max observed time rather than any horizon, because there is no
    // RMST here to cap in the first place.
    return {
      curve: [],
      median: null,
      medianLowerBound: maxObserved,
      mean: null,
      restrictionTime: maxObserved,
      meanTruncated: false,
      naiveMean,
      naiveMedian,
      events: 0,
      censored: censored.length,
      total,
      q25: null,
      q75: null,
      reliableUntil: null,
      excludedPreEntry,
      maxObserved,
      rowsIn,
      noClock,
      eventsPastCut: 0, // no events at all -> nothing to have been cut past
      lateEntrants,
      lateEntryMedianAge,
    };
  }

  const fullCurve = kmCurveEntry(events, events.concat(censored));

  let reliableUntil: number | null = null;
  let curve = fullCurve;
  if (opts?.minRisk) {
    reliableUntil = reliableUntilFromCurve(fullCurve);
    // First event already unreliable -> nothing on the curve is trustworthy; ship none of it.
    curve = reliableUntil === null ? [] : fullCurve.filter((p) => p.t <= reliableUntil!);
  }
  // `eventsPastCut`: see its own KMResult comment. `opts?.minRisk` false means no cut ran at
  // all — 0 by definition. `reliableUntil === null` under `minRisk` means the FIRST event
  // already failed reliability, so nothing at all is trustworthy and every event is "past the
  // cut" (curve is []). Otherwise it is exactly the raw events whose time landed after the cut.
  const eventsPastCut =
    !opts?.minRisk ? 0
    : reliableUntil === null ? events.length
    : events.filter((e) => e.t > reliableUntil!).length;

  const median_ = kmMedianFromCurve(curve);
  const q25 = kmQuantileFromCurve(curve, 0.25);
  const q75 = kmQuantileFromCurve(curve, 0.75);

  // τ: capped to the horizon AND to the reliability cut (if either applies), else the max
  // observed time — same "τ = max observed" legacy default when neither opts field is set.
  const tau =
    opts?.horizonDays !== undefined
      ? Math.min(opts.horizonDays, reliableUntil ?? maxObserved!)
      : maxObserved!;
  const { rmst, sAtTau } = rmstToTau(curve, tau);

  const medianLowerBound =
    median_ !== null ? null
    : opts?.minRisk ? (reliableUntil ?? maxObserved)
    : maxObserved;

  return {
    curve,
    median: median_,
    medianLowerBound,
    mean: rmst,
    restrictionTime: tau,
    meanTruncated: sAtTau > 0,
    naiveMean,
    naiveMedian,
    events: events.length,
    censored: censored.length,
    total,
    q25,
    q75,
    reliableUntil,
    excludedPreEntry,
    maxObserved,
    rowsIn,
    noClock,
    eventsPastCut,
    lateEntrants,
    lateEntryMedianAge,
  };
}

/** Scalar KM median — the thin wrapper preserving the original call/test semantics. */
export function kmMedian(rows: RemediationRow[]): number | null {
  return kaplanMeier(rows).median;
}

// --------------------------------------------------------------------- opts.scope filter

/**
 * `opts.scope` filter shared by mttrPercentiles / resolutionBuckets / openPastSla /
 * awaitingVendorFix / latencyView (D4b rule 4): narrows the population to one register before
 * computing. Follows metrics.summarize()'s convention — a row whose `scope` was never attached
 * passes through untouched (present-but-wrong-scope is excluded; absent-scope survives) rather
 * than being silently dropped, since several callers (this file's own tests included) still
 * build rows with no scope tag at all.
 */
function filterScope<T extends { scope?: Scope }>(rows: T[], scope?: Scope): T[] {
  return scope ? rows.filter((r) => r.scope === undefined || r.scope === scope) : rows;
}

// --------------------------------------------------------------------- resolution histogram

// Time-to-resolve histogram edges (days) and their five bucket labels — bucketed with `<=`
// edges, the same convention gas/'s insights.ageBuckets used.
export const RESOLUTION_BUCKET_EDGES = [1, 7, 30, 90] as const;
export const RESOLUTION_BUCKET_LABELS = ["≤1d", "2–7d", "8–30d", "31–90d", "90+d"] as const;

/** RemediationRow with an optional scope tag — the row shape the opts.scope filters take. */
type ScopedRemediationRow = RemediationRow & { scope?: Scope };

export interface Pctile {
  p50: number | null;
  p90: number | null;
  count: number;
}

export interface MttrPercentiles {
  perSev: Record<string, Pctile>;
  overall: Pctile;
}

/**
 * Median and p90 of resolved lifecycles (finite mttr_days), per severity + overall — the tail
 * percentile the ~1-day median hides. Percentiles are the same linear-interpolation `quantile`
 * util.ts's other parity-tested reducers use; null when no resolved sample. `opts.scope`
 * narrows to one register before computing (see filterScope's note).
 */
export function mttrPercentiles(
  rows: ScopedRemediationRow[],
  opts?: { scope?: Scope },
): MttrPercentiles {
  const filtered = filterScope(rows, opts?.scope);
  const bySev: Record<string, number[]> = {};
  const all: number[] = [];
  for (const row of filtered) {
    const m = resolvedMttr(row);
    if (m === null) continue;
    const s = normalizeSeverity(row.severity);
    (bySev[s] ?? (bySev[s] = [])).push(m);
    all.push(m);
  }
  const perSev: Record<string, Pctile> = {};
  for (const s of SEVERITY_ORDER) {
    const vals = bySev[s];
    if (!vals) continue;
    perSev[s] = { p50: quantile(vals, 0.5), p90: quantile(vals, 0.9), count: vals.length };
  }
  return {
    perSev,
    overall: { p50: quantile(all, 0.5), p90: quantile(all, 0.9), count: all.length },
  };
}

export interface ResolutionBuckets {
  perSev: Record<string, [number, number, number, number, number]>;
  labels: typeof RESOLUTION_BUCKET_LABELS;
  total: number;
}

/**
 * Time-to-resolve histogram: bucket resolved lifecycles by mttr_days into
 * ≤1d / 2–7d / 8–30d / 31–90d / 90+d with `<=` edges, split per severity. perSev bucket counts
 * sum to `total`; open / null-mttr rows are excluded. Insertion-order keys, so it drops into
 * the same stacked-bar chart shape as an age histogram. `opts.scope` narrows to one register
 * before computing.
 */
export function resolutionBuckets(
  rows: ScopedRemediationRow[],
  opts?: { scope?: Scope },
): ResolutionBuckets {
  const filtered = filterScope(rows, opts?.scope);
  const perSev: Record<string, [number, number, number, number, number]> = {};
  let total = 0;
  for (const row of filtered) {
    const m = resolvedMttr(row);
    if (m === null) continue;
    const bucket =
      m <= RESOLUTION_BUCKET_EDGES[0] ? 0
      : m <= RESOLUTION_BUCKET_EDGES[1] ? 1
      : m <= RESOLUTION_BUCKET_EDGES[2] ? 2
      : m <= RESOLUTION_BUCKET_EDGES[3] ? 3
      : 4;
    const s = normalizeSeverity(row.severity);
    if (!perSev[s]) perSev[s] = [0, 0, 0, 0, 0];
    perSev[s][bucket] += 1;
    total += 1;
  }
  return { perSev, labels: RESOLUTION_BUCKET_LABELS, total };
}

// --------------------------------------------------------------------- open-past-SLA backlog

export interface OpenSlaSev {
  open: number;
  breached: number;
  pct: number | null;
  target: number | null;
}

export interface OpenSlaOverall {
  open: number;
  breached: number;
  pct: number | null;
}

export interface OpenPastSla {
  perSev: Record<string, OpenSlaSev>;
  overall: OpenSlaOverall;
}

/**
 * Open findings already older than their severity's SLA target — the aged backlog the
 * resolved-only "In SLA %" never scores. Over open rows with a finite age_days, breached iff
 * `age_days > SLA_TARGETS[sev]` (strict `>`, the dual of the in-SLA `d <= target`). A severity
 * with no target (e.g. UNKNOWN) gets `target: null` and never breaches. `pct` is null only when
 * `open === 0` (no open sample to score). `opts.scope` narrows to one register before computing.
 *
 * `opts.slaTargets` (severity -> days) defaults to `SLA_TARGETS`; a caller measuring one
 * register's own saved windows passes `settingsLogic.effectiveSlaTargets(settings)` instead,
 * the way `readModels.ts`'s `buildMttr` does for both the detection-clock and
 * actionable-clock calls.
 */
export function openPastSla(
  rows: ScopedRemediationRow[],
  opts?: { scope?: Scope; slaTargets?: Record<string, number> },
): OpenPastSla {
  const filtered = filterScope(rows, opts?.scope);
  const targets = opts?.slaTargets ?? SLA_TARGETS;
  const perSev: Record<string, OpenSlaSev> = {};
  let totalOpen = 0;
  let totalBreached = 0;
  for (const row of filtered) {
    const age = openAge(row);
    if (age === null) continue;
    const s = normalizeSeverity(row.severity);
    const target = targets[s] ?? null;
    const stat = perSev[s] ?? (perSev[s] = { open: 0, breached: 0, pct: null, target });
    stat.open += 1;
    totalOpen += 1;
    if (target !== null && age > target) {
      stat.breached += 1;
      totalBreached += 1;
    }
  }
  for (const stat of Object.values(perSev)) {
    stat.pct = stat.open ? (stat.breached / stat.open) * 100 : null;
  }
  return {
    perSev,
    overall: {
      open: totalOpen,
      breached: totalBreached,
      pct: totalOpen ? (totalBreached / totalOpen) * 100 : null,
    },
  };
}

/**
 * The `openPastSla.overall.breached` count computed from a current-scan FRAME (dotted records +
 * injected `now`), for a history-snapshot writer that would run before any ledger view exists —
 * the role gas/'s openPastSlaFromRecords plays for its own snapshot writer. Age comes from the
 * first-seen column (metrics.findCol) against `now`, not durable age_days, so it can disagree
 * slightly with a ledger-based trend series drawn from the same period. Rows missing a
 * first-seen timestamp, or whose severity has no SLA target, never count.
 */
export function openPastSlaFromRecords(records: Rec[], now?: number): number {
  if (!records.length) return 0;
  const nowMs = now ?? Date.now();
  const firstSeenCol = findCol(recordColumns(records), "firstSeenAt", "firstDetectedAt", "createdAt");
  if (!firstSeenCol) return 0;
  let breached = 0;
  for (const rec of records) {
    if (!isOpen(rec["status"])) continue;
    const first = parseTs(rec[firstSeenCol]);
    if (first === null) continue;
    const s = "severity" in rec ? normalizeSeverity(rec["severity"]) : "UNKNOWN";
    const target = SLA_TARGETS[s];
    if (target !== undefined && (nowMs - first) / DAY_MS > target) breached += 1;
  }
  return breached;
}

// --------------------------------------------------------------------- the actionable clock

/**
 * Re-project base rows onto the RemediationRow shape using the *actionable* clock —
 * mttr_actionable_days / actionable_age_days in place of the from-detection mttr_days /
 * age_days. Feed the result to openPastSla, kaplanMeier, or mttrPercentiles and they measure
 * from vendor-fix availability instead of first detection, with no change to their bodies.
 * Awaiting-vendor-fix rows carry null actionable fields, so they drop out of every clock here
 * automatically (a resolved row with no fix ever observed likewise has a null
 * mttr_actionable_days) while still counting in awaitingVendorFix / the open backlog.
 *
 * MTTR delayed-entry package: `opts.trackingStart` carries the tracking-start this clock's own
 * entry is measured against. UNLIKE the detection clock (whose entry rides on `BaseRow.
 * entry_days`, already relative to `first_seen`), the actionable clock starts at
 * `actionable_from` — a DIFFERENT origin whenever a fix arrives after detection — so its entry
 * has to be computed fresh here: `max(0, trackingStart - actionable_from) / DAY_MS`. Only sca
 * rows ever reach this view with a genuine `actionable_from` (D4b rule 3 / this file's own
 * header), so `opts.trackingStart` is a single scalar (that scope's tracking start) rather than
 * a per-scope map — every caller of this function already narrows to one scope first.
 */
export function actionableView(
  rows: (Pick<BaseRow, "severity" | "status" | "mttr_actionable_days" | "actionable_age_days"> &
    // `actionable_from` is OPTIONAL on the accepted row, not required: test/remediation.test.ts's
    // pre-existing bRes/bOpen fixtures (D4b, before this package) build rows without it, and
    // every one of those calls also omits `opts.trackingStart` — so `entryDaysFrom` reads
    // `undefined` for both its arguments and returns 0 regardless of whether this field was
    // supplied. Real callers (readModels.ts) always pass genuine `BaseRow`s, which carry it.
    Partial<Pick<BaseRow, "actionable_from">>)[],
  opts?: { trackingStart?: string | null },
): RemediationRow[] {
  // `entry_days` is left OFF the projected row entirely — not even `0` — when no
  // `opts.trackingStart` was supplied, rather than always computing `entryDaysFrom(undefined,
  // …)` (which would itself return 0). Both read the same to `kaplanMeier`'s own normalization
  // (RemediationRow.entry_days: absent/null/<=0 all mean "no delayed entry"), but an ALWAYS-
  // present `entry_days: 0` breaks the exact-shape `toEqual` assertions test/remediation.test.ts
  // already pins against this function's D4b-era output — the same reasoning KMResult's own new
  // fields follow (remediation.ts's `kaplanMeier` docstring).
  const hasTrackingStart = opts?.trackingStart !== undefined && opts?.trackingStart !== null;
  return rows.map((r) => ({
    severity: r.severity,
    status: r.status,
    mttr_days: r.mttr_actionable_days,
    age_days: r.actionable_age_days,
    entry_days: hasTrackingStart
      ? entryDaysFrom(opts!.trackingStart, r.actionable_from ?? null)
      : undefined,
  }));
}

export interface AwaitingVendorFix {
  perSev: Record<string, number>;
  overall: number;
  openTotal: number;
  pctOfOpen: number | null;
  /**
   * Open, non-sca rows (sast/secrets have no vendor to wait on) — counted here instead of
   * `overall`/`perSev` even when a row's own `awaiting_vendor_fix` flag reads true, so an
   * upstream derivation bug can never leak a "no vendor fix" claim onto a scope with no
   * vendor. D4b rule 3.
   */
  notApplicable: number;
}

/**
 * The "awaiting vendor fix" segment: OPEN, SCA findings with no vendor fix available yet
 * (awaiting_vendor_fix), which is exactly the population the actionable clock excludes — they
 * sit outside every SLA/MTTR deadline until a fix appears. perSev / overall count those rows by
 * normalized severity; openTotal is the full open backlog for context (every scope), and
 * pctOfOpen is the awaiting share of it — null when nothing is open, so the UI never renders a
 * fake 0% against an empty denominator. `opts.scope` narrows to one register before computing.
 *
 * sast and secrets rows are never counted in `overall`/`perSev` (see `notApplicable` and the
 * module header) — neither scope has a vendor to wait on, so a mistakenly-set
 * `awaiting_vendor_fix` flag on one of them is refused rather than trusted.
 */
export function awaitingVendorFix(
  rows: (Pick<BaseRow, "severity" | "status" | "awaiting_vendor_fix"> & { scope?: Scope })[],
  opts?: { scope?: Scope },
): AwaitingVendorFix {
  const filtered = filterScope(rows, opts?.scope);
  const perSev: Record<string, number> = {};
  let overall = 0;
  let openTotal = 0;
  let notApplicable = 0;
  for (const row of filtered) {
    if (!isOpen(row.status)) continue;
    openTotal += 1;
    if (row.scope !== undefined && row.scope !== "sca") {
      if (row.awaiting_vendor_fix) notApplicable += 1;
      continue;
    }
    if (!row.awaiting_vendor_fix) continue;
    const s = normalizeSeverity(row.severity);
    perSev[s] = (perSev[s] ?? 0) + 1;
    overall += 1;
  }
  return {
    perSev,
    overall,
    openTotal,
    pctOfOpen: openTotal ? (overall / openTotal) * 100 : null,
    notApplicable,
  };
}

// --------------------------------------------------------------------- latency clock

/**
 * Which end of the wait a latency clock starts from.
 *
 *   "detection" — first_seen. How long WE waited for a fix after finding it, so it pairs
 *                 additively with the actionable clock: exposure = latency + actionable.
 *
 * DIVERGENCE (D4b rule 2): gas/'s LatencyOrigin also carried "disclosure" (published_date —
 * CVE publication to fix), the vendor's own release latency. This register's ledger has no
 * published_date column at all (sca/sast/secrets all lack a publication timestamp — see
 * ledgerTypes.ts's LedgerRow), so that clock has no data source here and does not survive the
 * port. Kept as a type (of one member) rather than inlined so a future package that adds a
 * disclosure-equivalent field doesn't have to touch every latencyView/latencySegments call
 * site.
 */
export type LatencyOrigin = "detection";

/**
 * How a latency population divides up. Reported beside the estimate rather than inferred from
 * it, because `kaplanMeier` silently drops a row that is neither event nor censored and a
 * reader cannot tell a small register from a badly-measured one otherwise.
 *
 * `events + censored + closedBeforeFix + unmeasured === total`, and two containments:
 * `zeroAtOrigin ⊆ events`, while `censored + closedBeforeFix === KMResult.censored`.
 */
export interface LatencySegments {
  /** A vendor fix became available and we observed when. */
  events: number;
  /** Still open with no fix — censored at now. The population the metric exists for. */
  censored: number;
  /**
   * Resolved without a fix ever being observed — the repository went away, the finding was
   * ignored, or Wiz simply stopped returning it. Censored at its resolution, because that is
   * when we stopped being able to observe a fix. It is a competing risk and not a fix, so it
   * is counted apart: `resolution_src` only distinguishes `api` from `disappeared`, never
   * "patched" from "abandoned", so a cause-specific model is not available and this counter is
   * the honest substitute.
   */
  closedBeforeFix: number;
  /** Events at t=0 — the fix already existed at the origin. Subset of `events`. */
  zeroAtOrigin: number;
  /** Origin (first_seen) never captured, so the row is outside the estimate entirely. */
  unmeasured: number;
  /** Every row considered, measured or not. */
  total: number;
}

/**
 * A base row projected onto just the columns the latency clock reads.
 *
 * `entry_days` rides straight through from `BaseRow` rather than being recomputed: every
 * `latencyObservation` time `t` below is measured relative to `first_seen` (fixAvail-first,
 * resolved-first, now-first), the SAME origin `BaseRow.entry_days` is already relative to
 * (ledgerCore.ts's `withDerived`), so this clock's delayed-entry offset IS the detection
 * clock's — no second `entryDaysFrom` call needed, unlike `actionableView`'s different origin.
 */
type LatencyRow = Pick<
  BaseRow,
  "severity" | "status" | "first_seen" | "fix_available_at" | "resolved_at" | "entry_days"
> & { scope?: Scope };

/** One row's classification: null when it contributes to no clock. */
function latencyObservation(
  row: LatencyRow,
  nowMs: number,
): { t: number; event: boolean; closedBeforeFix: boolean } | null {
  const first = parseTs(row.first_seen);
  if (first === null) return null; // origin never captured

  const fixAvail = parseTs(row.fix_available_at);
  if (fixAvail !== null) {
    const raw = fixAvail - first;
    // Wiz's upstream fixDate routinely predates our first sight of the finding. That is a
    // real zero-length wait, not a negative one — clamp rather than let a negative duration
    // into the risk set.
    return { t: Math.max(0, raw) / DAY_MS, event: true, closedBeforeFix: false };
  }

  const resolved = parseTs(row.resolved_at);
  if (resolved !== null) {
    return { t: Math.max(0, resolved - first) / DAY_MS, event: false, closedBeforeFix: true };
  }
  // Open with no fix yet: censored at now.
  if (isOpen(row.status)) {
    return { t: Math.max(0, nowMs - first) / DAY_MS, event: false, closedBeforeFix: false };
  }
  return null;
}

/**
 * Re-project base rows onto the RemediationRow shape using a *latency* clock: the wait for a
 * vendor fix to exist, rather than the wait to deploy one. Feed the result to `kaplanMeier` and
 * it measures that wait with no change to its body — the same trick `actionableView` plays.
 *
 * This is the complement of every other clock here. The actionable clock starts where a fix
 * becomes available; this one ends there. Rows still awaiting a fix are the CENSORED
 * population rather than an excluded one, which is the whole point — dropping them would leave
 * only the findings that got fixed and measure how fast the fixed ones were fixed, the
 * survivorship bias the KM estimator exists to avoid.
 *
 * Note the projected `status`: an event carries "RESOLVED" and a censored row "OPEN", because
 * `openAge` gates on `isOpen(status)` while `resolvedMttr` does not. A finding that closed
 * before any fix appeared is therefore projected as "OPEN" even though it is resolved — it is
 * censored, not an event, and the projection has to say so in the only vocabulary the
 * estimator reads. `opts.scope` narrows to one register before computing.
 */
export function latencyView(
  rows: LatencyRow[],
  origin: LatencyOrigin,
  now?: number,
  opts?: { scope?: Scope },
): RemediationRow[] {
  const nowMs = now ?? Date.now();
  const filtered = filterScope(rows, opts?.scope);
  const out: RemediationRow[] = [];
  for (const row of filtered) {
    const obs = latencyObservation(row, nowMs);
    if (obs === null) continue;
    out.push({
      severity: row.severity,
      status: obs.event ? "RESOLVED" : "OPEN",
      mttr_days: obs.event ? obs.t : null,
      age_days: obs.event ? null : obs.t,
      entry_days: row.entry_days,
    });
  }
  return out;
}

/**
 * The segment counts behind a `latencyView` population, classified by the same predicate in
 * the same order — split out rather than reimplemented so the counters and the curve cannot
 * disagree about which rows were measured.
 */
export function latencySegments(
  rows: LatencyRow[],
  origin: LatencyOrigin,
  now?: number,
  opts?: { scope?: Scope },
): LatencySegments {
  const nowMs = now ?? Date.now();
  const filtered = filterScope(rows, opts?.scope);
  const seg: LatencySegments = {
    events: 0, censored: 0, closedBeforeFix: 0, zeroAtOrigin: 0, unmeasured: 0, total: 0,
  };
  for (const row of filtered) {
    seg.total += 1;
    const obs = latencyObservation(row, nowMs);
    if (obs === null) {
      seg.unmeasured += 1;
    } else if (obs.event) {
      seg.events += 1;
      if (obs.t === 0) seg.zeroAtOrigin += 1;
    } else if (obs.closedBeforeFix) {
      seg.closedBeforeFix += 1;
    } else {
      seg.censored += 1;
    }
  }
  return seg;
}

// --------------------------------------------------------------------- no-fix predicates

/**
 * "No fix" predicate over a durable base row — an OPEN, SCA finding with no vendor fix
 * available yet (exactly `awaiting_vendor_fix`). Resolved rows carry `awaiting_vendor_fix ===
 * false`, so they are never hidden. The choke-point filter behind the global "show findings
 * without a vendor fix" toggle.
 *
 * DIVERGENCE (D4b rule 3): sast/secrets have no vendor, so this refuses to call a non-sca row
 * no-fix even if `awaiting_vendor_fix` reads true on it — the guard is a property of the
 * predicate itself, not something every upstream derivation has to get right on its own.
 */
export function baseRowNoFix(row: Pick<BaseRow, "scope" | "awaiting_vendor_fix">): boolean {
  return row.scope === "sca" && row.awaiting_vendor_fix === true;
}

/**
 * The frame-record equivalent of baseRowNoFix, for the current-scan record surfaces that run
 * before (or without) a ledger view. Mirrors the same `fixedVersion || fixDate` presence test
 * reconcile.ts uses to derive fix_observed_at.
 *
 * DIVERGENCE (D4b rule 2): gas/'s recordNoFix also exempted a record first seen before
 * REMEDIATION_ROLLOUT_ISO (a fix by construction, under the old hasFix-only ingestion filter).
 * This is a fresh register with no such legacy migration, so that branch is dropped outright.
 *
 * DIVERGENCE (D4b rule 3): a record explicitly tagged with a non-sca `scope` is never no-fix —
 * same guard as baseRowNoFix, applied to the frame shape. A record with no `scope` key at all
 * (the common case: a single-scope scan's records are homogeneous by construction — see
 * metrics.ts's header) is not dropped by the guard, matching filterScope's "absent scope
 * survives" convention.
 */
export function recordNoFix(rec: Rec): boolean {
  if ("scope" in rec && rec["scope"] !== "sca") return false;
  if (!isOpen(rec["status"])) return false;
  return !(present(rec["fixedVersion"]) || present(rec["fixDate"]));
}
