// Emits src/components/<Name>.jsx, src/index.jsx and dist/index.d.ts from spec.mjs.
// Run: node .design-sync/adapter/gen.mjs
import { writeFileSync, mkdirSync, readdirSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { COMPONENTS, SHARED_TYPES } from "./spec.mjs";

const root = dirname(fileURLToPath(import.meta.url));
const compDir = join(root, "src", "components");
const distDir = join(root, "dist");
mkdirSync(compDir, { recursive: true });
mkdirSync(distDir, { recursive: true });

// The shared core lives in gas_shared/, not in a register and not here. Four levels up
// from src/components/. It was gas_devsecops/src/client/js/ui until the design system was
// cut into its own package; the modules are byte-identical, only the path moved.
const UI = "../../../../gas_shared/ui";
// `nameCell` split out of cells.js on the way: it is the one cell renderer that reaches
// icons.js (512 lines of node-kind SVG), and `absent()` must not drag that in.
const MOD_MOVED = { nameCell: "nodeCell" };

const isFn = (t) => t.includes("=>");
const wrap = (text, width, indent) => {
  const words = String(text).split(/\s+/);
  const lines = [];
  let line = "";
  for (const w of words) {
    if (line && (line + " " + w).length > width) {
      lines.push(line);
      line = w;
    } else line = line ? line + " " + w : w;
  }
  if (line) lines.push(line);
  return lines.map((l) => indent + l).join("\n");
};

function jsdoc(c) {
  const lines = [" * " + wrap(c.doc, 92, "").split("\n").join("\n * ")];
  if (c.props.length) {
    lines.push(" *");
    for (const p of c.props) {
      if (!p.d) continue;
      lines.push(" * @param " + p.n + " " + p.d);
    }
  }
  return "/**\n" + lines.join("\n") + "\n */";
}

// ------------------------------------------------------------------ components
const byMod = new Map();
for (const c of COMPONENTS) {
  if (!byMod.has(c.mod)) byMod.set(c.mod, new Set());
  byMod.get(c.mod).add(c.factory);
}

// Wipe stale generated files so a renamed component cannot linger.
for (const f of readdirSync(compDir)) rmSync(join(compDir, f));

for (const c of COMPONENTS) {
  const slots = c.slots || [];
  const fnKeys = c.props.filter((p) => isFn(p.t)).map((p) => p.n);
  // Severity components derive their entries from a counts record, so they also need
  // sevEntries — which lives in the same module, hence one merged import.
  const needsEntries = c.call.includes("sevEntries");
  const named = [c.factory];
  // `after` may call a sibling helper from the same module (axisBar -> axisSegments).
  if ((c.after || "").includes("axisSegments")) named.push("axisSegments");
  const extra = [];
  if (needsEntries) {
    if (c.mod === "severity") named.push("sevEntries");
    else extra.push(`import { sevEntries } from "${UI}/severity.js";`);
  }
  const imports = [
    'import React from "react";',
    'import { Mounted, Slots, sigOf, useSlot, useStableProps } from "../mount.jsx";',
    `import { ${[...new Set(named)].join(", ")} } from "${UI}/${MOD_MOVED[c.factory] || c.mod}.js";`,
    ...extra,
  ];
  if (needsEntries) {
    imports.push(
      'const DEFAULT_SEV_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", "UNKNOWN"];',
    );
  }

  const body = [];
  body.push("  const p = useStableProps(props || {}, " + JSON.stringify(fnKeys) + ");");
  if (slots.length) {
    body.push(
      "  const S = {\n" +
        slots
          .map((s) => `    ${s}: useSlot(p.${s} !== undefined && p.${s} !== null),`)
          .join("\n") +
        "\n  };",
    );
  } else {
    body.push("  const S = {};");
  }
  body.push("  const sig = sigOf(p, " + JSON.stringify(slots) + ");");
  const build = c.after
    ? `() => {\n        const node = ${c.call};\n        ${c.after};\n        return node;\n      }`
    : `() => ${c.call}`;
  if (slots.length) {
    body.push("  return (");
    body.push("    <>");
    body.push(`      <Mounted sig={sig} build={${build}} />`);
    body.push(
      "      <Slots pairs={[" +
        slots.map((s) => `[S.${s}, p.${s}]`).join(", ") +
        "]} />",
    );
    body.push("    </>");
    body.push("  );");
  } else {
    body.push(`  return <Mounted sig={sig} build={${build}} />;`);
  }

  writeFileSync(
    join(compDir, c.name + ".jsx"),
    imports.join("\n") +
      "\n\n" +
      jsdoc(c) +
      "\nexport function " +
      c.name +
      "(props) {\n" +
      body.join("\n") +
      "\n}\n",
  );
}

// ----------------------------------------------------------------------- index
writeFileSync(
  join(root, "src", "index.jsx"),
  "// Generated by gen.mjs from spec.mjs — do not edit.\n" +
    COMPONENTS.map((c) => `export { ${c.name} } from "./components/${c.name}.jsx";`).join("\n") +
    "\n",
);

// ------------------------------------------------------------------------ d.ts
const iconNames = [
  "close", "chevron-up", "chevron-down", "chevron-left", "chevron-right", "widen", "grip",
  "braces", "link", "external", "info", "graph", "plus", "minus", "group", "layout", "rows",
  "lanes", "organic", "radial", "fit", "eye", "eye-off", "table", "columns", "pencil",
  "search", "filter", "property", "check", "not", "branch", "folder", "tag", "folders",
  "doc", "bookmark", "dock", "undock",
];

const dts = [
  "// Generated by gen.mjs from spec.mjs — do not edit.",
  'import * as React from "react";',
  "",
  SHARED_TYPES,
  "",
  "/** Every icon in the interface set. */",
  "export type UiIconName =",
  iconNames.map((n) => `  | ${JSON.stringify(n)}`).join("\n") + ";",
  "",
];

for (const c of COMPONENTS) {
  dts.push("/**\n" + wrap(c.doc, 92, " * ") + "\n */");
  dts.push(`export interface ${c.name}Props {`);
  for (const p of c.props) {
    if (p.d) dts.push("  /** " + p.d + " */");
    dts.push(`  ${p.n}${p.req ? "" : "?"}: ${p.t};`);
  }
  dts.push("}");
  dts.push(`export declare function ${c.name}(props: ${c.name}Props): React.ReactElement;`);
  dts.push("");
}

writeFileSync(join(distDir, "index.d.ts"), dts.join("\n"));

console.log(
  `generated ${COMPONENTS.length} components across ${new Set(COMPONENTS.map((c) => c.group)).size} groups`,
);
