/*
 * The tenant's own schema vocabulary, read by introspection on 2026-08-20 with
 * `npm run probe -- --vocab-only`. Nothing is scrubbed: these are type and relationship
 * NAMES, not tenant data.
 *
 * WHY THIS FILE EXISTS. For the whole life of this app, "does this tenant have that
 * relationship?" was answered from someone's execution log. Four traversals shipped names
 * taken from planning docs and ran refused for months; the correcting probe's output — the
 * hundred names below — was read once and never written down, so every later decision had to
 * re-run the probe or trust a memory of it. Two things went wrong for exactly that reason: a
 * name was inferred from a sample instead of asked of the schema, and seven relationships
 * were held back as "no evidence in this repo" when the tenant had all seven.
 *
 * So this is the authority. A new hop cites a line in this file or it does not ship.
 *
 * UNLIKE THE OTHER CAPTURES HERE, this one is a real module. The rest of exemples/ is raw
 * request and response text that nothing imports (test/graphExpand.test.ts inlines its
 * fixtures and says so). This file is meant to be READ BY A TEST — the point of writing the
 * vocabulary down is that a check can cite it — so it carries ESM exports rather than the
 * inert `module.exports` the sibling captures use under this package's "type": "module".
 *
 * WHAT IT SETTLES, on the day it was captured:
 *
 *   · 100 relationships, 252 entity types — the figure the investigation remembered, confirmed.
 *   · Of the 23 kinds `EDGE_TYPES` declares (domain/graphTypes.ts), FIVE are relationships this
 *     tenant has: ALLOWS_ACCESS_TO, USES, BUILT_FROM, HAS_DATA_FINDING, SERVES. That is the
 *     "23 declared, 5 exist" claim, now checkable rather than recalled. Note BUILT_FROM among
 *     them: ai/AARS_SCORING_ASSESSMENT.md filed it under "sampleData.ts only", which was true
 *     of the app and not of the tenant.
 *   · RUNS_AS, HAS_FINDING, PROTECTED_BY, BOUND_TO and PERMITS_ACCESS_ROLE are all absent, as
 *     are USES_TOOL, USES_MODEL, USES_DATASET, STORED_IN, INVOKES_TOOL, CAN_INVOKE, ENFORCES,
 *     HOSTED_ON and HAS_ISSUE. Near-misses are not substitutes: the tenant has PERMITS but not
 *     PERMITS_ACCESS_ROLE, HOSTS but not HOSTED_ON, INVOKES but not CAN_INVOKE.
 *   · VERSION_OF, REGISTERED_IN, HAS_DATA_STORE, CALLS, SEND_MESSAGES_TO, INTEGRATED_WITH and
 *     DEPENDS_ON all EXIST. domain/lineageQuery.ts held them back for want of exactly this
 *     file; they are available to a traversal that wants them, with the standing point still
 *     to be argued.
 *   · AI_SECURITY_FINDING is an entity type on this tenant and appears nowhere in this
 *     codebase — a class of AI findings nothing collects.
 *
 * Refresh it by re-running the probe; a diff is a schema change.
 */

/** When the introspection above was read. */
export const capturedAt = "2026-08-20T18:28:30.694Z";

/** GraphRelationshipType — every relationship name a traversal may send. */
export const relationships = [
  "ACCESSIBLE_BY", "ACTING_AS", "ADMINISTRATE", "ALERTED_ON", "ALIAS_OF", "ALLOWS",
  "ALLOWS_ACCESS_TO", "ANY", "ANY_OUTGOING", "APPLIES_TO", "ASSIGNED_TO",
  "ASSIGNS_ON_REGISTRATION", "ATTACHED_TO", "BACKS_UP", "BASE_IMAGE_OF", "BEHIND", "BOOTS",
  "BUILT_FROM", "CALLS", "CAUSES", "CODE_AUTHOR", "COLLABORATES", "CONNECTED_TO",
  "CONSENTED_BY", "CONTAINS", "CONTAINS_DST", "CONTAINS_DST_IP_RANGE",
  "CONTAINS_DST_PORT_RANGE", "CONTAINS_SRC", "CONTAINS_SRC_IP_RANGE",
  "CONTAINS_SRC_PORT_RANGE", "CREATED_BY", "DENIES", "DEPENDS_ON", "DEPLOYED_TO", "ENCRYPTS",
  "ENCRYPTS_PARTITION", "ENTITLES", "EXCLUDES", "EXPOSES", "FORKED_FROM", "GOVERNS", "HAS",
  "HAS_ASSIGNMENT", "HAS_BOUNDARY_POLICY", "HAS_DATA_FINDING", "HAS_DATA_INVENTORY",
  "HAS_DATA_SCHEMA", "HAS_DATA_STORE", "HAS_ORGANIZATION_POLICY", "HAS_PRINCIPAL_POLICY",
  "HAS_PRIVATE_KEY", "HAS_PUBLIC_KEY", "HAS_RESOURCE_POLICY", "HAS_SNAPSHOT", "HAS_SOURCE",
  "HAS_STANDARD_WEB_ACCESS_FROM", "HAS_TECH", "HOSTS", "IDENTIFIED_FOR", "IGNORES",
  "IMPLEMENTS", "INCLUDES", "INFECTS", "INSIDE", "INSTANCE_OF", "INTEGRATED_WITH", "INVOKES",
  "IS_CODE_OWNER", "LOGS_DATA_FOR", "MANAGES", "MOUNTS", "OWNS", "PART_OF", "PEERED_TO",
  "PERFORMED", "PERFORMED_IMPERSONATED", "PERMITS", "POINTS_TO", "PRODUCES", "PROTECTS",
  "READS_DATA_FROM", "REFERENCED_BY", "REGISTERED_IN", "REPLICA_OF", "RESOLVES_TO",
  "ROUTES_TRAFFIC_FROM", "ROUTES_TRAFFIC_TO", "RUNS", "SCANNED", "SCOPED_TO",
  "SEND_MESSAGES_TO", "SERVES", "SOURCE_MAPPED", "STORES_DATA_IN", "SUSPECTED_DECLARED_BY",
  "TRANSIT_PEERED_TO", "USES", "VALIDATES", "VERSION_OF",
];

/** GraphEntityType — every entity type a traversal may name. */
export const entityTypes = [
  "ANY", "ACCESS_FINDING", "ACCESS_KEY", "ACCESS_ROLE", "ACCESS_ROLE_BINDING",
  "ACCESS_ROLE_PERMISSION", "AI_AGENT", "AI_AGENT_REGISTRY", "AI_DATASET", "AI_DEPLOYMENT",
  "AI_EXTENSION", "AI_GATEWAY", "AI_GUARDRAIL", "AI_MODEL", "AI_PIPELINE",
  "AI_SECURITY_FINDING", "AI_SERVICE", "AI_SKILL", "AI_SKILL_TEMPLATE", "AI_TOOL",
  "API_ENDPOINT", "API_GATEWAY", "APPLICATION", "ARTIFACT", "ARTIFACT_REGISTRY",
  "ARTIFACT_REPOSITORY", "ATTACK_SURFACE_FINDING", "AUTHENTICATION_CONFIGURATION",
  "AUTHENTICATION_POLICY", "BACKUP_SERVICE", "BRANCH_PACKAGE", "BUCKET", "CALL_CENTER_SERVICE",
  "CDN", "CICD_SERVICE", "CI_JOB", "CI_RUNNER", "CI_RUNNER_CONFIG", "CI_WORKFLOW",
  "CLOUD_COST_COMMITMENT", "CLOUD_COST_MONITOR_FINDING", "CLOUD_COST_OPPORTUNITY",
  "CLOUD_LOG_CONFIGURATION", "CLOUD_ORGANIZATION", "CLOUD_RESOURCE", "CODE_APPLICATION",
  "CODE_CRYPTOGRAPHIC_ALGORITHM", "CODE_MODULE", "CODE_SNIPPET", "COLLABORATION_WORKSPACE",
  "COMMUNICATION_SERVICE", "COMPUTE_INSTANCE_CONFIGURATION", "COMPUTE_INSTANCE_GROUP",
  "CONFIGURATION_FINDING", "CONFIGURATION_RULE", "CONFIGURATION_SCAN", "CONFIG_MAP",
  "CONTAINER", "CONTAINER_GROUP", "CONTAINER_IMAGE", "CONTAINER_INSTANCE_GROUP",
  "CONTAINER_REGISTRY", "CONTAINER_REPOSITORY", "CONTAINER_SERVICE", "CONTROLLER_REVISION",
  "CRM_TABLE", "DAEMON_SET", "DATABASE", "DATABASE_TABLE", "DATASET_CONFIGURATION",
  "DATA_CATALOG", "DATA_CONNECTOR", "DATA_FINDING", "DATA_INVENTORY", "DATA_NETWORK_POLICY",
  "DATA_PROCEDURE", "DATA_RESOURCE", "DATA_SCHEMA", "DATA_STORE", "DATA_WORKFLOW",
  "DATA_WORKLOAD", "DB_SERVER", "DEDICATED_INFRASTRUCTURE", "DEPLOYMENT",
  "DEVELOPMENT_SERVICE", "DISK_USAGE", "DNS_PRIVATE_RESOLVER", "DNS_RECORD", "DNS_ZONE",
  "DOMAIN", "EMAIL_SERVICE", "ENCRYPTION_KEY", "ENDPOINT", "EXCESSIVE_ACCESS_FINDING",
  "FILE_DESCRIPTOR", "FILE_DESCRIPTOR_FINDING", "FILE_STORAGE", "FILE_SYSTEM_SERVICE",
  "FINDING", "FIREWALL", "FIREWALL_CONFIGURATION", "GATEWAY", "GOVERNANCE_POLICY",
  "GOVERNANCE_POLICY_ASSIGNMENT", "GOVERNANCE_POLICY_GROUP", "GROUP", "HOSTED_APPLICATION",
  "HOSTED_TECHNOLOGY", "HOST_CONFIGURATION_FINDING", "HOST_CONFIGURATION_RULE",
  "HYBRID_STORAGE_SERVICE", "IAC_BACKEND", "IAC_DECLARATION_INSTANCE", "IAC_DEPLOYMENT",
  "IAC_DEPLOYMENT_GROUP", "IAC_FINDING", "IAC_MODULE", "IAC_RESOURCE_DECLARATION",
  "IAC_STATE_INSTANCE", "IAM_BINDING", "IDE", "IDENTITY", "IDENTITY_PROVIDER",
  "INTERNAL_CLOUD_SERVICE", "IO_T_DEVICE", "IO_T_DEVICE_GROUP", "IO_T_JOB",
  "IO_T_ROUTING_RULE", "IP_ADDRESS_GROUP", "IP_ADDRESS_POOL", "IP_RANGE", "KUBERNETES_CLUSTER",
  "KUBERNETES_CRON_JOB", "KUBERNETES_CUSTOM_RESOURCE", "KUBERNETES_CUSTOM_RESOURCE_DEFINITION",
  "KUBERNETES_INGRESS", "KUBERNETES_INGRESS_CONTROLLER", "KUBERNETES_JOB",
  "KUBERNETES_NETWORK_POLICY", "KUBERNETES_NODE", "KUBERNETES_PERSISTENT_VOLUME",
  "KUBERNETES_PERSISTENT_VOLUME_CLAIM", "KUBERNETES_POD_SECURITY_POLICY",
  "KUBERNETES_POD_TEMPLATE", "KUBERNETES_REPLICATION_CONTROLLER", "KUBERNETES_RESOURCE",
  "KUBERNETES_SERVICE", "KUBERNETES_STORAGE_CLASS", "LAST_LOGIN", "LATERAL_MOVEMENT_FINDING",
  "LOAD_BALANCER", "LOCAL_GROUP", "LOCAL_USER", "MAILBOX", "MALWARE", "MALWARE_INSTANCE",
  "MANAGED_CERTIFICATE", "MANAGED_JUMP_SERVER", "MANAGEMENT_SERVICE", "MAP_REDUCE_CLUSTER",
  "MCP_SERVER", "MEDIA_SERVICE", "MESH_GATEWAY", "MESH_VIRTUAL_SERVICE", "MESSAGING_SERVICE",
  "METADATA_REPOSITORY", "MONITOR_ALERT", "MONITOR_SERVICE", "NAMESPACE", "NAT",
  "NETWORK_ADDRESS", "NETWORK_APPLIANCE", "NETWORK_CONNECTION_USAGE", "NETWORK_INTERFACE",
  "NETWORK_MANAGEMENT_SERVICE", "NETWORK_ROUTING_RULE", "NETWORK_SECURITY_RULE", "PACKAGE",
  "PEERING", "PEN_TEST_FINDING", "POD", "POLICY_STATEMENT", "PORT_RANGE", "PREDEFINED_GROUP",
  "PRINCIPAL", "PRINCIPAL_DIRECTORY", "PRIVATE_ENDPOINT", "PRIVATE_KEY_BINDING",
  "PRIVATE_LINK", "PROXY_RULE", "RAW_ACCESS_POLICY", "REGION", "REGISTERED_DOMAIN",
  "REPLICA_SET", "REPOSITORY", "REPOSITORY_BRANCH", "REPOSITORY_TAG", "RESOURCE_GROUP",
  "ROUTE_TABLE", "SAST_FINDING", "SAST_RULE", "SCHEMA_CONFIGURATION", "SEARCH_INDEX", "SECRET",
  "SECRET_CONTAINER", "SECRET_DATA", "SECRET_INSTANCE", "SECURITY_EVENT_FINDING",
  "SECURITY_TOOL_FINDING", "SECURITY_TOOL_FINDING_TYPE", "SECURITY_TOOL_SCAN", "SERVERLESS",
  "SERVERLESS_PACKAGE", "SERVICE_ACCOUNT", "SERVICE_BLUEPRINT", "SERVICE_CONFIGURATION",
  "SERVICE_DISCOVERY_ENDPOINT", "SERVICE_DISCOVERY_NAMESPACE", "SERVICE_DISCOVERY_SERVICE",
  "SERVICE_PORTAL", "SERVICE_QUOTA", "SERVICE_USAGE_TECHNOLOGY", "SIMULATION_SERVICE",
  "SNAPSHOT", "SOFTWARE_SUPPLY_CHAIN_RULE", "STATEFUL_SET", "STORAGE_ACCOUNT", "SUBNET",
  "SUBSCRIPTION", "SUPPLY_CHAIN_FINDING", "SUPPLY_CHAIN_RULE", "SWITCH", "TARGET_GROUP",
  "TECHNOLOGY", "TELECOM_NETWORK", "TICKETING_TABLE", "TRAFFIC_MIRROR_SERVICE", "USAGE",
  "USER_ACCOUNT", "VERSION_CONTROL_RESOURCE", "VIRTUAL_DESKTOP", "VIRTUAL_DRIVE",
  "VIRTUAL_MACHINE", "VIRTUAL_MACHINE_IMAGE", "VIRTUAL_NETWORK", "VIRTUAL_WORKSPACE",
  "VIRTUAL_WORKSTATION", "VOLUME", "VULNERABILITY", "WEAKNESS", "WEB_SERVICE", "WORKSTATION",
];
